CONTRIBUTING.md
Add git-commit messages convention to the `CONTRIBUTING.md` file.
=> Add git-commit messages convention

config/src/lib.rs, core/src/lib.rs, crypto/src/lib.rs, data_structures/src/lib.rs, p2p/src/lib.rs, storage/src/lib.rs
Force contributors to write docs for public api(but you still by-pass by applying `#[allow(missing_docs]` onto certain items), it'll benefit both developing and contributing.
r? @aesedepece
=> deny missing docs for public api

.travis.yml
This PR is a workaround it is not possible to `#[allow(clippy)]` in both beta and nightly versions.
In the nightly version, the following works
```
#![feature(tool_lints)]
#![allow(clippy::all)]
```
However, in the beta version, `features` are not supported and the allow does not work.
In the near future, once the nightly becomes a beta, then this workaround should be removed.
More info can be found [here](https://github.com/rust-lang/rust/pull/54358).
=> ci(travis): run clippy only in nightly

.travis.yml, docs/architecture/managers/peers-manager.md
This PR is a workaround due to the last nightly toolchain does not include clippy.
The issue #78 should restore the temporal fix described in #77 .
=> fix(travis): use a previous nightly in to order have clippy available

core/src/actors/config_manager.rs, core/src/actors/connections_manager.rs, core/src/actors/peers_manager.rs, core/src/actors/sessions_manager.rs, core/src/actors/storage_manager.rs
This PR refactors the way actors communicate with the `ConfigManager`.
Some repetitive code was being used when an actor needed to communicate with the `ConfigManager` in order to get the configuration and extract some parameter from it.
With this PR, the `ConfigManager` provides a public method `send_get_config_request` that other actors can use to send a `GetConfig` message to the `ConfigManager`. Those other actors need to provide a function to process the configuration when received.
This PR implements this new way of communicating with `ConfigManager` for the actors: `PeersManager`, `SessionsManager` and `ConnectionsManager`.
=> refactor(core): add function in ConfigManager to send GetConfig message

core/src/actors/connections_manager.rs, core/src/actors/session.rs, core/src/actors/sessions_manager.rs, p2p/src/sessions/bounded_sessions.rs, p2p/src/sessions/mod.rs, p2p/tests/bounded_sessions.rs, p2p/tests/sessions.rs
This PR adds separate consolidated / unconsolidated collections for outbound sessions in `p2p sessions library`. The p2p sessions library is the one that contains the state and most of the logic of the session manager. Inbound sessions are left in the same collection, no matter what their status is.
Tests for the `p2p sessions library` have been adapted to this new logic. Also, the actors that used that refactored logic in some way have been adapted.
Additionally, some extra logic that was left in the `SessionsManager` actor has been extracted from it and written in the library instead. New tests have been implemented for this new logic.
=> refactor(p2p): add separate consolidated/unconsolidated collections for outbound sessions

.gitignore, config/src/lib.rs, core/src/actors/config_manager.rs, docs/architecture/managers/config-manager.md, docs/configuration/cli.md, docs/configuration/toml-file.md, mkdocs.yml
Documentation comments for the config crate.
In order to test run: `cargo doc -p witnet_config --open` and you should find all structs and their fields commented.
Also created a section in the project-level docs with the config params explained.
=> chore(config doc): Document config fields and default values

Justfile, core/src/actors/storage_manager.rs
* Add version information to the Justfile to prevent similar issues in the future.
* `Put` now has a `new` method which takes raw bytes, and `from_value` which takes a `Storable` type.
=> fix(actors): rename new to from_value in order to fix clippy warnings

config/src/config/mod.rs, config/src/config/partial.rs, config/src/defaults.rs, core/src/actors/mod.rs, core/src/actors/peers_manager.rs, core/src/actors/storage_keys.rs, docs/architecture/managers/peers-manager.md, p2p/Cargo.toml, p2p/src/peers/mod.rs
Define a new config parameter named storage_peers_period.
Implement a function on Peers Manager to dump periodically peers into storage through sending a Put message to Storage Manager
Add documentation to peers manager doc 
Close #97
=> feat(managers): periodically persist peers into storage 

config/src/config/partial.rs, config/src/loaders/toml.rs
Allow to set
```toml
[connections]
bootstrap_peers_period_seconds = 10
```
=> fix(config): read duration as seconds from file

config/src/config/mod.rs, config/src/config/partial.rs, config/src/defaults.rs, core/src/actors/sessions_manager.rs, docs/architecture/managers/sessions-manager.md, docs/architecture/session.md
Define a new config parameter named discovery_peers_period.
Implement a function on Session Manager to call to itself with Anycast(GetPeers) (see #87).
Add documentation to SessionsManager and Sessions
Close #90
=> feat(managers): implement algorithm for peer discovery in SessionManager

core/src/actors/peers_manager.rs
Fixes the debug message "Added the following addresses from storage" which isn't working properly.
=> fix(core): print all peers added from storage

core/src/actors/sessions_manager/handlers.rs, core/src/actors/sessions_manager/messages.rs, docs/architecture/managers/sessions-manager.md, p2p/src/sessions/mod.rs
Similarly to the anycast message, the broadcast message forwards the wrapped message to all the consolidated outbound sessions.
In order to broadcast a message, the message needs to implement Clone.
Proof of work: sending a `Broadcast<GetPeers>`:
=> feat(core): add broadcast message to sessions manager

config/src/config/mod.rs, config/src/config/partial.rs, config/src/defaults.rs, config/src/loaders/toml.rs, docs/configuration/environment.md, docs/configuration/toml-file.md
This PR implements the first three actionables of #152 :
- Add a new `[jsonrpc]` section in configuration and a `server_address` param under it.
- Add tests for it
- Add documentation for this new section and parameter
`ConfigManager` already reads the whole configuration, no change was required for that.
This PR does not close the issue #152 , as more work is required.
=> feat(config): add jsonrpc section and server_address under it

core/src/actors/blocks_manager/actor.rs, core/src/actors/blocks_manager/handlers.rs, core/src/actors/blocks_manager/mod.rs, core/src/actors/epoch_manager/handlers.rs, core/src/actors/epoch_manager/messages.rs, core/src/actors/epoch_manager/mod.rs, core/src/actors/mod.rs, core/src/actors/node.rs, core/src/actors/peers_manager/mod.rs, docs/architecture/managers/blocks-manager.md, docs/architecture/managers/epoch-manager.md, mkdocs.yml
This PR adds the functionality described in #105 and #107 for the `EpochManager`, that is:
- Handler for the `SubscribeEpoch` message in the `EpochManager` for other actors to subscribe to a particular epoch. The `SubscribeEpoch` message contains a notification object that implements the `NotificationSender` trait and knows how to notify the subscriber actor when that epoch is reached. When the message is received at the `EpochManager`, that notification object is stored in the `EpochManager` state.
- Handler for the `SubscribeAll` message in the `EpochManager` for other actors to subscribe to all epochs. The `SubscribeAll` message contains a notification object that implements the `NotificationSender` trait and knows how to notify the subscriber actor when a new epoch is reached. When …
=> feat(core): add subscribe and notify functionality in EpochManager

config/src/config/mod.rs, config/src/config/partial.rs, config/src/defaults.rs, config/src/loaders/toml.rs, core/src/actors/blocks_manager/actor.rs, core/src/actors/blocks_manager/mod.rs, core/src/actors/storage_keys.rs, data_structures/Cargo.toml, data_structures/src/chain.rs, data_structures/src/lib.rs, docs/architecture/managers/blocks-manager.md
This PR implements the requirements for the issues #130 #146 #150 
- Fix typo in config parameter `checkpoints_period`.
- Implement ChainInfo data structure.
- Make BlocksManager query ConfigManager for environment name and protocol constants and keep all that info into state.
- Make BlocksManager query StorageManager for the stored ChainInfo upon startup.
- Update documentation to reflect BlocksManager actor state.
- Update documentation to reflect all the new behavior and outcoming actor messages.
Close #130 
Close #146 
Close #150
=> feat(core): Create ChainInfo data structure and make BlocksManager load it from Storage

data_structures/src/builders.rs, data_structures/src/chain.rs, data_structures/src/flatbuffers/protocol_generated.rs, data_structures/src/serializers.rs, data_structures/src/types.rs, data_structures/tests/builders.rs, data_structures/tests/serializers.rs, docs/protocol/network/messages/inventory.md, schemas/protocol.fbs
This PR implements the inv message as part of the Witnet's inventory exchange protocol:
- Add inv message in flatbuffers' schema (including auto-generated code)
- Add inv message as a Witnet data structure
- Add functions to convert inv message to/from flatbuffers' types from/to Witnet's types
- Add function to build an inv message
- Add tests for the serializer and builder functions
This PR is to be merged after #183
=> feat(data-structures): add inv protocol message

core/src/actors/session/handlers.rs
The handling of some protocol messages is only allowed for a certain type of sessions (outbound/inbound).
This PR introduces the check of the session type in the `StreamHandler`of the `Session`. It also fixes this check for the `Peers` message (`Peers` message should only be allowed for outbound sessions).
=> fix(core): add outbound/inbound checks in Session's StreamHandler

data_structures/src/builders.rs, data_structures/src/flatbuffers/protocol_generated.rs, data_structures/src/serializers.rs, data_structures/src/types.rs, data_structures/tests/builders.rs, data_structures/tests/serializers.rs, schemas/protocol.fbs
Implement get_data as a Command in the FlatBuffers schema.
Implement get_data as a native data structure.
Implement get_data and its builder as a WitnetMessage in witnet_data_structures::types::Message
Add tests for the serializer and builder functions.
Close #163
=> feat(data-structures): add get_data protocol message

core/src/actors/mempool_manager/actor.rs, core/src/actors/mempool_manager/mod.rs, core/src/actors/mod.rs, core/src/actors/node.rs, core/src/actors/utxo_manager/actor.rs, core/src/actors/utxo_manager/mod.rs, docs/architecture/managers/mempool-manager.md, docs/architecture/managers/utxo-manager.md, mkdocs.yml, witnet.toml
- We try to use very expressive names for configuration variables.
- Each variable is encumbered with a comment.
- Even though, we should add a header to the `witnet.toml` configuration file, including a link to the documentation page for the same file.
- This lets us keep the comments in the configuration file succinct while providing a way for the users to learn more about each variable and discover example values for them.
=> chore(config): Add link to config-params docs

core/src/actors/session/handlers.rs, core/src/actors/session/messages.rs, docs/architecture/session.md
Add `AnnounceItems` message to `Session` actor. Allows to announce a new inventory item to the outbound peers.
=> feat(core): AnnounceItems actor message

core/src/actors/session/handlers.rs, data_structures/src/chain.rs
This PR adds a basic handler for get_data messages at the `Session`.
Item retrieved from the storage postponed until Issue #159.
Close #179
=> feat(core): add handler for get_data messages in session

core/src/actors/blocks_manager/handlers.rs, core/src/actors/blocks_manager/messages.rs, core/src/actors/blocks_manager/mod.rs
This PR add a `GetBlock` message in the `BlocksManager` to add the functionality to get a block from the `BlocksManager` from its hash.
Required for the demo for the `GetData` handler in the `Session` to retrieve the block from the `BlocksManager`.
=> feat(core): add GetBlockMessage in BlocksManager

core/src/actors/config_manager/actor.rs, core/src/actors/config_manager/messages.rs, core/src/actors/config_manager/mod.rs
Change `ConfigManager` actor to contain an `Arc<Config>` so the handler for the `GetConfig` message returns a reference to the loaded configuration instead of a deep copy.
=> refactor(config manager): Use Arc to share the loaded config

core/src/actors/blocks_manager/handlers.rs, core/src/actors/blocks_manager/messages.rs, core/src/actors/blocks_manager/mod.rs, core/src/actors/session/handlers.rs, data_structures/src/builders.rs, data_structures/src/error.rs, data_structures/tests/builders.rs
This PR adds a message in the `BlocksManager` to discard existing inventory vectors (in memory) from a list of inventory vectors. The handler of this message just calls a library function (tests are also added for it).
When an `Inv` message is received at the `Session`, a message is sent to the `BlocksManager` to discard the inventory vectors that already exist and to send a `GetData` message only with those. This is also added in this PR.
=> feat(core): discard existing inventory vectors in inv handler

core/src/actors/mod.rs, core/src/actors/node.rs, core/src/actors/reputation_manager/actor.rs, core/src/actors/reputation_manager/handlers.rs, core/src/actors/reputation_manager/messages.rs, core/src/actors/reputation_manager/mod.rs, docs/architecture/managers/reputation-manager.md, mkdocs.yml
Add reputation manager actor and a dummy implementation for the `ValidatePoE` (validate proof of eligibility) message that always assumes it's valid.
I've created #235 to keep track of the pending work.
=> feat(actor): Add reputation manager actor

core/src/actors/chain_manager/mod.rs, crypto/Cargo.toml, crypto/src/hash.rs, crypto/src/merkle.rs, crypto/tests/lib.rs, crypto/tests/merkle.rs, data_structures/Cargo.toml, data_structures/src/chain.rs
This allows to import crypto from data_structures, otherwise there would be a cyclic dependency.
=> refactor(crypto): remove data_structures dependency from crypto

core/src/actors/chain_manager/mod.rs, data_structures/src/chain.rs
Add TransactionsPool struct which is a container of Transaction objects providing constant time lookup by transaction-hash and iteration over the transactions sorted by K, where:
```
transaction fee
K = ------------------
transaction weight
```
This pool is used internally by the ChainManager as its mempool.
See the generated docs for the data structure for more examples.
=> feat(data structures): add TransactionsPool struct

core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/messages.rs, core/src/actors/chain_manager/mod.rs, core/src/validations.rs, core/tests/validations.rs, data_structures/src/chain.rs, docs/architecture/managers/chain-manager.md
This PR adds a method to create new blocks with a given proof of eligibility. It gets the maximum number of transactions (currently unimplemented). The block is then validated in the `AddNewBlock` handler, following the same path as external blocks (blocks from the network).
TODOs:
* Add coinbase transaction
* Calculate the total fee of the transactions
* Should there be any helper methods to build Block/BlockHeader/LeadershipProof?
=> feat(core): add BuildBlock message to ChainManager

core/src/actors/chain_manager/actor.rs, core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mod.rs, core/src/actors/mining_manager/actor.rs, core/src/actors/mining_manager/handlers.rs, core/src/actors/mining_manager/mod.rs, storage/Cargo.toml, storage/src/storage.rs
The following works correctly:
* The block with the lowest hash will be chosen when there are 2 candidates
* A new node will ask for the all the blocks that it is missing
* The blocks are correctly mined and sent
* The blocks are successfully stored and retrieved from the `InventoryManager`
Aside from a few minor bugs, the following changes should be discussed:
* replace MessagePack with Json as a temporary workarround for a MessagePack bug
* accept blocks from a past epoch
* add randomness to mining manager to help testing the block candidate logic
=> Fix bugs found while trying mining demo

core/src/actors/chain_manager/actor.rs, core/src/actors/chain_manager/handlers.rs, core/src/actors/epoch_manager/mod.rs, core/tests/actors/epoch_manager.rs, util/src/timestamp.rs
This is a quick fix for making `ChainManager` wait for epoch 0 before bootstrapping the chain.
=> Wait for epoch 0 before trying to bootstrap the chain

p2p/src/peers/mod.rs
=> Filter out 0.0.0.0 "unspecified" address when adding new peer addresses

core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mod.rs
This PR fixes some issues regarding some validations of the block candidate in the ChainManager:
- update `block_candidate` after verifying PoE
- verify epoch for checking if the node already has a better block candidate
=> fix(chain_manager): fix some issues for block candidates

core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/messages.rs, core/src/actors/chain_manager/mod.rs, core/src/actors/json_rpc/connection.rs, core/src/actors/json_rpc/json_rpc_methods.rs, core/src/actors/session/handlers.rs, data_structures/src/chain.rs, docs/architecture/managers/chain-manager.md, docs/interface/json-rpc.md
Closes #280 
Implement the getBlockChain JSON-RPC method.
One major change is that now JSON-RPC requests are handled asynchronously, which looks like it solves #176.
Example request:
{"jsonrpc": "2.0","method": "getBlockChain", "id": 1}
Example response:
{"jsonrpc":"2.0","result":[[0,"ed28899af8c3148a4162736af942bc68c4466da93c5124dabfaa7c582af49e30"],[1,"9c9038cfb31a7050796920f91b17f4a68c7e9a795ee8962916b35d39fc1efefc"]],"id":1}
The hashes are obtained from the `ChainManager`, from the `epoch_to_block_hash` map, which should be stored in the storage as it is used to synchronize two nodes. Right now it is not stored, so the blockchain is lost when all the nodes shutdown. (Alternatively, the map could be rebuilt when the node starts, but it would need to naively read all the blocks from the …
=> getBlockChain

Cargo.toml, docs/interface/cli.md, mkdocs.yml, src/cli.rs, src/json_rpc_client.rs, src/main.rs
Close #281, close #302 
Implement a human friendly command-line interface to query the getBlockChain JSON-RPC method. Usage example:
```text
$ cargo run -- cli getBlockChain
Finished dev [unoptimized + debuginfo] target(s) in 0.17s                                                          
Running `target/debug/witnet cli getBlockChain`
Block for epoch #46924 had digest e706995269bfc4fb5f4ab9082765a1bdb48fc6e58cdf5f95621c9e3f849301ed
Block for epoch #46925 had digest 2dc469691916a862154eb92473278ea8591ace910ec7ecb560797cbb91fdc01e
```
Support --config and -c flag to set the config file, because the JSON-RPC server address is obtained from the config file.
Also implement the raw command: send raw JSON-RPC requests:
```text
$ cat get_block_chain.txt | cargo run -- cli raw …
```
=> witnet cli getBlockChain

core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mod.rs, core/src/actors/storage_keys.rs
Closes #293 
Remarks:
1. I already took the opportunity to rename `epoch_to_block_hash` to `block_chain` (mentioned in #295)
2. Maybe we could refactor the way in which we persist block chain status into storage, as we are storing `chain_info` and `block_chain` separately (i.e. using 2 `Put` messages).
=> feat(chain_manager): persist blocks index into storage

core/src/actors/chain_manager/mod.rs, core/src/actors/session/handlers.rs, core/src/actors/session/messages.rs
Created SendBlock msg and handler in session actor to send a block to another peers
Created broadcast_block function to send a Broadcast(SendBlock) msg to sessions manager
Changed candidate hash validation from < to <=
Added two options in process a new block:
* current epoch: update candidate and broadcast the block
* older epoch: broadcast an annoucement and persist block
=> feat(core): Change AnnounceItem msg to Block msg when a block is mined

core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mod.rs, core/src/utils.rs
Added blocks_to_validate state in ChainManager to keep blocks that we can't validate because we don't have their previous hash.
Added a recursive call to process_block to validate blocks in blocks_to_validate hashmap 
Added a function to update utxo_set with block candidate and with older blocks
Added tests
Close #319
=> feat(core): Update utxo set and validate blocks in order

core/src/actors/chain_manager/data_request.rs, core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mod.rs, data_structures/src/chain.rs, docs/interface/json-rpc.md
Close #340, close #341, close #342
On every epoch, as we start processing the consolidated block,
we will update the state of the DataRequestPool with all the new
transactions, commits, reveals and tallys.
=> Data Request pool and logic

data_structures/src/chain.rs
The Transaction::new factory method takes inputs, outputs and a signing key and returns a Transaction object containing those inputs and outputs and with the appropriate signatures. Since keys and signatures needs to be implemented first in witnet_crypto crate, the method returns dummy signatures.
=> feat(data_structures): add Transaction::new factory method

core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mining.rs, core/src/actors/chain_manager/mod.rs, core/src/validations.rs, data_structures/Cargo.toml, data_structures/src/chain.rs, data_structures/src/lib.rs, data_structures/src/tests.rs
Add several methods to Transaction and Block that ultimately add up to support Block's validate method that so far it only validates the mint transaction. This method probably should grow to validate everything related to the block that currently is spread out through the ChainManager actor handlers.
Things to highlight:
- Merged two different `impl` blocks that existed for `Transaction`
- Removed the `validate_coinbase` function inside `validations.rs` module
- Created a `validate` method inside `Block` that so far it only validates the mint transaction, but my recommendation is that everything related to block validation goes in there
- Implemented the `fee` method for `Transaction`
- Implemented an `inputs_sum` method for `Transaction`
- Implemented an `is_mint` method for …
=> feat(data_structures): add method to validate Block's mint

core/src/actors/chain_manager/data_request.rs, core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mining.rs, core/src/actors/chain_manager/validations.rs, core/src/actors/node.rs, core/src/actors/rad_manager/actor.rs, core/src/actors/rad_manager/handlers.rs, core/src/actors/rad_manager/messages.rs
Created a function in `data_request.rs` to extract a vector of `DataRequestState` available for one `Epoch`
Added a RADRequest field in the `ResolveRA` msg 
Added a mocked `verify_poe_data_request` function
Start `RadManager` in node
Added functionality to send `ResolveRA` msgs to `RadManager` in mining to execute `rad_requests`
Added function to create a commit transaction
Added function to create a reveal transaction and update `DataRequestState`
Broadcast commit transactions
Close #351
Close #356
=>  feat(mining): create commit and reveal transactions in mining

core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mining.rs, core/src/actors/chain_manager/mod.rs, core/src/actors/chain_manager/validations.rs, data_structures/src/chain.rs, data_structures/src/tests.rs
The mint transaction is now validated correctly.
Transaction validation incorrectly used the `TransactionPool` instead of the `UnspentOutputsPool`.
Block consolidation now correctly updates the `TransactionPool`.
In `AddTransaction`, the validations are disabled because they failed to recognize a valid commitment transaction. The only checks enabled are whether the input of the transaction is present in the unspent outputs pool.
=> Fix mint and transactions

core/src/actors/chain_manager/actor.rs, core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/messages.rs, core/src/actors/chain_manager/mod.rs, core/src/actors/inventory_manager/handlers.rs, core/src/actors/session/handlers.rs, core/src/actors/session/messages.rs, core/src/actors/sessions_manager/handlers.rs, core/src/actors/sessions_manager/mod.rs, p2p/src/sessions/mod.rs, p2p/tests/sessions.rs
When requesting blocks with an `InventoryRequest` message, the node was sending the blocks in inverse order causing a bit of trouble. This fix makes the node send the blocks in the requested order.
This PR supersedes #361
=> Fix: send inventory blocks in same order as requested

core/src/actors/chain_manager/actor.rs, core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mining.rs, core/src/actors/chain_manager/mod.rs, core/src/actors/storage_keys.rs, data_structures/src/chain.rs
This PR refactors the `ChainManager` state so that the blocks are not longer required to be on memory in order to validate newer blocks. 
This PR supersedes the PR #367
=> refactor(chain_manager): remove storing blocks in ChainManager state

rad/src/operators/mixed.rs, rad/src/operators/mod.rs, rad/src/types/mixed.rs
Implement the operators `to_float` and `to_map` to the `RadonMixed` type.
=> feat(rad): implement to_float and to_map to RadonMixed

core/src/actors/chain_manager/data_request.rs, core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mining.rs, core/src/actors/chain_manager/validations.rs, core/src/actors/json_rpc/json_rpc_methods.rs, data_structures/src/chain.rs, data_structures/src/serializers/decoders.rs, data_structures/tests/serializers.rs
Example data request:
```json
{"jsonrpc":"2.0","method":"inventory","params":{"transaction":{"version":0,"inputs":[{"ValueTransfer":{"transaction_id":"bf4b7d5f1b4ed859a8de5815ab8b2caa7f788b8e62d181811034003e2b7443f5","output_index":0}}],"outputs":[{"DataRequest":{"pkh":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"data_request":{"not_before":0,"retrieve":[{"kind":"HTTP-GET","url":"https://openweathermap.org/data/2.5/weather?id=2950159&appid=b6907d289e10d714a6e88b30761fae22","script":[0]},{"kind":"HTTP-GET","url":"https://openweathermap.org/data/2.5/weather?id=2950159&appid=b6907d289e10d714a6e88b30761fae22","script":[0]}],"aggregate":{"script":[0]},"consensus":{"script":[0]},"deliver":[{"kind":"HTTP-GET","url":"https://hooks.zapier.com/hooks/catch/3860543/l2awcd/"},{"kind":"HTTP-GET","url":"ht …
```
=> Fix data requests when multiple nodes are mining

core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mod.rs, core/src/actors/codec.rs
Fixed error produced when the maximum message size had been exceeded. This case appears during INVENTORY_ANNOUNCEMENT when too much block hashes announced. 
Added limit of 500 to this kind of message
=> feat(core): limit blocks number sent during sychronization process

core/src/actors/chain_manager/handlers.rs, core/src/actors/chain_manager/mod.rs, core/src/actors/session/handlers.rs, core/src/actors/sessions_manager/mod.rs, data_structures/src/types.rs
Modified Display for Command to add block hash to `Block` message
Divided last_beacon handler in outbound and inbound to send `last_beacon` messages to allow synchronization and reach mine flag enabling
Specified `SYNCED_INTERVAL` to at least 2 epochs to ensure synchronization
Request previous block in case of synced blockchain to do not lose 1 block (no recursive)
Added `candidate_to_validate` to keep the last block candidate to ensure synchronization. It will substitute to `blocks_to_validate`
Added synced flag and modified mine flag enable condition to avoid forks
Added a temporally solution to disable mine flag in case of not have a minimum number of outbounds
=> fix(core): fix lagging 1 block behind the tip

core/src/actors/chain_manager/actor.rs, core/src/actors/session/actor.rs, core/src/actors/session/handlers.rs, core/src/actors/session/mod.rs, core/src/actors/sessions_manager/actor.rs, core/src/actors/sessions_manager/handlers.rs, data_structures/src/builders.rs, data_structures/src/chain.rs, data_structures/src/types.rs, data_structures/tests/builders.rs, data_structures/tests/serializers.rs, p2p/src/sessions/mod.rs, partial_struct/src/lib.rs, schemas/witnet/witnet.proto
Added a magic number (`u16`) for messages built with the 2 first `u8` of the Sha256 of the `ConsensusConstants`
Added protobuff conversion to `ConsensusConstants`
Added a validation of this number in each message received. Closing communication in case of mismatching magic numbers
Close #307
=> feat(core): disable communication between nodes with different consensus constants

wallet/Cargo.toml, wallet/src/key.rs, wallet/src/lib.rs, wallet/src/mnemonic.rs
Example
```rust
use witnet_wallet::mnemonic;
use witnet_wallet::key;
let passphrase = "";
let seed = mnemonic::MnemonicGen::new().generate().seed(passphrase);
let ext_key = key::MasterKeyGen::new(seed).generate();
```
Example
```rust
use witnet_wallet::mnemonic::MnemonicGen;
let mnemonic = MnemonicGen::new().generate();
// A Mnemonic Seed must be protected by a passphrase
let passphrase = "";
// String of mnemonic words
let words = mnemonic.words();
// Seed that can be used to generate a master secret key
let seed = mnemonic.seed(passphrase);
```
Run `cargo doc -p witnet_wallet --no-deps --open` to see the rendered API docs
=> feat(wallet): BIP39 Mnemonic and BIP32 Master Key generation

data_structures/src/chain.rs, data_structures/src/tests.rs, node/src/actors/chain_manager/mining.rs
=> fix(data_structures): block hash should only depend on block header

Cargo.lock, node/src/actors/messages.rs, rad/Cargo.toml, rad/src/error.rs, rad/src/hash_functions/mod.rs, rad/src/hash_functions/sha2.rs, rad/src/lib.rs, rad/src/operators/array.rs, rad/src/operators/map.rs, rad/src/operators/mixed.rs, rad/src/operators/mod.rs, rad/src/operators/string.rs, rad/src/reducers/average.rs, rad/src/reducers/mod.rs, rad/src/script.rs, rad/src/types/array.rs, rad/src/types/float.rs, rad/src/types/map.rs, rad/src/types/mixed.rs, rad/src/types/mod.rs, rad/src/types/string.rs, rad/tests/lib.rs
This kind of biggie refactor tries to exemplify how we are supposed to use the Failure framework properly.
The benefits of this approach are manyfold:
- Error messages are not created in place but defined in the `RadonError` enum, which prevents inconsistent error reporting and keeps the code cleaner.
- Every usage of `RadonResult<T>` is now `Result<T, RadonError>`, where `Result` is Rust's primitive `Result`. 
- The API for each module can now be uniform and predictable.
=> Make witnet-rad module use Failure properly

data_structures/src/chain.rs, node/src/lib.rs, node/src/signature_mngr.rs, node/tests/signature_test.rs, wallet/src/key.rs, wallet/src/signature.rs
The Signature Manager is in charge of storing a secret key and sign data.
The API consists of three functions:
- `start`: Starts the manager with no key
- `set_key`: Sets the key the manager is going to use to sign data
- `sign`: Signs the given data
Example:
```rust
use witnet_node::signature_mngr;
signature_mngr::start();
let key = SK::from_slice(&[1 as u8; 32]).unwrap();
signature_mngr.set_key(key).and_then(|_| {
let data = [0xab; 32];
signature_mngr::sign(&data)
})
//...
```
=> feat(signature_mngr): add signature manager

crypto/src/key.rs, data_structures/src/chain.rs, data_structures/src/proto/mod.rs, data_structures/src/tests.rs, data_structures/tests/builders.rs, data_structures/tests/serializers.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/signature_mngr.rs, schemas/witnet/witnet.proto, validations/src/validations.rs
- Signature manager returns a `KeyedSignature` as the result of signing
- Added the conversion `From<secp256k1::Secp256k1> for Signature`
- Signing of: beacon, reveal, commit and tally, in minging manager
Start signature manager and give it a key in order to be able to sign
Closes #563 #554
=> feat(signatures): sign blocks in mining manager

Justfile, docker/aarch64-unknown-linux-gnu/Dockerfile, docker/arm-unknown-linux-gnueabihf/Dockerfile, docker/armv7-unknown-linux-gnueabihf/Dockerfile, docker/openssl.sh, docs/development.md, docs/get-started/installation/cross-compilation.md, docs/get-started/installation/from-source.md, docs/get-started/installation/gnu-linux.md, mkdocs.yml
This PR adds support for cross compiling `witnet-rust` for most popular ARM targets, specially those used by the different models of the Raspberry Pi micro computer.
close #552
=> Support cross compilation for common ARM targets

Justfile, crypto/src/key.rs, data_structures/src/builders.rs, data_structures/tests/builders.rs, data_structures/tests/proto.rs, data_structures/tests/serializers.rs, p2p/tests/peers.rs, p2p/tests/sessions.rs, partial_struct/src/lib.rs, rad/src/lib.rs, storage/src/backends/rocksdb.rs
I have updated the `clippy` command inside `Justfile` to include `--alll`, and fixed all the errors.
<details><summary>The errors reported by clippy</summary>
<pre>
Checking witnet_util v0.2.0 (/home/anler/src/public/witnet-rust/util)
Checking witnet_crypto v0.2.0 (/home/anler/src/public/witnet-rust/crypto)
warning: long literal lacking separators
--> crypto/src/key.rs:280:29
|
280 |                 ChildNumber(0x8000002c), // purpose: BIP-44
|                             ^^^^^^^^^^ help: consider: `0x8000_002c`
|
= note: #[warn(clippy::unreadable_literal)] on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unreadable_literal
warning: long literal lacking separators
--> crypto/src/key.rs:281:29
|
281 | …
=> refactory(clippy): fix clippy warnings

data_structures/src/chain.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, validations/src/validations.rs
`validate_block` function now returns a *diff* of changes to apply to the utxo set instead of cloning the utxo set before validation. This has two implications:
1. When choosing the candidate: Each block candidate keeps its own diff, when one is chosen as the best candidate, its diff is consolidated into the chain state.
2. When synchronizing the chain: Each block in the batch of 500 blocks is validated, if it's valid, its diff is consolidated into the chain state. After the validation of the entire batch the chain is persisted into the storage. If for some reason one block it's not valid, the entire batch is cancelled and the chain state is restored to the last persisted state.
=> Synchronization without cloning pools

.travis.yml, Justfile
- Speeds up travis builds by improving caching and linking rocksdb dynamically
- Renames `just travis` to `just ci`
- Adds the possibility of passing flags to `just clippy`, `just fmt` and `just node`
Close #583
=> Continuous integration and Justfile overhaul

Cargo.lock, node/Cargo.toml, node/src/storage_mngr.rs
JSON was a temporary solution, and it does not work when maps have non-string keys.
[Bincode](https://github.com/TyOverby/bincode) is a very simple serializer where "the size of the encoded object will be the same or smaller than the size that the object takes up in memory in a running Rust program".
=> feat(storage_mngr): replace json with bincode for serialization

Cargo.lock, data_structures/Cargo.toml, data_structures/src/lib.rs, node/Cargo.toml
Updated old serde dependencies in data_structures and node to solve that if we do a cargo check in witnet-rust/data_strutctures instead of witnet-rust we load the older serde version and fail
=> fix(serde): update serde dependencies in data_structures and node

Cargo.lock, config/src/config.rs, config/src/defaults.rs, data_structures/Cargo.toml, data_structures/src/chain.rs, data_structures/src/data_request.rs, data_structures/tests/reputation.rs, node/Cargo.toml, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mod.rs, node/tests/serialization.rs, reputation/src/ars.rs, reputation/src/trs.rs, schemas/witnet/witnet.proto
This PR integrates the reputation crate with the node.
* Create `ReputationEngine` struct with all the required state, and store it in `ChainState`.
* Create `Reputation` and `Alpha` types, for now just a wrapper around a `u32`.
* On block consolidation, update reputation engine: for every tally, process the revealers and update their reputation.
Close #599 
Close #600
=> Integrate Reputation Engine

Cargo.lock, Cargo.toml, Justfile, config/Cargo.toml, config/src/config.rs, config/src/defaults.rs, crypto/Cargo.toml, data_structures/Cargo.toml, data_structures/src/chain.rs, docs/configuration/environment.md, docs/configuration/toml-file.md, node/Cargo.toml, node/tests/config_test.rs, p2p/Cargo.toml, partial_struct/Cargo.toml, protected/Cargo.toml, rad/Cargo.toml, reputation/Cargo.toml, storage/Cargo.toml, util/Cargo.toml, validations/Cargo.toml, wallet/Cargo.toml, witnet.toml
- updates the IP of the bootstrap node
- upgrade consensus constants and their documentation
- bumps the versions of all the components from `0.2.x` to `0.3.0`
=> Testnet 3 release candidate

Cargo.lock, Cargo.toml, config/Cargo.toml, crypto/Cargo.toml, data_structures/Cargo.toml, node/Cargo.toml, p2p/Cargo.toml, partial_struct/Cargo.toml, protected/Cargo.toml, rad/Cargo.toml, reputation/Cargo.toml, storage/Cargo.toml, util/Cargo.toml, validations/Cargo.toml, wallet/Cargo.toml, witnet.toml
The commit in between (929c1e7923bda50cdddc42d3b8b32c9a38de13c6) is the release candidate for testnet-3.1.
Commit 5fd33bc76749c80329a542975a1a0a6931a33334 is far from trivial, as it changes three different consensus constants:
```patch
-checkpoint_zero_timestamp = 1559347200
+checkpoints_period = 30
+checkpoint_zero_timestamp = 1560643200
+genesis_hash = "00000000000000000000000000000000000000007769746e65742d302e332e31"
```
- The checkpoint zero timestamp has been updated to Jun 16 2019, 12am. 
- The checkpoint period is temporarily reduced to allow faster testing. This will be reverted back when we are closer to mainnet.
- Genesis hash now contains a reference to the testnet version (it's the codification of `witnet-0.3.1`). In future releases we can change this to avoid annoying …
=> Bumps crates versions to 0.3.1 and 0.3.2

wallet/src/actors/app/builder.rs, wallet/src/actors/app/error.rs, wallet/src/actors/app/handlers/get_wallet_infos.rs, wallet/src/actors/app/handlers/mod.rs, wallet/src/actors/app/handlers/stop.rs, wallet/src/actors/app/mod.rs, wallet/src/actors/controller.rs, wallet/src/actors/storage/builder.rs, wallet/src/actors/storage/handlers/create_wallet.rs, wallet/src/actors/storage/handlers/flush.rs, wallet/src/actors/storage/handlers/get_wallet_infos.rs, wallet/src/actors/storage/handlers/mod.rs, wallet/src/actors/storage/mod.rs, wallet/src/lib.rs, wallet/src/storage/mod.rs
1. When shutting down the application with an `INT` signal (`Ctrl-C`), the database is not flushed. Nevertheless, it will be automatically flushed when starting the application again, but this is not desirable since we are forcing users to always start the application just to persist pending changes that couldn't be applied when the application stopped.
2. If we flush the database before shutting down, we receive a `pure virtual method called` in some cases. The error means we must drop the database handle before static destruction kicks in.
The solution here is very simple, when handling the shutdown signal (`impl Handler<Shutdown> for Controller`) we issue a `Stop` message to the App actor, and in turn this one sends a `Flush` message to the Storage actor.
Solution `1` is very simple, …
=> refactor(wallet): implement graceful shutdown of the db

crypto/src/merkle.rs, crypto/tests/merkle.rs, data_structures/src/transaction.rs, data_structures/tests/inclusion_proofs.rs
Close #708 
In order to build a proof of inclusion, we need the entire merkle tree, not just the root. This PR adds a new merkle tree implementation which stores all the intermediate nodes.
Missing: 
* improve documentation
=> Proofs of inclusion for transactions in blocks

wallet/src/actors/app/builder.rs, wallet/src/actors/app/handlers/mod.rs, wallet/src/actors/app/handlers/unlock_wallet.rs, wallet/src/actors/app/handlers/wallet_unlocked.rs, wallet/src/actors/app/mod.rs, wallet/src/actors/storage/error.rs, wallet/src/actors/storage/handlers/mod.rs, wallet/src/actors/storage/handlers/unlock_wallet.rs, wallet/src/actors/storage/handlers/wallet_infos.rs, wallet/src/actors/storage/mod.rs, wallet/src/api/endpoints/unlock_wallet.rs, wallet/src/storage/error.rs, wallet/src/storage/mod.rs, wallet/src/wallet.rs
Implement the *unlockWallet* API endpoint. This enpoint will:
* Use the provided password to derive the key used to encrypt/decrypt the stored password
* Use the key to read the wallet contents and keep it open for the current session
The `seesionId` param is used to associate the unlocked wallet with the given session. After that, every time the client wants to interact with this wallet it will have to specify its `sessionId` as well as the `walletId`.
```json
{
"id": "<request id>",
"params": {
"password": "<wallet password>",
"sessionId": "<session id>",
"walletId": "<wallet id>"
},
"method": "unlockWallet",
"jsonrpc": "2.0"
}
```
If the unlock wallet succeeds it will send an empty ok-response.
```json
{
"id": "1",
"result": { …
```
=> Unlock wallet

data_structures/src/chain.rs, data_structures/src/transaction.rs, data_structures/tests/inclusion_proofs.rs, validations/tests/validations.rs
Co-authored-by: Tomasz Polaczyk <tmpolaczyk@gmail.com>
Close #706 
Close #707 
Close #709 
Close #710 
Modified methods to create the hash of DRTransaction and TallyTransaction:
--> DRTransaction hash = hash( hash(dr_output bytes) + hash(dr_transaction bytes) )
--> TallyTransaction hash = hash( hash( hash(dr_pointer bytes) + hash(tally_result bytes) ) + hash(tally_transaction bytes) )
The idea to use the total transaction bytes instead of only the rest of fields is avoid to implement new types of messages in Protobuff that represents a vector ("repeated") of messages, so the bytes of dr_output, dr_pointer and tally_result are included twice (inside and outside transaction)
The idea to concatenate tally_result and dr_pointer hashes in TallyTransaction hash creation is to have only one …
=> Modify hash method for dr and tally and include them in the PoI

data_structures/src/chain.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs, node/src/actors/session/handlers.rs, reputation/src/ars.rs
- Created last_chain_state in ChainManager to have a backup of the previous state of ChainState field.
- Modified persist_chain_state function to persist last_chain_state instead of chain_state
- Modified GetBlockEpochRange response to returns hashes instead of InventoryEntries to simplify some operations.
- Modified Synchronization protocol, outbound peer include the block of the last epoch consolidated by the inbound to allow it checking fork cases.
- Created peers_beacons_received boolean in ChainManager to handle cases when we dont obtain a consensus message (PeersBeacons) from our outbounds
- Handled fork or out of consensus cases in PeersBeacons, using the initialize_from_storage function and handling the state machine states
Close #682
=> Implement some features to avoid forks

wallet/src/actors/app/handlers/close_session.rs, wallet/src/actors/app/handlers/lock_wallet.rs, wallet/src/actors/app/handlers/mod.rs, wallet/src/actors/app/mod.rs, wallet/src/api/endpoints/close_session.rs, wallet/src/api/endpoints/lock_wallet.rs, wallet/src/api/endpoints/mod.rs, wallet/src/api/endpoints/unlock_wallet.rs, wallet/src/api/error.rs, wallet/src/api/routes.rs, wallet/src/app/error.rs
This PR adds two methods to the Wallet API:
- [`lockWallet`](https://github.com/witnet/witnet-rust/wiki/Lock-Wallet) which locks the specified wallet if it's unlocked, and closes the active session
- [`closeSession`](https://github.com/witnet/witnet-rust/wiki/Close-Session) which closes the active session
- Introduce `Unauthorized` and `Forbidden` API errors. See the [wiki](https://github.com/witnet/witnet-rust/wiki/Wallet-API-Errors) for more information.
=> Lock wallet and Close session methods

crypto/src/mnemonic.rs
This prevents the repo from compiling in Rust 1.36
=> fix: specify AsRef type explicitly

docs/interface/json-rpc.md, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs
Close #725 
Now the `buildVtt` and `buildDrt` methods will return the transaction hash when the transaction is successfully created.
```json
{"jsonrpc":"2.0","method":"buildDataRequest","id":1,"params":{"dro":{"data_request":{"not_before":0,"retrieve":[{"kind":"HTTP-GET","url":"https://api.coindesk.com/v1/bpi/currentprice.json","script":[152, 83, 204, 132, 146, 1, 163, 98, 112, 105, 204, 132, 146, 1, 163, 85, 83, 68, 204, 132, 146, 1, 170, 114, 97, 116, 101, 95, 102, 108, 111, 97, 116, 204, 130]}],"aggregate":{"script":[145,  146,  102,  32]},"consensus":{"script":[145,  146, 102,  32]},"deliver":[{"kind":"HTTP-GET","url":"https://hooks.zapier.com/hooks/catch/3860543/l2awcd/"},{"kind":"HTTP-GET","url":"https://hooks.zapier.com/hooks/catch/3860543/l1awcw/"}]},"value":1002,"witnesses":2,"bac …
```
=> feat(jsonrpc): return transaction hash in buildVtt method

Cargo.lock, node/src/actors/messages.rs, node/src/actors/peers_manager/actor.rs, node/src/actors/peers_manager/handlers.rs, node/src/actors/peers_manager/mod.rs, node/src/actors/session/actor.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/handlers.rs, p2p/Cargo.toml, p2p/src/error.rs, p2p/src/peers/mod.rs, p2p/tests/peers.rs
Modified Peers structure and methods to implement Bitcoin bucketing with 2 buckets (tried and new)
Modified get_random_peer method in Peers that choose a peer randomly from each bucket
Modified Peers tests
Added src_address field in AddPeers message
Created a new method in PeersManager to import peers from a Peers structure
Created a new method in PeersManager, `try_peer`, to check if a peer is good initializing a handshake protocol
Close #732 
Close #737
Close #738
=> feat(p2p): modify Peers to use Bitcoin bucketing

data_structures/src/error.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, validations/src/validations.rs, validations/tests/validations.rs
Close #797
There was a mistake in the validation code which always accepted blocks whose `prev_block_hash` was the `genesis_block_hash`.
=> Prev block hash genesis hash

docs/interface/json-rpc.md, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/transaction_factory.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
Add JSON-RPC and CLI methods to getBalance and getPkh. Usage:
```
witnet node getPkh
witnet node getBalance --pkh=2dbf2cefcf626d661a8cb1797be92624ca1835f7
```
Calling getBalance with no pkh will default to the node pkh.
=> getBalance and getPkh methods

storage/src/backends/crypto.rs
This test sometimes failed because there is a small probability that AES
decrypts to a valid value. Now we check that it decrypts to the same
value as we encrypted. There is also a small probability that this test
will fail, but it should never happen in practice.
=> Fix another non-deterministic test

data_structures/src/error.rs, validations/src/lib.rs, validations/src/tests.rs, validations/src/validations.rs, validations/tests/validations.rs
1. Create new function `validate_data_request_output` which is used by the wallet
2. Add more descriptive errors: `NoReward` (*The fees of the data request is greater that its value*) and `NonUniformReward` (*The reward is not the same for each witness*)
3. Move tests inside the crate since they are unit and not integration tests.
=> Refactor validations crate

wallet/src/actors/worker/methods.rs, wallet/src/db/encrypted/mod.rs, wallet/src/db/mod.rs, wallet/src/db/plain/mod.rs, wallet/src/db/tests.rs, wallet/src/model.rs, wallet/src/repository/keys.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/factories.rs, wallet/src/repository/wallet/tests/mod.rs, wallet/src/types.rs
* Add unit tests for `index_transactions` method
* Uniquely index transactions, that is, if a block is indexed twice its transactions aren't indexed/duplicated anymore in the database
* Add a new method `contains` to `Database` interface
=> Uniquely index transactions

node/src/actors/json_rpc/json_rpc_methods.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
Previously the --limit argument was used to limit the number of blocks, not the number of epochs.
Also changed the default to show the block hashes from the last 50 epochs.
=> fix(cli): epoch limit on blockchain method

.cargo/config
The default number of parallel jobs by default is the # of CPUs. Currently, we have `jobs` restricted to 1
=> chore: remove parallel jobs restriction

rad/src/error.rs, rad/src/operators/array.rs, rad/src/script.rs, rad/src/types/array.rs
Before this PR, RADON subscripts were deserialized as:
// Old
[83, [85, "symbol"], 117]
But we actually want them to be inside one array:
// New
[83, [[85, "symbol"], 117]]
=> fix(rad): subscripts should be inside an array

node/src/actors/messages.rs, node/src/actors/peers_manager/handlers.rs, node/src/actors/peers_manager/mod.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/handlers.rs, node/src/actors/sessions_manager/mod.rs, p2p/src/peers/mod.rs, p2p/src/sessions/mod.rs, p2p/tests/peers.rs, witnet.toml
Reduced bootstrap periods
Create get_outbound_diff method to obtain the number of peers required to conform a consensus group
Modify GetRandom method to GetRandomPeers to obtain a group of random peers
Close #813
=> Improve peering process

Cargo.lock, Cargo.toml, node/src/actors/chain_manager/mining.rs, node/src/actors/messages.rs, node/src/actors/rad_manager/handlers.rs, rad/src/lib.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs, validations/src/validations.rs, wallet/src/actors/worker/methods.rs
With option to try serialized data requests locally:
cargo run -- node send-request --run --hex=0aa0...
Additionally, renamed run_consensus to run_tally for consistency.
=> Add send-request command to node

witnet.toml
This updates the `witnet.toml` configuration file with the addresses of the new bootstrap nodes for the Testnet 5.
=> chore: update bootstrap nodes info

.travis.yml, Cargo.lock, node/Cargo.toml, node/tests/data_request_examples.rs
This ensures that our examples always work.
* Added a test which iterates over the json files in `examples/` and tries to parse them as data requests.
* Added tests which execute the request radon scripts locally, with fake input data, but they have to be added manually.
* To avoid untested data requests, there is a hardcoded list of filenames and if that list does not match the filenames in `examples/`, the test fails.
=> test: parse and run data requests in examples/ folder

node/src/actors/chain_manager/handlers.rs
Otherwise the node can get stuck in Synchronizing state.
=> fix(node): add missing state transition in PeersBeacons handler

data_structures/src/chain.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, validations/src/validations.rs
Add generic `TransactionPool::contains` method.
Changed the return type of `commit_contains` and `reveal_contains` from `bool` to `Result<bool, TransactionError>`, to handle the case where there are two commits with different hash but equal pkh for the same data request. We only accept the first one and ignore the rest as duplicates. Same with reveals.
This fixes an issue where one commit can overwrite another and we enter an infinite loop since the received commit is always considered new.
Move `AddTransaction` logic from handler to its own method in `chain_manager/mod.rs`
And move generic transaction validation function to validations crate.
Add tests for handling commits and reveals with no signatures.
Add tests for handling invalid transaction types.
Close #875
=> Test add transaction

Cargo.lock, config/src/config.rs, config/src/defaults.rs, data_structures/Cargo.toml, node/src/actors/epoch_manager/mod.rs, util/Cargo.toml, util/src/timestamp.rs
=> feat(utils): use NTP timestamps to avoid sync problems

docker/witnet-rust/Dockerfile, docker/witnet-rust/runner.sh
Namely:
- Compatibility with release candidates in the likes of `0.5.1-rc1`
- Mount `/witnet` directory with write permissions for persistence
- Run `witnet node server` instead of `witnet node` by default
=> fix: solve a few issues with current docker images

data_structures/src/types.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/codec.rs, node/src/actors/session/handlers.rs, node/src/actors/session/mod.rs
Messages sent through the network now show the size in bytes.
Transaction messages now show the transaction hash, and last_beacon messages show the received beacon.
And logs are aligned so received and sent messages line up.
Sample:
```
[2019-12-03T14:29:30Z DEBUG witnet_node::actors::session] [>] Sending  LAST_BEACON: #278218: 4051c1e27d11fa91c95d60390af14f01154fd5c94c90d229e96f2c4070e58001 message to session V4(192.168.2.204:51350) (51 bytes)
[2019-12-03T14:29:30Z DEBUG witnet_node::actors::session] [<] Received LAST_BEACON: #278218: 4051c1e27d11fa91c95d60390af14f01154fd5c94c90d229e96f2c4070e58001 message from session V4(192.168.2.204:21337) (51 bytes)
[2019-12-03T14:37:30Z DEBUG witnet_node::actors::session] [>] Sending  REVEAL_TRANSACTION: …
```
=> Improve node logs

data_structures/src/radon_report.rs, rad/src/error.rs, rad/src/lib.rs, rad/src/operators/array.rs, rad/src/operators/mod.rs, rad/src/reducers/average.rs, rad/src/reducers/mod.rs, rad/src/reducers/mode.rs, rad/src/types/array.rs
The following operators are now forbidden from being used during the tally stage:
* All the array operators except `ArrayFilter` and `ArrayReduce`
This does not affect subscripts, only top-level operators, so for example `ArrayGet` can still be used inside an `ArrayFilter`.
Important change: reducers lose the ability to modify the liars vector. If a user wants to punish all the reveals different from the mode, they should use a filter instead.
Another important change: the liars vector is now frozen after the first reduce. This prevents an issue where running filters after a call to reduce resulted in an invalid liars vector. It also makes a lot of sense: we only want to penalize liars based on the values of the input array. Since a reduce consumes the input array, it does not make sense …
=> Forbid dangerous operators in tally stage

data_structures/src/chain.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/inventory_manager/handlers.rs, node/src/actors/inventory_manager/mod.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs, node/src/actors/peers_manager/mod.rs, node/src/actors/session/handlers.rs, node/src/signature_mngr.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
Close #457, close #498
Note: since this changes the format of stored blocks, the storage needs to be erased to avoid errors. Specifically, blocks were stored as `InventoryItem`, but are now stored as simply `Block`.
Works with value transfer and data request transactions even if they are not included in a block
Only works with commits and reveals if they are already included in consolidated blocks (issue #918)
The format of the result of `getTransaction` includes the block hash: `{"blockHash": "...", "transaction": {}}`
There is a JSON-RPC `getTransaction` method and also a CLI `getTransaction` method:
```
$ cargo run -- node getTransaction ea057a62adcee2903aa3e1a78d44f67da0cc7f7946d3eb1402445154c0eae7fb
```
However the CLI method just prints the JSON, it is not using a human friendly …
=> GetTransaction method

Justfile, validations/src/tests.rs
Some tests still show clippy warnings
=> Rust 1 40 (second try)

Cargo.lock, Cargo.toml, config/src/defaults.rs, witnet.toml
This PR prepares everything for Testnet-6. In particular, it updates multiple consensus constants:
- genesis timestamp
- genesis block hash
- reputation expiration alpha diff period
- number of peers needed to start synchronizing (2 → 3)
This is a partial solution for #925, but it's still missing the WBI/BR deployment.
=> chore: set testnet-6 consensus constants

data_structures/src/chain.rs
Close #918.
This will allow `getTransactions` method to work with unconfirmed commits and reveals.
But since commits and reveals are cleared every epoch, we cannot use this method to see commits or reveals that were not accepted into a block.
=>  Implement get (commits, revels) for TransactionsPool

data_structures/src/chain.rs, data_structures/src/lib.rs, data_structures/src/radon_report.rs, data_structures/src/vrf.rs, validations/src/lib.rs
When you forget to add `#[test]` to a test, cargo prints a warning:
This warning (dead_code) was disabled in some places.
This PR fixes that, and fixes the ignored warnings
=> test: enable all warnings in tests

Cargo.lock, data_structures/src/radon_error.rs, data_structures/src/radon_report.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/messages.rs, node/src/actors/rad_manager/handlers.rs, rad/Cargo.toml, rad/src/error.rs, rad/src/filters/mode.rs, rad/src/lib.rs, rad/src/reducers/mode.rs, rad/src/script.rs, rad/src/types/array.rs, rad/src/types/boolean.rs, rad/src/types/bytes.rs, rad/src/types/float.rs, rad/src/types/integer.rs, rad/src/types/map.rs, rad/src/types/mod.rs, rad/src/types/string.rs, validations/src/validations.rs, wallet/src/actors/app/handlers/run_rad_req.rs
Close #939
Close #963 
This implements a bidirectional conversion between `RadonErrors` and `RadError`. This way we avoid duplicating the serialization logic. Basically, all `RadonErrors` must be convertible to `RadError`, and if that `RadError` has any extra arguments, these arguments are encoded into the CBOR array. Detailed explanation:
`RadonError` is the type reported by nodes when a data request has some error. Most `RadonTypes` are encoded as their CBOR equivalent: for example `RadonInteger` is encoded as `Value::Integer` and `RadonString` is `Value::Text`. But there is no `Value::Error`, so the encoding of `RadonError` is a bit different.
A `RadonError` is serialized as a tagged CBOR array with tag id 39:
```rust
CborValue::Tagged(Tag::of(39), Box::new(CborValue::Array(values))) …
```
=> Support interception, serialization and commitment of all `RadonError`s

Cargo.lock, Cargo.toml, witnet.toml
This is the release candidate for Testnet 0.6.1
=> chore: prepare release 0.6.1

witnet.toml
This change in `witnet.toml` slows down recalculation of the clock drift.
This change is not final.
=> fix: slow down ntp client

node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mining.rs
This log is misleading since it is printed on every call to `initialize_from_storage`, and we use that method to roll back one block if something goes wrong.
=> chore: remove "mining enabled" log

node/src/actors/node.rs, node/src/signature_mngr.rs
This PR follows the same approach in the `StorageManager` in order to run the `SignatureManager` on a separate thread.
The known limitation is that the number of threads that the pool can be configured has to be 1, because the way the `SignatureManager` is configured with the `SetKey` message (which requires to request  information to the storage).
=> feat(actors): run signature manager on its own thread

data_structures/src/data_request.rs
We can see a strange error while synchronizing the testnet in commit 8af0f30ce061478a68f8c4d1acfa578033da9d37:
> [2020-01-30T15:02:35Z INFO  witnet_node::actors::chain_manager] Synchronization progress: 17.60% (  4373/ 24843). Latest synced block is 7days 2h 35m old.
[2020-01-30T15:02:35Z INFO  witnet_node::actors::chain_manager] Synchronization progress: 17.61% (  4374/ 24843). Latest synced block is 7days 2h 34m 30s old.
[2020-01-30T15:02:35Z ERROR witnet_data_structures::data_request] Data request b0f36f514e8f9aa1667485d10a6883c6c8781e2b12eb3cfb4243c2c999d830d3 was not present in the data_requests_by_epoch map (epoch #4373)
[2020-01-30T15:02:35Z INFO  witnet_node::actors::chain_manager] Synchronization progress: 17.61% (  4375/ 24843). Latest synced block is 7days 2h 34m old. …
=> fix(data_structures): remove from data_requests_by_epoch only once

docker/cross-compilation/aarch64-unknown-linux-gnu/Dockerfile, docker/cross-compilation/arm-unknown-linux-gnueabihf/Dockerfile, docker/cross-compilation/armv7-unknown-linux-gnueabihf/Dockerfile, docker/cross-compilation/x86_64-unknown-linux-gnu/Dockerfile
This should add some information to backtraces, but I'm not sure how much of an impact does this make.
Binary size before strip: 31 MB
Binary size after strip: 24 MB
=> chore: do not strip release binaries

Cargo.lock, Cargo.toml, witnet.toml
NOTICE: this changes consensus constants, and thus implies hard-forking the network.
Close #998
=> chore: draft release 0.6.2

src/cli/node/json_rpc_client.rs, validations/src/validations.rs
Close #1014 
Sample output:
```
46000.000000000 wits
```
=> Pretty print Wits in getBalance

node/src/actors/chain_manager/handlers.rs
This removes a confusing `warn` log line which used to happen during the first consolidation after synchronizing, because the candidates vector was not cleared.
=> fix(node): clear candidates while synchronizing

node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mod.rs
Sometimes, the node can panic when initializing because the `chain_info` is `None`. That's because one future was incorrectly spawned with `.spawn()` instead of `.wait()`.
Replace that `.spawn()` with a future chain so hopefully we prevent similar problems in the future.
Now the final `.wait(ctx)` blocks the actor until it is properly initialized.
Also, for some reason `cargo fmt` does not work on this file.
=> fix(node): race condition during ChainInfo loading

bridges/ethereum/src/actors/block_relay_and_poi.rs, bridges/ethereum/src/actors/claim_and_post.rs, bridges/ethereum/src/actors/eth_event_stream.rs, bridges/ethereum/src/actors/witnet_block_stream.rs, bridges/ethereum/src/config.rs, bridges/ethereum/src/eth.rs, bridges/ethereum/src/main.rs, witnet_ethereum_bridge.toml
This makes a few breaking changes to the bridge configuration file.
`enable_block_relay` has been separated into two different flags:
```toml
enable_block_relay_new_blocks = true
enable_block_relay_old_blocks = true
```
And now the gas limits can be set in the config file:
```toml
[gas_limits]
claim_data_requests = 500000
post_data_request = 1000000
post_new_block = 200000
report_data_request_inclusion = 200000
report_result = 200000
```
=> misc bridge fixes

Cargo.lock, Cargo.toml, crypto/src/key.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/signature_mngr.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs, util/src/credentials.rs, util/src/lib.rs
Close #1033 
This PR adds the ability to export the private key associated to the identity used by the node. A new `exportPrivateKey` command can be used to print that private key:
```
$ cargo run -- node masterKeyExport
Private key for pkh twit1cpnnz00l0lg84mn6t8wsq855f88nx5rw6tkfkn:
xprv1qru3g4rsugt5edkkhpycn5xnxctdwd3zr6m0re294u6urwvzjcexzqya0njnwklpgs8t8ffu5cx3evlc72n5e7tyfyxmg4aaxjt30ls49c4mrp5y
```
Or write the private key to a file inside the storage dir specified in the config:
```
$ cargo run -- node masterKeyExport --write
Private key written to /home/t/witnet-rust/.witnet-rust-testnet-6/private_key_twit1cqhaxkxatx5uf7kr2qe9772qa2hqdp5705jwx4.txt
```
In the future, the `masterKeyImport` command will be used to restore the identity.
=> Export private key

wallet/src/actors/app/handlers/close_session.rs, wallet/src/actors/app/handlers/create_data_req.rs, wallet/src/actors/app/handlers/create_vtt.rs, wallet/src/actors/app/handlers/create_wallet.rs, wallet/src/actors/app/handlers/generate_address.rs, wallet/src/actors/app/handlers/get.rs, wallet/src/actors/app/handlers/get_addresses.rs, wallet/src/actors/app/handlers/get_balance.rs, wallet/src/actors/app/handlers/get_transactions.rs, wallet/src/actors/app/handlers/lock_wallet.rs, wallet/src/actors/app/handlers/send_transaction.rs, wallet/src/actors/app/handlers/set.rs, wallet/src/actors/app/handlers/subscribe.rs, wallet/src/actors/app/handlers/unlock_wallet.rs, wallet/src/actors/app/handlers/update_wallet.rs, wallet/src/actors/app/methods.rs, wallet/src/actors/app/routes.rs, wallet/src/types.rs
Close #1029 
Add optional field `prefill` to `unlock_wallet`
```
{
"wallet_id": "...",
"password": "...",
"prefill": [1000, 2000, 3000]
}
```
This will generate 3 new addresses and send 1000 nanowits to the first address, 2000 to the second and 3000 to the third.
In case of error (if the node is not synced or it does not have any balance), the addresses are generated but will not receive any wits.
=> Add option to easily send value to a new wallet

config/src/config.rs, node/src/signature_mngr.rs, src/cli/node/with_node.rs
Close #1034 
The idea is to be able to import the master key when starting the node for the first time:
```
$ cargo run -- node run --master-key-import private_key_twit1wpmdccr3rn5zw8wuppu4wsg34ul9yvl6awt2q5.txt 
```
The current implementation requires users to delete the storage in order to import a different master key. This avoids any problems that could arise from people accidentally overwriting their private key and losing their mined wits. Also, it's significantly simpler to implement, as the current code assumes that the node master key never changes in many places.
This is the error that appears in the logs when trying to import a master key without deleting the storage:
```
[2020-03-04T11:47:04Z ERROR witnet_node::signature_mngr] Failed to configure master key: Tried to overwrite …
```
=> Import master key

node/src/signature_mngr.rs
=> fix(node): store master key in storage after import

node/src/actors/chain_manager/handlers.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
Close #1058 
Now by default the `blockchain` CLI method will return the last 50 blocks.
=> Change getBlockChain API to limit based on number of blocks

bridges/ethereum/src/config.rs, config/src/config.rs, config/src/defaults.rs, config/src/loaders/toml.rs, data_structures/src/chain.rs, node/tests/config_test.rs, src/cli/node/json_rpc_client.rs, wallet/src/actors/app/handlers/create_vtt.rs, wallet/src/repository/wallet/mod.rs
Close #1073 
This can break some users configuration files: if they had explicitly set `environment = "testnet-3"`, they will see this error:
```
Error: Error parsing config file: unknown variant `testnet-3`, expected `mainnet` or `testnet` for key `environment` at line 40 column 1
```
But the default configuration file does not have that field, so hopefully this doesn't cause many problems.
This also changes the default storage path from `.witnet-rust-testnet-3` to `.witnet`. So users that have not set any `db_path` in the configuration file will have to manually rename that folder. But since the default configuration file now explicitly sets `db_path = ".witnet"`, this shouldn't be a common problem.
=> fix: rename testnet3 environment to testnet

config/src/config.rs, config/src/defaults.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/json_rpc/server.rs
Close #1050 
Now, users can set `enable_sensitive_methods = false` to disable the following JSON-RPC methods:
```
"createVRF",
"getPkh",
"getPublicKey",
"masterKeyExport",
"sendRequest",
"sendValue",
"sign",
```
Trying to use one of these methods when it has been disabled will result in a custom "unauthorized" error:
```
$ cargo run -- -c witnet_01.toml node getPkh
Finished dev [unoptimized + debuginfo] target(s) in 0.20s
Running `target/debug/witnet -c witnet_01.toml node getPkh`
Loading config from: witnet_01.toml
Setting log level to: ERROR, source: Config
Error: ServerError { code: -32603, message: "Method getPkh not allowed while node setting json_rpc.enable_sensitive_methods is set to false" }
```
The default behavior is the same as before (all methods enabled), this is not a …
=> feat: add option for disabling sensitive JSON-RPC methods

config/src/defaults.rs
block weight to 150K
activity period to 2000 epochs
alpha clock to 20000 witnesses acts  
This PR is related to https://github.com/witnet/research/issues/94
=> feat(config): increase default values of some consensus constants

config/src/config.rs, config/src/defaults.rs, witnet.toml
Using milliseconds gives finer granularity and adapts better to reality, as most APIs should normally return a result or an error under 1 second.
The default is changed to 1/30th of the epoch length, in line with #1099.
The `witnet.toml` config file is also changed so it uses `1000` milliseconds.
=> Make retrieval timeout be expressed in milliseconds

config/src/config.rs, config/src/defaults.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, witnet.toml
This PR introduces a configuration entry, `data_request_max_retrievals_per_epoch`, that enables setting a limit on the number of sources that can be retrieved in a single epoch.
The motivation for this change is reducing the likelihood for a node to be de-synced because of some retrievals draining way too much resources.
Solve #1098
=> Limit the number of retrieved sources per epoch

Cargo.lock, Cargo.toml, witnet.toml
This PR needs to be rebased to #1099, #1101 and #1105 upon their merge.
The used genesis block is https://github.com/witnet/genesis_block/blob/master/testnet_0.7.1_genesis_block.json
Checkpoint zero is intentionally in the future (2020-03-21 00:00:00 UTC).
=> feat(config): set consensus constants for T7.1

data_structures/src/chain.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/chain_manager/transaction_factory.rs, validations/src/tests.rs, validations/src/validations.rs
Close #1110
The coin age can be calculated using the `included_in_block_number` method of `UnspentOutputsPool`. As the name implies, the coin age is measured in the number of blocks, not the number of epochs.
This changes the chain state serialization, so old nodes must delete the storage.
=> Store coin age in UTXO set 

node/src/actors/session/actor.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/beacons.rs, node/src/actors/sessions_manager/handlers.rs, node/src/actors/sessions_manager/mod.rs
Additionally, now a `LastBeacon` message is sent to all inbound peers as soon as they consolidate their connection, which greatly reduces the synchronization delay.
=> feat(node): use all beacons in consensus, not only expected ones

Cargo.lock, Cargo.toml, data_structures/src/chain.rs, node/src/actors/json_rpc/json_rpc_methods.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
Close #898
Implement a new `dataRequestReport` method.
```
witnet-node-dataRequestReport 0.7.3
Show information about a data request
USAGE:
witnet node dataRequestReport [FLAGS] [OPTIONS] <dr-tx-hash>
FLAGS:
-h, --help       Prints help information
--json       Show output in JSON format
--show-dr    Print data request
-V, --version    Prints version information
OPTIONS:
-n, --node <node>    Socket address of the Witnet node to query
ARGS:
<dr-tx-hash>    Data request transaction hash
```
Sample output
```
$ witnet node dataRequestReport 8473a26fbf11656816d7c541928f2d6d3041ade1381c85b27a24808f83d14845
Report for data request 8473a26fbf11656816d7c541928f2d6d3041ade1381c85b27a24808f83d14845:
Deployed in block 0a71ea00a87b2ccfa7a5ca054ab33c228feaf4727fd0b51ca82e470869ecc431 by …
```
=> dataRequestReport

.gitignore
I've followed https://docs.witnet.io/developer/from-source/ and it downloads genesis_block.json but it's not ignored yet by git so it should be helpful to make it ignored to have a clean git status while a build can be done.
Or am I missing something ?
=> feat: ignore genesis block needed for local builds

node/src/actors/chain_manager/handlers.rs, node/src/actors/messages.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/handlers.rs, node/src/actors/sessions_manager/mod.rs
This fixes a bug where the node would move to WaitingConsensus as soon
as one of its peers closed the connection.
Now the SessionsManager will always send the list of beacons to the
ChainManager. If there is consensus after counting the missing peers as
"NO BEACON", the node will start synchronizing even if it's still
missing some peers.
For example, if a node has `outbound_limit = 5` and `consensus_c = 70`, it means that it's waiting for 5 peers, and at least 70% of them must agree (in this case 4 peers out of 5). So before this PR the node would wait for 5 peers, and then calculate the consensus. After this PR, the node calculates the consensus once every epoch, and if at least 4 peers reported the same beacon, it will start synchronizing even if it is still missing some peers. …
=> fix(node): send PeersBeacons even if peers < outbound limit

node/src/actors/chain_manager/handlers.rs, node/src/actors/epoch_manager/mod.rs, node/src/actors/messages.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/handlers.rs
Add some logs to epoch manager, to detect problems with EpochNotifications.
Now when a node notices that it missed an epoch, it will move back to WaitingConsensus state and start synchronizing with its peers. This should prevent nodes from forking in some cases.
=> Epoch notification timestamp check

.gitignore, wallet/src/actors/worker/methods.rs, wallet/src/lib.rs, wallet/src/model.rs, wallet/src/params.rs, wallet/src/repository/keys.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/mod.rs
The wallet was not indexing the genesis block at the initial wallet synchronization, because of the `since_beacon` is pointing to epoch 0 and the sync logic start at `checkpoint + 1`.
The solution was to handle this specific case before the `loop` that iterates synchronization batches.
=> fix(wallet): index genesis block in initial sync

.gitignore, wallet/src/actors/worker/methods.rs, wallet/src/model.rs, wallet/src/repository/keys.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/mod.rs
In this PR:
- Extend address information with a new field called `info`.
- Fix duplicated field contents `pkh` and `address` (currently `pkh` and `address` fields are the same).
These are the data structure returned by the wallet server `get_addresses`:
```rust
#[derive(Debug, Serialize, PartialEq)]
pub struct Address {
pub address: String,
pub index: u32,
pub keychain: u32,
pub account: u32,
pub path: String,
pub info: AddressInfo,
pub pkh: types::PublicKeyHash,
}
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct AddressInfo {
pub label: Option<String>,
pub received_payments: Vec<String>,
pub received_amount: u64,
pub first_payment_date: Option<i64>,
pub last_payment_date: Option<i64>,
}
```
where the `received_payments` is a list of output_pointers of the form …
=> feat(wallet): add address additional information

node/src/actors/connections_manager/mod.rs, node/src/actors/messages.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/handlers.rs, p2p/src/sessions/bounded_sessions.rs, p2p/src/sessions/mod.rs, p2p/tests/sessions.rs
Fix #1056 
It is possible that the node tries to connect twice to the same peer because of a race condition in the code. This can result in some errors when registering and unregistering peers.
This PR will:
* Remove backtraces from some logs
* Move the errors that can happen because of the race condition to debug level
* Fix overflow in `num_missing_outbound`
=> Move session errors to debug

bridges/ethereum/README.md
Update the contract addreses in rinkeby and goerli in the README _how to run a bridge node_.
=> fix: update addresses in How to run a bridge node

Cargo.lock, Cargo.toml, config/src/config.rs, node/src/actors/node.rs, src/cli/mod.rs, witnet.toml
This feature is disabled by default, but currently enabled by the `witnet.toml` configuration file.
Fix #1177
=> feat(node): integrate Sentry for automated bug reporting / telemetry

src/cli/mod.rs
For convenience of the developers.
=> feat: disable telemetry when compiling `debug` target

data_structures/src/builders.rs, data_structures/src/chain.rs, data_structures/src/types.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/chain_manager/superblock.rs, node/src/actors/messages.rs, node/src/actors/session/handlers.rs, node/src/actors/session/mod.rs, schemas/witnet/witnet.proto, validations/src/validations.rs
Close #1233
Close #1236 
This PR has a long list of unresolved questions:
```
message SuperBlockVote {
Hash superblock_hash = 1;
Bn256Signature bn256_signature = 2;
KeyedSignature secp256k1_signature = 3;
fixed32 superblock_index = 4;
}
```
We sign (superblock_index || block_hash) using bn256, and then we sign (superblock_index || block_hash || bls_signature) using secp256k1. The superblock_index is serialized in big endian. The bn256 public key is not needed because it can be obtained using the secp256k1 public key and the `AltKeys` mapping, so it is not included.
The `superblock_hash` field is also technically not needed because we can just try to verify the signature using our local `superblock_hash`, and if it fails it means it's a vote for a different superblock. But it is included …
=> Superblock broadcasting

node/src/actors/node.rs
this is believed to help with #1088
=> fix: ensure that `system.run()` lives inside a Task

node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, validations/src/tests.rs, validations/src/validations.rs
Prior to this PR, the node did not store invalid candidates anywhere. So valid candidates were only validate once, but invalid candidates were validated every time they were received. This PR will validate all received block candidates once (per epoch). So receiving the same candidate twice will only trigger two validations if we receive it in different epochs. Which may make sense because the validity of a candidate depends on the current epoch.
Before this PR, the candidate validation consisted of comparing the block epoch with the current epoch and verifying the VRF hash. This PR adds an additional verification in between, check that the candidate builds on top of our current top of the blockchain. This changes an error that happens during synchronization: `The block has an invalid …
=> Validate candidates once

src/cli/node/with_node.rs, src/cli/wallet/with_wallet.rs
When running the command `cargo run -- node --help` some of the descriptions have a dot and some don't. This PR erases the dots in with_node.rs and with_wallet.rs.
=> Match punctuation in subcommands description

node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/messages.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/handlers.rs, node/src/actors/sessions_manager/mod.rs
The purpose of this PR is to fix a strange issue where the node can get stuck in `Synchronizing` state forever. It is unknown if it actually fixes that issue though, as it is hard to reproduce.
Also, since this removes a check between the current epoch and the block epoch, now all the blocks that are not "expected" are assumed to be candidates and are sent to the ChainManager. Therefore we can see some new warnings:
[2020-05-26T14:53:03Z WARN  witnet_node::actors::chain_manager] Block candidate's epoch differs from current epoch (9989 != 9988)
Update: we believe that are are 3 different issues that can get the node stuck in `Synchronizing`:
* If the node has 0 outbound consolidated peers when sending the `Anycast<LastBeacon>` message, it will be waiting for an `AddBlocks` message that …
=> Fix node stuck on Synchronizing

Cargo.lock, Cargo.toml, node/Cargo.toml, node/src/actors/chain_manager/actor.rs, src/cli/mod.rs
This attaches node addresses to telemetry reports for any errors or panics happening in the node runtime, after the node address has been already loaded into `ChainManager`.
This also allows compiling with no telemetry features at all.
=> Attach node address to telemetry reports

docker/witnet-rust/Dockerfile, docker/witnet-rust/downloader.sh, docker/witnet-rust/executer.sh, docker/witnet-rust/ip_detector.sh, docker/witnet-rust/migrator.sh, docker/witnet-rust/runner.sh, src/cli/mod.rs, src/cli/node/with_node.rs, src/cli/node/without_node.rs, witnet.toml
- divides the `.witnet` folder into `.witnet/config` and `.witnet/storage`
- updates `witnet.toml` so it uses the new folders
- makes the `witnet-rust` Docker image migrate old storage files into the new storage folder
- allows the host to directly modify `witnet.toml` of a existing container
- copies `./witnet` into `/usr/local/bin`, so that `docker exec` commands also work as `docker exec witnet_node witnet node ...`
- makes `masterKeyExport` write to config folder, not storage folder, so that you don't delete our master key backup if a storage wipe is needed
Existing non-Docker setups should keep working, provided that they use a custom `witnet.toml` file that points directly to their storage folder.
=> New folders layout

node/src/actors/chain_manager/mod.rs
Due to we have the getReputation cli method, and currently there are so many nodes. Do you think is needed to keep showing the rep every epoch?
=> log(node): remove periodic reputation logging

data_structures/src/chain.rs, data_structures/src/data_request.rs, data_structures/src/error.rs, data_structures/src/radon_report.rs, data_structures/src/transaction.rs, data_structures/tests/inclusion_proofs.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/rad_manager/handlers.rs, rad/src/lib.rs, schemas/witnet/witnet.proto, src/cli/node/json_rpc_client.rs, validations/src/tests.rs, validations/src/validations.rs, wallet/src/repository/wallet/mod.rs
This PR adds the next logic:
- If you commit a RadonError you can not be slashed
- If you commit a RadonError and you are in consensus, you will earn the wits reward
- If you commit more RadonErrors than normal values (truths) in an epoch, you will not earn reputation.
Close #1261
=> Stop slashing commitments with "forced errors"

Cargo.lock, data_structures/src/radon_error.rs, data_structures/src/radon_report.rs, node/Cargo.toml, node/src/actors/rad_manager/handlers.rs, node/tests/data_request_examples.rs, rad/Cargo.toml, rad/src/error.rs, rad/src/lib.rs, rad/src/operators/array.rs, rad/src/operators/map.rs, rad/src/operators/mod.rs, rad/src/operators/string.rs, rad/src/script.rs, rad/src/types/array.rs, rad/src/types/boolean.rs, rad/src/types/bytes.rs, rad/src/types/float.rs, rad/src/types/integer.rs, rad/src/types/map.rs, rad/src/types/mod.rs, rad/src/types/string.rs, validations/src/validations.rs, wallet/Cargo.toml, wallet/src/actors/app/handlers/run_rad_req.rs, wallet/src/actors/app/methods.rs, wallet/src/actors/worker/handlers/run_rad_request.rs, wallet/src/actors/worker/methods.rs, wallet/src/types.rs, wallet/tests/data_requests.rs
This avoids compilation errors when using `witnet_node` as a dependency or compiling it separately from other crates that already enable the `with-serde` feature:
=> Enable serde by default for crypto and protected subcrates when imported from node

Cargo.lock, data_structures/src/radon_error.rs, data_structures/src/radon_report.rs, node/src/actors/rad_manager/handlers.rs, node/tests/data_request_examples.rs, rad/Cargo.toml, rad/src/error.rs, rad/src/lib.rs, rad/src/operators/array.rs, rad/src/operators/map.rs, rad/src/operators/mod.rs, rad/src/operators/string.rs, rad/src/script.rs, rad/src/types/array.rs, rad/src/types/boolean.rs, rad/src/types/bytes.rs, rad/src/types/float.rs, rad/src/types/integer.rs, rad/src/types/map.rs, rad/src/types/mod.rs, rad/src/types/string.rs, validations/src/validations.rs, wallet/Cargo.toml, wallet/src/actors/app/handlers/run_rad_req.rs, wallet/src/actors/app/methods.rs, wallet/src/actors/worker/handlers/run_rad_request.rs, wallet/src/actors/worker/methods.rs, wallet/src/types.rs, wallet/tests/data_requests.rs
This allows tracing the execution of a RADON script step by step.
Fix #1244
=> feat(rad): make `RadonReport` include `partial_results`

node/src/actors/chain_manager/handlers.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs, src/cli/node/json_rpc_client.rs
Close #1278 
Add synchronization progress to nodeStats command
```
Block mining stats:
- Proposed blocks: 0
- Blocks included in the block chain: 0
Data Request mining stats:
- Times with eligibility to mine a data request: 0
- Proposed commits: 0
- Accepted commits: 0
- Slashed commits: 0
Synchronization progress: 99.99% (186960/186964)
```
```
Block mining stats:
- Proposed blocks: 1
- Blocks included in the block chain: 0
Data Request mining stats:
- Times with eligibility to mine a data request: 0
- Proposed commits: 0
- Accepted commits: 0
- Slashed commits: 0
The node is synchronized and the current epoch is 186966
```
=> Add synchronization progress to nodeStatus command

node/src/actors/chain_manager/handlers.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs
Basic support for #1291 
TODO: rename to `getPendingTransactions`?
=> feat(jsonrpc): implement getMempool method

Justfile
This ignores a lint that checks for many single name variables. Using many single name variables in tests is fine.
=> chore: skip clippy lint in tests

node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs
This is a temporal workaround to reduce the message overhead in testnet 0.9.0c
=> feat(node): disable superblock creation

node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/json_rpc/json_rpc_methods.rs, rad/src/reducers/mode.rs, validations/src/validations.rs
Change some functions in ChainManager to accept references to blocks and transactions, and change other functions that used to clone a reference into accept an owned value, removing the clone in some cases.
Also, replace
x[0].clone()
with
x.into_iter().next().unwrap()
=> refactor: remove some unnecessary clones

config/src/config.rs
From now on, consensus constants shall be only defined at compile time.
=> feat(config): stop reading consensus constants from config file

data_structures/src/chain.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/chain_manager/superblock.rs, schemas/witnet/witnet.proto
This PR:
- Stores the prior to last ARS.
- Stores the prior to last bn256 ARS keys ordered by reputation. In case of tie, identities are ordered by pkh.
- Computes the superblock with the prior to last oordered bn256 ARS keys.
- Checks the validity of a b2n56 key before inserting it to AltKeys.
- Adds the ARS length to the superblock
=> Ars merkelization

node/src/actors/sessions_manager/mod.rs, p2p/src/peers/mod.rs
Bug 1:
The peer selection strategy used before had a high probability of yielding 0 peers when asked for 1. Example: the node has 7 out of 8 peers, only 1 peer is missing:
Before: choose 1 random peer, filter out the already connected ones, connect to all that remain.
Now: choose 8 random peers, filter out the already connected ones, take 1 peer from those.
Bug 2:
When selecting a random peer, it is supposed to be 50% of being from tried bucket and 50% of being from new bucket. There was a bug where they were always selected from tried, and only selected from new if there are not enough tried.
=> Fix p2p small bugs

node/src/actors/messages.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/handlers.rs
Fix #1334 
It turns out this was not only an issue with the feeler, outbound connections had the same problem.
=> fix(node): never add unverified addresses to tried bucket

config/src/config.rs, config/src/defaults.rs, node/src/actors/connections_manager/handlers.rs, node/src/actors/connections_manager/mod.rs, node/src/actors/messages.rs, node/src/actors/peers_manager/handlers.rs, node/src/actors/peers_manager/mod.rs, node/src/actors/sessions_manager/actor.rs, node/src/actors/sessions_manager/handlers.rs, p2p/src/error.rs, p2p/src/peers/mod.rs, p2p/src/sessions/mod.rs, p2p/tests/buckets.rs, p2p/tests/lib.rs, p2p/tests/sessions.rs, witnet.toml
Namely:
- fix(p2p): evict peer addresses from `tried` buckets upon connection failure
- refactor(p2p): improve readability of `remove_from_tried`
- tests(p2p): add tests for new and tried buckets
- refactor(p2p): avoid redundant hashmap lookups
- feat(node): refuse creating multiple inbound sessions for similar IP ranges
=> Several fixes to p2p / bucketing

node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs, node/src/actors/peers_manager/actor.rs, node/src/actors/peers_manager/mod.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/handlers.rs, p2p/src/peers/mod.rs, p2p/tests/peers.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
Implement addPeers JSON-RPC and CLI methods
CLI usage:
```
$ witnet node addPeers 52.166.178.145:21337 52.166.178.145:22337
Loading config from: witnet.toml
Setting log level to: DEBUG, source: Config
[2020-06-25T11:31:18Z DEBUG witnet_data_structures] Set environment to testnet
[2020-06-25T11:31:18Z INFO  witnet::cli::node::json_rpc_client] Connecting to JSON-RPC server at 127.0.0.1:21338
Successfully added peers: ["52.166.178.145:21337", "52.166.178.145:22337"]
```
If the command is called without any arguments, it will read the peers from standard input, so you can paste peer lists found online [like this one](https://gist.github.com/harsh-98/607c2f4ad94d7fdc95c0badb2731b36c)
The addPeers JSON-RPC method is considered "sensitive", so it will not work on public nodes. This is to prevent …
=> feat(jsonrpc): implement addPeers method

data_structures/src/chain.rs, data_structures/src/lib.rs, data_structures/src/superblock.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs
This PR adds the functionality of building the superblock state while synchronizing to a new tip. This prevents a freshly synchronized node to forward a vote that it is not supposed to forward
=> feat(chain manager): update superblock while synchronizing

node/src/actors/chain_manager/handlers.rs
This PR:
- Goes to almost synced state if while synched we lost consensus on our peers.
- While in almost synced state, if drops only peers whose beacons are different from ours.
Close #1351 
Close #1349
=> Almost synched if no consensus

data_structures/src/builders.rs, data_structures/src/types.rs, data_structures/tests/builders.rs, data_structures/tests/serializers.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/messages.rs, node/src/actors/session/actor.rs, node/src/actors/session/handlers.rs, node/src/actors/session/mod.rs, node/src/actors/sessions_manager/handlers.rs, node/src/actors/sessions_manager/mod.rs, schemas/witnet/witnet.proto
Close #1348
BREAKING CHANGE
This PR adds a `LastBeacon` field to the `Version` message. This field is used in the handshake to ensure that a node never connects to outbound peers whose beacon is behind its own, or whose beacon has a different block hash. This is also used by the feeler process to ensure that the peers that are added to tried are in consensus with the node.
=> Check beacon during handshake

rad/src/types/mod.rs, wallet/tests/data_requests.rs
Fix #1302 
For some strange reason, the wallet fails to serialize `i128` values. It's strange because there is a test where that works, but the same code fails if executed in the wallet. Since the only `i128` we use seems to be the one from `RadonInteger`, as a workaround we can simply serialize it as a string.
This serialization is only used by sheikah to display the result of a data request, so let's make sure this doesn't break that.
Before:
{"RadonInteger":42}
Now:
{"RadonInteger":"42"}
=> fix(rad): serialize RadonIntegers as strings

data_structures/src/builders.rs, data_structures/src/superblock.rs, data_structures/src/types.rs, data_structures/tests/builders.rs, data_structures/tests/serializers.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/messages.rs, node/src/actors/session/handlers.rs, schemas/witnet/witnet.proto
This PR adds the superblock beacon to the lastbeacon message. In particular:
- Adds a new 'highest_superblock_checkpoint' to LastBeacon structure.
- If there exists some superblock state, adds the superblock checkpoint to the lastbeacon message.
- Else, signals the genesis hash and the 0 index.
The latter point should be modified when a decision is taken about how to bootstrap the network with an appropriate state #1367.
Currently upon reception of the superblock checkpoint the node does nothing. Once the consensus has been decided, we should implement how to handle that superblock state #1366.
=> feat(session manager): Signal superblock beacon

node/src/actors/peers_manager/handlers.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/handlers.rs, p2p/src/peers/mod.rs, p2p/tests/buckets.rs
This PR adds methods to remove addresses from the ice bucket, and removes those addresses added manually thtough addPeers method
=> feat (p2p): melt addresses inserted through addPeers

data_structures/src/chain.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/tests/serialization.rs
This PR modifies where the last superblock beacon is taken from to the chain info structure. The superblock hash is copied from the superblock state to chain info when a new superblock will be constructed
=> Send consolidated last superblock beacon

wallet/README.md
This PR just updates the README file from the wallet module.
Once merged, we could also remove the old Wallet Wiki GitHub section as it has been moved (and improved) to a [section](https://docs.witnet.io/developer/wallet-api/) in the Witnet documentation website.
This PR should close #1201 and #1202
=> docs(wallet): update README

data_structures/src/data_request.rs, data_structures/src/radon_report.rs, rad/src/lib.rs
This enables clients like Sheikah to get all the available details for tracing execution of scripts and subscripts.
=> Include entire ReportContext in RadonReport

config/src/config.rs, config/src/defaults.rs, data_structures/src/chain.rs, data_structures/src/superblock.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mod.rs, node/tests/serialization.rs, schemas/witnet/witnet.proto, validations/src/tests.rs
This PR creates the method `update_superblock_signing_committee` that returns the subset of the ARS in charge of signing a specific superblock. In particular:
- Orders the ARS with the method `get_rep_ordered_pkh_list` and stores it in the `chain_state.last_ars`
- Adds the size of the superblock signing committee in the consensus constants, and sets it to 100 as default. 
- Creates the function `update_superblock_signing_committee`, this function is called when building the superblock using the previous superblock_hash.
- Adds previous_ordered_ars_identities and current_ordered_ars_identities in the superblockState
Close #1395 
Close #1391 
Close #1393
=> Superblock signing committee

data_structures/src/chain.rs, data_structures/src/superblock.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs
This PR creates superblocks even when no blocks have been proposed during a superblock period.
It also stores the last ARS instead of the prior to last ARS
Closes #1415
=> feat(superblocks): create superblocks even if there are no blocks during superepoch

node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs
This PR provides functionality for split_blocks_batch function which splits a block batch in:
- Blocks needed to construct a consolidated superblock
- Blocks needed to potentially construct an intermediate superblock
=> Split blocks at batch function

data_structures/src/superblock.rs, data_structures/src/types.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/messages.rs, node/src/actors/session/handlers.rs, node/src/actors/sessions_manager/beacons.rs, node/src/actors/sessions_manager/mod.rs, node/src/utils.rs
This PR supersedes the WIP PR #1420 with code from @tmpolaczyk and @girazoki .
In summary it replaces the previous consensus algorithm with a new one based on superblocks and ARS committee votes:
- updates the last beacon structure with additional superblock information in `SessionsManager`.
- implements new synchronization logic in `ChainManager`.
This PR has been tested under the following conditions:
1. Initial sync of 2 nodes that are in the initial signing committee: they reached Synced state and start voting superblocks as expected.
2. Additional node synchronization to an already bootstrapped chain.
3. Revert the chain if not sufficient superblock votes are broadcasted.
4. Recovering a initial sync node after a failure (storage was not removed).
5. Having a small activity period, …
=> feat: implement new consensus based on superblocks

node/src/actors/session/handlers.rs
This PR partially mitigates a DoS attack in which a malicious user sends a huge amount of messages to the node by dropping the TCP socket.
=> fix(session): close TCP socket if error msg

config/src/defaults.rs, node/src/actors/epoch_manager/mod.rs, util/src/timestamp.rs, witnet.toml
This reenables NTP, adds a ±5s variance on its polling period and prints drift with milliseconds.
Fix #1193 
Fix #1189
=> Reenable and improve NTP support

config/src/config.rs, config/src/defaults.rs, data_structures/src/chain.rs, data_structures/src/superblock.rs, node/src/actors/chain_manager/mod.rs, node/tests/serialization.rs, schemas/witnet/witnet.proto, validations/src/tests.rs
This PR adds functionality for reducing the superblock voting committee size if sufficient epochs elpase without consolidated superblock. The period after which the comittee gets reduced is configurable through consensus constants.
This PR aims at solving the problem of loss of availability of a percetange of the ARS members. 2 approaches were discussed to achieve this:
- Reduce the 2/3 votes required to consolidate a block
- Reduce the committee size, thus increasing the probability of achieving 2/3 of the votes.
The first clearly recovers the chain faster, but also in my view decreases the security of the system by breaking the 2/3 vote assumption. The latter spends more time recovering the chain (ideally, for each committee reduction, several iterations would need to be tried before a …
=> Reduced committee size

node/src/actors/json_rpc/json_rpc_methods.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
This PR adds a new command to the node CLI called `claim` a node identity.
This command will be used in order to prove the ownership of a node identity by signing a given data (e.g. an identifier) with the node master key. The output will also contain the signed data, the public key and the signature itself.
```bash
USAGE:
witnet node claim [FLAGS] [OPTIONS] --identifier <identifier>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
--write      Write the signed claimed data to "storage_path/claim-<id>-<public_key>.txt"
OPTIONS:
-i, --identifier <identifier>    Identifier to be claimed by the node (e.g. Witnet ID)
-n, --node <node>                Socket address of the Witnet node to query
--write-to <write-to>        Change the path to write …
```
=> feat(cli): add claim command to node CLI

data_structures/src/chain.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/chain_manager/transaction_factory.rs, src/cli/node/json_rpc_client.rs
This pull request solves #1258. I took the liberty to add some extra categories (and rephrase others) for ease of use. I also formatted the output as a table similar to the output of `getUtxoInfo --long`. 
The categories I added are "Utxos smaller than collateral minimum", which I think is useful to indicate if you should do joinTransactions (previously you'd have to calculate that yourself). I also added "Utxos bigger than and not ready for collateral" for completeness.
If some of these changes are unwanted, I can obviously change them.
PS: I don't know why the formatting check requires me to put the utxos_table columns names on one line (comparing line 155 to 160 and line 215), but I did it anyway.
=> feat(jsonrpc): Add sum of the utxo amounts to getUtxoInfo and format it as a table

Cargo.lock, Cargo.toml, config/src/defaults.rs
Just bumping the `witnet-rust` version to 0.9.2 and setting the bootstrap timestamp to Wednesday, 19-Aug-2020, 09:00 UTC (`1_597_827_600`).
=> chore(cargo): bump version to 0.9.2

data_structures/src/error.rs, validations/src/tests.rs, validations/src/validations.rs
This PR adds two checks in the function `validate_rad_request`:
- If the data request has an empty retrieve vector it returns the error `UnsupportedReducerInAT`.
- If the data request has an empty url source is returns the error `NoRetrievalSource`.
The tests have been changed since the data request used as example was not longer valid.
Closes #1288
=> Request with zero retrieval source set as invalid

node/src/actors/chain_manager/mod.rs
This PR adds a function to get the members of the ARS with reputation greater than 1.
This is used when constructing the superblock so that the superblock signing committee is a subset of the reputed nodes of the ARS.
Close #1455
=> Reputed members of the ARS

node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs
Centralizes all state machine changes in ChainManager so debugging is easier and every transition gets logged in a predictable format.
=> refactor(node): centralize state machine changes in ChainManager

p2p/src/peers/mod.rs
The bug was caused by skipping serialization of one field, but not skipping deserialization. Now the deserializer will always use a safe default (60 secs) which will later be overwritten in runtime with whatever value is set in the configuration.
Fix #1422
=> fix(node): allow deserializing peers data structure from storage

wallet/src/actors/app/error.rs, wallet/src/actors/app/handlers/shutdown.rs, wallet/src/actors/app/methods.rs
Now `shutdown` can be called without specifying a `session_id` for shutting down the wallet, only if there are not any open session.
=> feat(wallet): allow shutdown if no open sessions

data_structures/src/chain.rs, data_structures/src/superblock.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs
Fix #1439
Followup to #1471 
This PR adds a new data structure `chain_state_snapshot` to replace the old `previous_chain_state`. The functionality is the same, but the `chain_state_snapshot` also stores the superblock index of the previous chain state, and the superblock index of the last chain state that has been persisted to the storage.
This will prevent accidentally persisting the same chain state twice, or skipping a superblock in some edge cases. The node will panic if it:
* Stores in memory two different copies of the chain state for the same superblock index. This means that one of the copies is wrong.
* Tries to persist the chain state for superblock N, when there is no copy of the chain state for superblock N (because we forgot to call `self.move_chain_state_forward`)
* Tries to …
=> Improve chain_state persist logs and add panics

config/src/config.rs, config/src/defaults.rs, data_structures/Cargo.toml, data_structures/examples/transactions_pool_overhead.rs, data_structures/src/chain.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mod.rs
Close #1495 
This PR adds a size limit to the `TransactionsPool`. The default is around 192M.
With this limit, when adding new transaction to a full `TransactionsPool`, the transactions with the smaller `fee / weight` ratio will be removed. Note that the limit only applies to value transfer and data request transactions. It does not apply to commits and reveals because they are implicitly limited by the number of data requests.
This limit can be configured in `witnet.toml`, as `mining.transactions_pool_total_weight_limit`. The units are "weight units" as described in https://github.com/witnet/WIPs/pull/32
Estimated overhead: total memory usage of a typical `TransactionsPool` with `transactions_pool_total_weight_limit = 192M`
* With only value transfer transactions with (1, 2, or 3) inputs …
=> Limit mempool size

data_structures/src/chain.rs, node/src/actors/chain_manager/actor.rs
This is a temporary workaround. See #1513 for the discussion
=> fix: clear TransactionsPool on reorganizations

src/cli/node/json_rpc_client.rs
Small fix in the `reputation --all` message
Closes #1521
=> fix: message reputation cli method

bridges/ethereum/src/actors/block_relay_and_poi.rs, bridges/ethereum/src/actors/claim_and_post.rs, bridges/ethereum/src/actors/tally_finder.rs, bridges/ethereum/src/actors/witnet_block_stream.rs, bridges/ethereum/src/actors/wrb_requests_periodic_sync.rs, bridges/ethereum/src/main.rs
This removes code like 
```rust
let wrb_contract2 = wrb_contract.clone();
let wrb_contract3 = wrb_contract.clone();
let wrb_contract5 = wrb_contract.clone();
let wrb_contract6 = wrb_contract.clone();
let wrb_contract7 = wrb_contract.clone();
```
=> refactor(bridge): remove repeated clone variables

node/src/actors/chain_manager/handlers.rs
This is a workaround to #1532.
That issue is still not solved because stopping the node while synchronizing does not store the chain state.
Explanation: the `Session` actor implicitly use an empty `AddBlocks` message to indicate an error. For example, when a peer disconnects while the node is receiving blocks from them, the `Session` actor will send an empty add blocks.
Before this PR, the `ChainManager` would restore the chain state to the last consolidated state, which is epoch 0 in nodes that are synchronizing the first time. This would make the synchronization process restart, and as the number of blocks increases synchronizing a new node would become impossible. After this PR, the `ChainManager` will simply request a new blocks batch from another peer when a peer fails to send the …
=> fix(node): do not restore chain state when processing empty AddBlocks

node/src/actors/chain_manager/mod.rs, node/src/actors/inventory_manager/handlers.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs
Close #1548 
Add JSON-RPC method `getSuperblock` that given a `superblock_index` returns the superblock, and the list of block hashes that pertain to that superblock. But only if the superblock has already seen a majority of votes and is consolidated. Also works when given a `block_epoch` instead of a `superblock_index`: will convert the block epoch to superblock index.
Note that nodes will only store superblocks when they are consolidated, so a new node that synchronizes to the testnet will not store the superblocks that were created when the node was offline.
You can test this method using:
```
echo '{"jsonrpc":"2.0","id":"1","method":"getSuperblock","params":{"superblock_index":0}}' | cargo run -- -c witnet.toml node raw
```
=> Store superblocks in storage

node/src/actors/chain_manager/handlers.rs
Reorder the inputs of the error message `"Received unexpected block {} for superblock index (consolidated: {}, current {}). Delaying synchronization until next epoch."`
=> Reorder inputs of error message

Cargo.lock, Cargo.toml, data_structures/Cargo.toml, rad/Cargo.toml
The main change here is a custom dependency on a forked version of `cbor-codec` that uses a shim for the `ldexpf` system function when on Windows (as such function does not exist on MSVC's own `libc` / `libm`).
- Rust (`x86_64-pc-windows-msvc` toolchain)
- LLVM
- Microsoft Visual C++ Distributable Package
- `vcpkg`
- `openssl:x64-windows-static` (installed through `vcpkg`)
```console
OPENSSL_STATIC=1 OPENSSL_DIR="C:\Program Files\vcpkg\installed\x64-windows-static" cargo build --release
```
=> feat: support x86_64-pc-windows-msvc target

data_structures/src/superblock.rs, node/src/actors/chain_manager/mod.rs
Fix #1573
Also, improved the "Add vote" log line, now it looks like:
```
[2020-09-21T13:04:10Z DEBUG witnet_data_structures::superblock] Add vote: ValidWithSameHash SUPERBLOCK_VOTE twit1fulan0j78dmdfa3gx0779kszj5sc5j35feljv5 #3463: ce1ff0a6b34a1fb0587bebae84a4440240500f08cb1581fce0b1e71b09cc85d7
```
=> fix(node): wait 1 epoch before sending superblock vote

node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs
This PR solves the issue observed during synchronization that generated substraction overflows. This happened because the node tried to create a consolidate and candidate superblocks that it already had built before but then lost synchronization because of lack of consensus on the beacons sent by its peers. While constructing the target superblock again after having constructed the candidate, the substaction between these two checkpoints yields negative.
This PR adds functionality to check whether we need to construct the target AND CANDIDATE blocks while syncronizing
Closes #1526
=> fix(chain manager): avoid overflows while selecting committee

config/src/defaults.rs
Wednesday, 23-Sept-2020, 09:00 UTC
=> chore: update T9.3-b checkpoint zero timestamp

Cargo.lock, bridges/ethereum/Cargo.toml, bridges/ethereum/src/actors/block_relay_and_poi.rs, bridges/ethereum/src/actors/claim_and_post.rs, bridges/ethereum/src/actors/mod.rs, bridges/ethereum/src/actors/tally_finder.rs, bridges/ethereum/src/actors/witnet_block_stream.rs, bridges/ethereum/src/config.rs, bridges/ethereum/src/eth.rs, bridges/ethereum/src/main.rs, witnet_ethereum_bridge.toml
This PR utilizes the superblocks subscription from branch  #1488 
It also adds support for storing superblocks and adds a method for retreving a superblock for a given epoch
It modifies the bridge to make it able to send superblocks to the block relay
Supersedes #1530
Close #1498
=> Send superblocks to block relay

storage/src/backends/crypto.rs
This only affects the wallet, and we never tried to delete anything there, so this issue shouldn't have affected us
=> fix(storage): fix delete operation on encrypted backend

node/src/actors/chain_manager/handlers.rs, src/cli/node/json_rpc_client.rs
Change the method reputation so that when adding the flag `--all` shows the identities active with their reputation and eligibility and those identities that are not active but have 0 reputation, in this case the eligibility is not printed.
This way the sum of the elegibilities is 100%.
For example in a case with 3 identitities active with reputation, the command shows
But if we stop one of the nodes so that is not longer active, the command prints
Closes #1514
=> CLI(reputation): --all shows correct eligibility percentage

config/src/config.rs, config/src/defaults.rs, node/src/actors/session/handlers.rs
Close #1279
Built on top of #1577 
Adds a configurable limit to the received blocks batch size, used when synchronizing.
```
[connections]
requested_blocks_batch_limit = 50
```
Note that values higher than 500 will work as 500, because there is a hardcoded limit to the sent blocks batch size:
```rust
/// Maximum blocks number to be sent during synchronization process
pub const MAX_BLOCKS_SYNC: usize = 500;
```
Also, setting `requested_blocks_batch_limit = 1` will result in an infinite loop and the node not syncing, because of #1580 
Setting `requested_blocks_batch_limit = 2` does also not work because the node stops requesting new blocks after reaching the target superblock.
So setting values smaller than 2 times the superblock period (2 * 10 in the current testnet) are silently set to …
=> Add config parameter to limit the number of blocks downloaded when synchronizing

data_structures/src/chain.rs, data_structures/src/data_request.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs
Replaced DataRequestReport with DataRequestInfo everywhere since the latter is basically an encompassing struct containing all data used by DataRequestReport. Clippy, FMT and all tests (cargo test --all --verbose) pass or are ignored. Let me know any comments you have.
This PR tackles issue #792.
=> refactor: remove DataRequestReport in favor of DataRequestInfo

node/src/actors/chain_manager/mod.rs
This PR (should) solve(s) issue #1005.
I split logging format string for COMMIT and REVEAL (taking the appropriate current round) on the one hand and TALLY on the other hand. Issue #1005 hints to use `extra_commit_rounds`, but that parameter does not exist anymore, so instead I took the `extra_rounds` parameter from the DataRequestPool struct.
I wanted to test whether the logging actually prints the correct messages, but I have not minted any blocks yet, so I am too poor to launch data requests and no one else is launching any either.
=> feat(log): show current commit stage and current reveal stage

rad/src/operators/string.rs
Implemented ignoring a line break when parsing float / int or bool tackling issue #1145 
I chose to truncate the string with one character if necessary rather than "blindly" replacing newlines because that is more strict. Even though I cannot think of anything exploiting replacing all newlines, I'd say stricter is always better.
Even though the issue only mentions integer parsing, the same goes for floats and bools, so I also added the code there. I guess I could abstract the truncating code to a separate function but since there are only three occurences, that would be pretty much the same overhead in terms of lines of code. Would you still prefer putting it into a separate function (e.g., for maintainability)?
=> feat(witnet_rad): ignore line breaks at the end of a float, int or bool when parsing from string

wallet/src/actors/app/handlers/create_vtt.rs, wallet/src/actors/app/handlers/get_balance.rs, wallet/src/actors/app/handlers/unlock_wallet.rs, wallet/src/actors/app/methods.rs, wallet/src/actors/worker/handlers/get_balance.rs, wallet/src/actors/worker/methods.rs, wallet/src/model.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/state.rs, wallet/src/repository/wallet/tests/factories.rs, wallet/src/repository/wallet/tests/mod.rs, wallet/src/types.rs
This PR implements different balances (unconfirmed, confirmed and pending) and fixes some problems of creating transactions (avoids using time-locked UTXOs).
Closes #1481 
Closes #1602
=> feat(wallet): add balances and add time_lock support in create VTTs

Cargo.lock, crypto/Cargo.toml
This PR updates some witnet_crypto dependencies to solve issue #1290.
I'm learning Rust dependency management on-the-go, so let me know if this flow of actions is incorrect (and if so reject the PR):
1. Update package versions in crypto/Cargo.toml
2. Run `cargo update -p aes` and `cargo update -p block-modes` to update Cargo.lock
3. Commit all changes
=> chore: Update aes and block-modes dependencies in witnet_crypto

wallet/src/actors/app/handlers/create_vtt.rs
Currently the wallet was showing wrong transaction fee metadata because it was multiplying the given `fee` by the bytes length of the transaction. However, nodes are weighting transactions differently depending on the number of inputs and outputs.
This problem should be fixed in #1635.
This PR fixes the wrong fee metadata by just passing the absolute value of the `fee` defined by the user to compute the value transfer components (e.g. UTXOs to be used). The wallet will send back the corrected absolute fee.
=> fix(wallet): remove wrong and unused fee computation

node/src/actors/peers_manager/actor.rs
Skip importing peers from storage if timestamp is earlier than Tuesday, October 20, 2020 11:00:00 AM UTC
This should be removed in #1646
=> fix(peers_manager): avoid temporarily import peers

config/src/config.rs, src/cli/wallet/with_wallet.rs, wallet/src/lib.rs, witnet.toml
Close #1632 
Allow setting multiple node urls in witnet.toml:
```
node_url = ["52.166.178.145:21338", "52.166.178.145:21339"]
node_url = "52.166.178.145:21338"
```
When there is more than one node_url, it will choose one at random.
Using the command line only allows one node url and overrides the config.
=> Wallet load balancing

node/src/actors/chain_manager/handlers.rs
This fixes a criticial issue in the node where sometimes the best block candidate can be consolidated twice, causing the node to fork and never recover.
The issue is as follows:
* Blocks 48 and 49 are consolidated by the node in synced state
* Block 50 is received as a candidate, but the network enters a high load state and the node cannot keep up
* The node goes to WaitingConsensus and starts synchronizing
* Blocks 51 and 52 are consolidated by the node when synchronizing
* Block 50 is consolidated as a candidate again, when the last block is 51, resulting in a corrupted state
Therefore, the chain is 48 -> 49 -> 50 -> 51 -> 50 and the node enters an inconsistent state and can never recover.
=> fix(node): clear best_candidate on every epoch

Cargo.lock, wallet/src/actors/app/error.rs, wallet/src/actors/app/handlers/create_wallet.rs, wallet/src/actors/app/handlers/validate_mnemonics.rs, wallet/src/actors/app/methods.rs, wallet/src/actors/worker/error.rs, wallet/src/actors/worker/handlers/check_wallet_seed.rs, wallet/src/actors/worker/handlers/create_wallet.rs, wallet/src/actors/worker/handlers/mod.rs, wallet/src/actors/worker/methods.rs, wallet/src/repository/wallets/mod.rs
This PR:
- allow re-create wallet with same seed phrase using the flag `overwrite` in `create_wallet`
- return `wallet_id` in `validate_mnemonics`
Closes  #1639 (previous PR)
Closes #1673 
Closes #1631
=> feat(wallet): allow re-create wallet with same seed phrase

node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs, wallet/src/actors/worker/methods.rs, wallet/src/lib.rs, wallet/src/params.rs, wallet/src/repository/wallet/mod.rs
This allows to know if a block has been consolidated by a majority of the superblock committee.
The implementation checks that the block epoch is below the last confirmed block according to the superblock beacon, and that the block hash exists at the expected position in the block chain.
This method is used in the wallet synchronization.
Close #1437
=> feat(jsonrpc): add "confirmed" field to getBlock method

config/src/config.rs, config/src/defaults.rs, data_structures/src/chain.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mod.rs, witnet.toml
This is a proposal to limit spamming the network with free VTT's (like we saw today). It could also be extended to DR's, but I did not include that yet because I'm not sure that is something we ultimately want.
This PR would allow a node operator to set a minimum transaction fee he wants to receive before including a VTT into a block whenever he's eligible. I would set this to 1 nanoWIT (though I did not set that as default), but obviously everyone can choose a setting.
Let me know what you think about this and if this unexpectedly breaks something. For example, I am not sure if this would let the VTT pool grow unlimited in the case of spam (I thought there was some sort of periodic cleanup).
=> feat(mining): allow miners to set a minimum required fee for including a VTT in a block

wallet/src/actors/app/handlers/create_wallet.rs, wallet/src/actors/app/handlers/unlock_wallet.rs, wallet/src/actors/app/handlers/update_wallet.rs, wallet/src/actors/app/methods.rs, wallet/src/actors/worker/handlers/create_wallet.rs, wallet/src/actors/worker/handlers/update_wallet.rs, wallet/src/actors/worker/handlers/update_wallet_info.rs, wallet/src/actors/worker/methods.rs, wallet/src/model.rs, wallet/src/repository/keys.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/state.rs, wallet/src/repository/wallet/tests/factories.rs, wallet/src/repository/wallet/tests/mod.rs, wallet/src/repository/wallets/mod.rs, wallet/src/repository/wallets/tests/mod.rs, wallet/src/types.rs
This PR modfies how wallet infos is retrieved. The caption field is renamed to description, and wallet_infos only returns the name. The description is only stored in the private encrypted section of the wallet DB.
=> Update wallet infos

wallet/src/actors/worker/error.rs, wallet/src/actors/worker/methods.rs, wallet/src/repository/error.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/state.rs, wallet/src/types.rs
This PR fixes 2 things:
- Sync wrapper to clear state if synchronization fails
- Ignore `handle_superblock` if wallet is syncing
=> fix(wallet): ignore handle superblock if syncing

wallet/src/actors/worker/methods.rs, wallet/src/constants.rs, wallet/src/db/encrypted/mod.rs, wallet/src/db/encrypted/write_batch.rs, wallet/src/db/mod.rs, wallet/src/db/plain/mod.rs, wallet/src/db/plain/write_batch.rs, wallet/src/db/tests.rs, wallet/src/model.rs, wallet/src/repository/keys.rs, wallet/src/repository/mod.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/factories.rs, wallet/src/repository/wallet/tests/mod.rs, wallet/src/repository/wallets/mod.rs, wallet/src/repository/wallets/tests/mod.rs
This PR adds types to the keys used in the wallet database.
This way one does not need to specify the type when using `db.get()`, and also it's impossible to deserialize a value as a wrong type. All the keys and types should be compatible with the ones in master, but we should double check that this does not break anything.
=> refactor(wallet): use type safe database api

data_structures/src/transaction.rs, node/src/actors/json_rpc/json_rpc_methods.rs
Added transaction size in bytes to the getTransaction method as that allows me to calculate fee per byte and generate transaction pool fee plots in the explorer.
=> feat(jsonrpc): Add transaction size in bytes to getTransaction method

node/src/actors/json_rpc/json_rpc_methods.rs, wallet/src/actors/worker/methods.rs
This speeds up synchronization times by 10x.
=> feat(JSON-RPC): make transaction hashes optional in get_block

wallet/src/actors/app/error.rs, wallet/src/actors/app/handlers/create_vtt.rs, wallet/src/actors/app/methods.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/mod.rs, wallet/src/types.rs
This PR allows creating VTT with multiple outputs (address, value, time_lock).
=> feat(wallet): support multiple outputs in create_vtt

config/src/config.rs, data_structures/src/chain.rs, data_structures/src/transaction_factory.rs, p2p/src/peers/mod.rs, rad/src/reducers/mode.rs, validations/src/validations.rs, wallet/src/actors/app/handlers/get_addresses.rs, wallet/src/actors/app/handlers/get_transactions.rs, wallet/src/actors/app/state.rs, wallet/src/repository/wallet/mod.rs
This time this is the only new lint:
https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations
=> chore: fix clippy warnings for rust 1.48

data_structures/src/chain.rs, net/src/client/tcp/actors/jsonrpc.rs, node/src/actors/json_rpc/json_rpc_methods.rs, src/cli/node/json_rpc_client.rs, wallet/src/actors/app/methods.rs, wallet/src/actors/app/mod.rs, wallet/src/actors/app/state.rs, wallet/src/actors/worker/handlers/notify_status.rs, wallet/src/actors/worker/methods.rs, wallet/src/types.rs
Add the function `periodic_node_request` that sends a `syncStatus` request, if returns an error (meaning the node is disconnected) it sends an event.
Closes #1705
=> [Wallet]: Add periodic node request to know if node disconnected

node/src/actors/json_rpc/json_rpc_methods.rs, wallet/src/actors/app/methods.rs, wallet/src/actors/app/mod.rs, wallet/src/actors/app/state.rs, wallet/src/actors/worker/methods.rs
This PR removes the wallet status subscription and sends the node status changed from the periodic request. 
Since the periodic request is returning the node status, the wallet can know when the node status has changed and send the NodeStatusRequest.
=> [Wallet]: send note status notification from the periodic request

Cargo.lock, bridges/ethereum/Cargo.toml, net/Cargo.toml, wallet/Cargo.toml
Fix #1707 
The issue was that the jsonrpc client library was leaking sockets. I fixed this in https://github.com/witnet/async-jsonrpc-client/tree/fix-tcp-leak but note that this changes the way the jsonrpc client works, so we should make sure this does not break anything.
Also, added a cooldown to the reconnect method, because otherwise the wallet enters in a sort of infinite loop. But the "too many open files" error should be fixed, even without the cooldown.
=> fix(net): add cooldown to jsonrpc client reconnect

wallet/src/repository/wallet/mod.rs
To avoid deadlock.
Close #1761
The issue was:
Thread 1 takes read lock here:
https://github.com/witnet/witnet-rust/blob/5a58020df717b843d61ba87af3a308d13f13e284/wallet/src/repository/wallet/mod.rs#L449
Thread 2 takes write lock (anywhere). This blocks because the lock is held by thread 1.
Thread 1 takes read lock again inside `get_address`. This blocks because the thread 2 has priority.
The fix is to avoid the second read lock, which is redundant.
=> fix(wallet): avoid recursive read lock

bridges/ethereum/src/actors/block_relay_and_poi.rs, bridges/ethereum/src/actors/block_relay_check.rs, bridges/ethereum/src/actors/claim_and_post.rs, bridges/ethereum/src/actors/wrb_requests_periodic_sync.rs, bridges/ethereum/src/config.rs, bridges/ethereum/src/eth.rs, bridges/ethereum/src/main.rs, witnet_ethereum_bridge.toml
This PR changes the code so as to only send superblocks to the block relay that contain DRs that were sent from Ethereum. It also changes the oneshot channel to use the one provided by futures due to an error after rust 1.48.0
=> Send only superblocks containing drs from ethereum

node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs
Before to stop it:
After clean storage and restarting again:
=> fix(node): fix updating node stats during synchronization

wallet/src/actors/app/error.rs, wallet/src/actors/app/methods.rs, wallet/src/actors/worker/error.rs, wallet/src/actors/worker/methods.rs
This PR solves the issue about getting a timeout while receiving blocks, as this might trigger an inconsistent state in the wallet. The solution provided sets the node state to 'None' when we receive a timeout, so as to trigger a new sync when the periodic ping pong request detects is online again
Closes #1750
=> feat(error): return timeout event if timeout error

node/src/actors/chain_manager/actor.rs
This error can happen while developing: we can accidentally break compatibility of some data structure. Prior to this PR, the chain state was replaced with a new chain state and there was no way to recover the old chain state. Now, the node panics so we can detect this error.
This was not a panic before because we wanted to make the transition from one testnet to the next as smooth as possible.
=> fix(node): panic on deserialization error instead of overwriting chain state

.github/workflows/push.yml, Justfile, bridges/ethereum/src/eth.rs, crypto/src/key.rs, data_structures/src/chain.rs, net/src/client/tcp/actors/jsonrpc.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/inventory_manager/handlers.rs, p2p/src/sessions/mod.rs, rad/src/filters/deviation.rs, rad/src/filters/mode.rs, rad/src/lib.rs, rad/src/operators/array.rs, reputation/src/trs.rs, validations/src/tests.rs, validations/src/validations.rs
Run `cargo +nightly clippy --all` and fix all the warnings. The Rust 1.49 update is scheduled for December 31st, but this PR can be merged now.
These are the new lints fixed by this PR:
https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_match
https://rust-lang.github.io/rust-clippy/master/index.html#comparison_to_empty
https://rust-lang.github.io/rust-clippy/master/index.html#field_reassign_with_default
https://rust-lang.github.io/rust-clippy/master/index.html#manual_range_contains
https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro
https://rust-lang.github.io/rust-clippy/master/index.html#result_unit_err
https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
https://rust-lang.github.io/rust-clippy/master/index.html#unne …
=> chore: fix clippy warnings for rust 1.49

node/tests/data_request_examples.rs, rad/src/reducers/mode.rs, rad/src/types/mod.rs
Co-authored-by: Tomasz Polaczyk <tmpolaczyk@gmail.com>
=> fix(radon): remove unwrap in CBOR encode hash function to avoid panics

data_structures/src/transaction_factory.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/messages.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
The cli command `balance` now shows the balance that has been confirmed (tx included in the superblock) and the balance that has not been confirmed yet.
It includes tests for get_total_balance
Closes #1814
=> feat(node): Show unconfirmed balance

node/src/actors/inventory_manager/handlers.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs
Close #1828 
Just like the `getBlock` method, now the result of `getTransaction` includes a "confirmed" field. This field is set to `true` if the block that includes this transaction has been confirmed by a superblock, and `false` otherwise.
=> feat(jsonrpc): add confirmed flag to getTransaction method

data_structures/src/chain.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs
This implements the fix described in https://github.com/witnet/witnet-rust/issues/1827#issuecomment-762849747
=> fix(node): do not clear all reveals on new consolidated block

wallet/src/actors/worker/handlers/handle_block.rs, wallet/src/actors/worker/handlers/sync.rs, wallet/src/actors/worker/methods.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/mod.rs
Closes #1818
- Removes `resynchronization` flag
- Reuses a `needs_indexing` flag in `handle_block` function (single entry point for sync, resync and new block from node)
- Updates tests
=> fix(wallet): fix show transactions after resync

rad/src/operators/string.rs
Before this PR, a data request that tries to parse `"[true]"` using `StringParseJSONArray` will return an empty RadonArray. That's because booleans are mapped to null because of a missing conversion. This PR fixes this by adding that missing conversion.
Since there is no RadonNull type, all null fields are silently ignored when parsing arrays and maps using `StringParseJSON`. Added a few tests to document this behavior.
=> fix(rad): fix deserialization of nested JSON booleans

config/src/defaults.rs
this PR changes the `bucketing_ice_period_duration` to 4 hours
=> fix(config): change ice period to 4 h

node/src/actors/sessions_manager/handlers.rs
This bug happened in the rebase of PR #1867 on top of #1865, because two new handlers ended with the same line.
=> fix(node): drop all peers after changing peers limit

node/src/actors/chain_manager/mod.rs
Allow to change the minimum superblock committee size, because the current minimum of 1 can lead to forks.
The new minimum and the activation date of this feature need to be discussed.
Close #1872
=> feat(node): change minimum superblock committee size

data_structures/src/superblock.rs, node/src/actors/chain_manager/mod.rs
There are 2 main changes:
1. Selection of the first member:
- Old: We take the first byte of the superblock index hash, and the first byte of the superblock hash and we add them (It is not a uniform distribution)
- New: We use those 2 bytes in the next function, byte_a * K + byte_b, where K = 256
2. Selection of the rest members:
- Old: the size of ARS is divided by the size of the committee to obtain the steps between the elements, to achieve a distributed committee. (The problem here, is that there are only a few possible committee combinations, in case of 2000 identities and a committee of 100, only there will be 20 possibles committees)
- New: we use the same logic but adding a random offset to every element, this randomness comes from the bytes of the superblock index hash
Close …
=> feat(superblock): improve randomness in committee selection

.github/workflows/push.yml, Justfile, data_structures/src/data_request.rs, data_structures/src/radon_report.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/messages.rs, node/src/actors/rad_manager/handlers.rs, validations/src/tests.rs, validations/src/validations.rs
Data requests have a `min_consensus_percentage` field that is used to ensure that the result of the data request has a minimum quality.
For example, a data request will 100 witnesses and `min_consensus_percentage = 75` needs 75 valid reveals. Valid means that they are not RadonError, and they all have the same type. The problem comes in the next step: after running the tally script some reveals can be marked as "liars" if they deviate too much from the consensus, according to the filter scripts. So for example using a mode filter with 75 values out of which 73 are all different and 2 are equal, the result would be a value that has only been reported by 2 witnesses out of 100, and the remaining 98 witnesses will be penalized.
This PR changes the validation logic to ensure that the …
=> feat: respect min_consensus in data requests

Cargo.lock
For some reason the bot that creates new issues when there is a security problem with our dependencies doesn't always work. So this PR is me running `cargo audit`, and then `cargo update` on the relevant dependencies.
Before this PR: 8 vulnerabilities and 9 warnings. After this PR: 1 vulnerability and 3 warnings. The remaining warnings already have open issues: https://github.com/witnet/witnet-rust/issues?q=is%3Aissue+is%3Aopen+RUSTSEC
<details>
<summary>List of fixed issues</summary>
```sh
cargo audit > cargo-audit-before
cargo audit > cargo-audit-after
git diff --no-prefix --no-index -U100000 cargo-audit-before cargo-audit-after
```
The lines in red are vulnerabilities fixed by this PR:
```diff
diff --git cargo-audit-before cargo-audit-after
index e55e8b5..7c23c93 100644
--- …
```
=> Update dependencies to fix cargo audit warnings

bridges/centralized-ethereum/src/actors/dr_sender.rs, bridges/centralized-ethereum/src/actors/dr_sender/tests.rs, bridges/centralized-ethereum/src/config.rs, witnet_centralized_ethereum_bridge.toml
Close #1904
Add a limit to the total value of a data request: this is the total cost of creating the data request, including all the fees. The bridge node will treat any data requests with a higher value as errors, and report a generic error to solidity.
=> feat(bridge): add value limit to avoid relaying expensive DRs

Cargo.lock, bridges/ethereum/src/eth.rs, data_structures/Cargo.toml, data_structures/src/chain.rs, partial_struct/src/lib.rs, storage/src/backends/crypto.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/factories.rs
I had to update the `protobuf` crate to get rid of a new error, and updating it may be dangerous if there is some weird serialization format change because we use protobuf to calculate the hashes of blocks and transactions, so any change would have changed the hash. So I have run a full resync on a mainnet node to ensure that nothing breaks.
=> chore: fix clippy warnings for rust 1.52

data_structures/src/data_request.rs, node/src/actors/chain_manager/mod.rs, validations/src/tests.rs
Fix #1796 
Remove `epoch_constants` parameter from `process_data_request` function.
As mentioned in that issue, in theory the `data_requests_by_epoch` field can be also removed, but that would require database migrations. So let's ignore that for now.
=> refactor: remove unused field from process_data_request

data_structures/src/chain.rs, data_structures/src/data_request.rs, data_structures/src/mainnet_validations.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/inventory_manager/handlers.rs, node/src/actors/messages.rs, node/src/actors/rad_manager/handlers.rs, validations/src/tests.rs, validations/src/validations.rs
This pull request is a refactor of the validations code to use a new `ActiveWips` struct when checking if some validation logic is enabled or not. Currently this only replaces the `after_first_hard_fork` and `after_second_hard_fork` functions, but the idea is to extend it when the Threshold Activation of Protocol Improvements (TAPI) is implemented.
=> feat: create struct to store active WIPs

data_structures/src/mainnet_validations.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs
Example usage:
```
echo '{"jsonrpc":"2.0","id":"1","method":"signalingInfo","params":null}' | cargo run -- -c witnet_01.toml node raw
```
Example output:
```json
{
"jsonrpc": "2.0",
"result": {
"active_upgrades": {
"WIP0008": 192000,
"WIP0009-0011-0012": 376320
},
"epoch": 501453,
"pending_upgrades": [
{
"bit": 14,
"end": 4294967295,
"init": 1096423,
"period": 100,
"votes": 0,
"wip": "WIPXXX1"
}
]
},
"id": "1"
}
```
=> feat: implement signalingInfo JSON-RPC method

data_structures/src/chain.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/storage_mngr.rs, node/src/storage_mngr/node_migrations.rs
Warning: this PR changes the format of the ChainState, so make a backup of your storage before testing.
This mechanism allows to add extra fields to the `ChainState` struct. It does not allow to remove or modify existing fields, and it does not work with other types, only with `ChainState`. The idea is to exploit a property of `bincode`, that the fields of a struct are serialized as the concatenation of the serialization of every individual field. Therefore, we can read the old serialized chain state, append some extra bytes (the serialization of the new fields), and deserialize the result as the new version of `ChainState`.
There were many options to detect the version of `ChainState` that is stored in the database:
* Try to read as the new version, in case of error try to read as older …
=> Allow to add new fields to ChainState without breaking the storage

data_structures/src/serialization_helpers.rs, data_structures/src/transaction_factory.rs, data_structures/src/utxo_pool.rs, data_structures/tests/serialization_helpers.rs, node/src/actors/chain_manager/handlers.rs, src/cli/node/json_rpc_client.rs, wallet/src/actors/app/handlers/create_vtt.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/mod.rs, wallet/src/types.rs
Allow to use an UTXO selection strategy that only takes UTXOs from the specified address.
Close #1940
In the wallet JSON-RPC API: add optional utxo_strategy field to `create_vtt` method. This allows to choose the address of the inputs of the transaction, but it also allows to use different UTXO selection strategies such as "bigger first" or "smaller first", aside from the default "random".
In the node JSON-RPC API: since the node only has one address this field can only be used as a fail-safe: if the node address is the one in the "from" field then the transaction will be created, and if the node address is not the one in the "from" field then the transaction will return an error "InsufficientBalance".
Example call (node):
```json
{
"jsonrpc": "2.0",
"method": "sendValue",
"params": { …
```
=> feat: allow to select from address when creating VTT transactions

.github/workflows/push.yml, Justfile, node/src/actors/epoch_manager/mod.rs
Sometimes the Epoch Manager wakes up twice in the same epoch, leading to logic bugs in other components. This commit fixes that by scheduling the Epoch Manager to wait until the next epoch.
=> fix(node): improve stability of EpochManager

config/src/defaults.rs
Given the exceptional nature of the current situation, these temporary values are enforced through compiled logic, not configuration.
=> feat: temporarily use shorter icing periods

node/src/actors/session/handlers.rs
This makes a node tolerate peers that have the same top superblock, even if they are on different blocks, assuming that they will eventually get on the same page at some point after failed superblock consensus.
=> feat: temporarily allow microforked peering

.github/workflows/push.yml
To prevent #1946 from happening again
=> chore: make CI fail when there are unstaged files

data_structures/src/superblock.rs
In some rare occasions, we can see logs like this:
```
[2021-05-31T13:00:00Z DEBUG witnet_data_structures::superblock] Superblock votes (99 in total):
a2c00dedb1f9f6fc41529112d6995b664e937c64ffc17c6364f1beab21ce0bae: 0 votes: []
e61aed6cd040c2ab2d09f0dc033394043a76824771f15e431456a4556f9767c7: 11 votes: ["wit1agc...
a43e0a1bedea3390d49eb93720be90f587c0b39f562f1dbd7d92fdb9ef18bee1: 88 votes: ["wit1ay3...
[2021-05-31T13:00:00Z DEBUG witnet_data_structures::superblock] Signing committee of size 100: ["wit1kn7...
```
Notice how the first line says "0 votes", which does not make sense. This happens when one identity votes more than once: the first vote was for superblock a2c00dedb1f9f6fc41529112d6995b664e937c64ffc17c6364f1beab21ce0bae, and the second vote was for superblock …
=> fix(data_structures): remove misleading "0 votes:" log

data_structures/src/transaction_factory.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
Fetching confirmed and pending balance is terribly slow for executing in an automated fashion (e.g. as part of a block explorer or a simple wallet app). I added a flag to the balance RPC call to fall back to the simple balance counter instead of the confirmed / pending balance.
=> Added a flag to fetch simple balance vs confirmed / pending balance

config/src/config.rs, data_structures/src/chain.rs, data_structures/src/data_request.rs, data_structures/src/superblock.rs, data_structures/src/transaction_factory.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/sessions_manager/beacons.rs, partial_struct/tests/partial_struct_derive.rs, reputation/src/ars.rs, reputation/src/trs.rs, src/cli/node/json_rpc_client.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/mod.rs
The new version will be released tomorrow (2021-06-17), but you can try the pre-release using
RUSTUP_DIST_SERVER=https://dev-static.rust-lang.org rustup update stable
=> chore: fix clippy warnings for rust 1.53

node/src/actors/chain_manager/mining.rs
This is broken since the tapi branch merge (#1985), I originally included the fix in #1976 but that's not merged yet.
=> fix(mining): use correct reppoe_threshold version

config/src/config.rs, config/src/loaders/toml.rs
Previously, setting
[tapi]
oppose_wip0016 = true
Would result in this error:
```
Loading config from: witnet.toml
Error: Error parsing config file: missing field `oppose_wip0014` for key `tapi` at line 68 column 1
```
=> fix(config): set missing fields of tapi struct to false

Cargo.lock, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, validations/Cargo.toml, validations/src/tests.rs, validations/src/validations.rs
Implement https://github.com/witnet/WIPs/pull/58
This branch is based on the tapi2 branch, however the automated WIP activation is not handled in this PR (`active_wips.wip0016()` will always return false).
Close #1960
=> Remove threshold factor from reppoe

node/src/actors/chain_manager/mod.rs
This only affects nodes when synchronizing. For example my node had 2055 votes but only 346 were unique.
=> Fix: small issues in add_temp_superblock_votes

config/src/config.rs, config/src/defaults.rs, wallet/src/actors/app/error.rs, wallet/src/lib.rs, wallet/src/params.rs, wallet/src/repository/error.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/state.rs, wallet/src/repository/wallet/tests/factories.rs, wallet/src/repository/wallet/tests/mod.rs
Close #1832 
Keep track of the transactions that modify the utxo set but are not confirmed yet, so that we can ignore unconfirmed utxo when selecting utxos for a new transaction.
This feature is disabled by default, can be enabled by setting
wallet.use_unconfirmed_utxos = false
in witnet.toml
=> feat(wallet): allow to avoid using unconfirmed UTXOs in transactions

Cargo.lock, Cargo.toml, toolkit/Cargo.toml, toolkit/src/cli/arguments.rs, toolkit/src/cli/commands.rs, toolkit/src/cli/data_requests.rs, toolkit/src/cli/mod.rs, toolkit/src/errors.rs, toolkit/src/lib/data_requests.rs, toolkit/src/lib/mod.rs, toolkit/src/main.rs
Provides convenient and simple to use methods for building any kind of Witnet related tools, either as libraries, FFIs or CLIs.
This crate can fundamentally be used in two different ways: as a CLI tool or as a Rust library.
When compiling this crate, the target binary is a CLI that can be used either standalone or wrapped as a FFI for performing Witnet related operations in programming languages different than Rust.
The `lib` module contains helper functions that can be easily imported into other Rust projects in order to create Witnet related software using Rust.
=> feat: kickstart development of `witnet_toolkit` crate

storage/src/backends/rocksdb.rs
Old error:
```
Error when writing blocks to storage: RocksDB error
```
New error:
```
Error when writing blocks to storage: RocksDB error: IO error: No space left on deviceWhile appending to file: .witnet/000009.log: No space left on device
```
=> feat: improve rocksdb error message

Cargo.lock, Cargo.toml, data_structures/src/chain.rs, data_structures/src/data_request.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/json_rpc/json_rpc_methods.rs, node/src/actors/messages.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs, validations/src/validations.rs
Supersedes #2029 
Close #1989
Output:
```
[2021-08-17T14:21:37Z INFO  witnet::cli::node::json_rpc_client] Connecting to JSON-RPC server at 127.0.0.1:21338
[2021-08-17T14:21:37Z INFO  witnet::cli::node::json_rpc_client] SupplyInfo { epoch: 589868, current_time: 1629210097, blocks_minted: 540691, blocks_minted_reward: 135172750000000000, blocks_missing: 49176, blocks_missing_reward: 12294000000000000, in_flight_requests: 5, locked_wits_by_requests: 2350200003401, current_unlocked_supply: 730394955285531143, current_locked_supply: 154775444522133176, maximum_supply: 2499999999962167720 }
Supply info at 2021-08-17 14:21:37 UTC (epoch 589868):
Supply type                         |    Total WITs 
-------------------------------------+---------------
Temporarily locked in data requests | …
```
=> Total supply cli +

node/src/actors/chain_manager/mod.rs, node/tests/data_request_examples.rs
This ensures that invalid RADON scripts are detected by the `run_locally` function. Otherwise it could be possible to have an invalid data request that seems valid when being run locally, but it is invalid when a node tries to include it into a block.
=> fix: validate RADON before running request

node/src/actors/chain_manager/mod.rs
This removes an unneeded call to `.collect()`, because `try_join_all` does already collect the result into a `Vec` internally, so it is not needed.
=> feat(node): avoid unused temporary allocation when counting TAPI votes

toolkit/src/cli/data_requests.rs
Latest changes in `witnet-requests-js` library uses a different syntax for compiling data requests into solidity code.
This PR updates the regex to capture the new generated solidity code.
=> feat(toolkit): update regex to latest changes in `witnet-requests-js` library

rad/src/types/bytes.rs, rad/tests/lib.rs
This will make requests with a `RadonBytes` result easier to read. Example:
Old:
```
[Data Request] Created Tally for Data Request 9feecfedb08de9331c4ab77988f64dfcad577b6f1270bd4f34837c461f5d61cc with result: RadonTypes::RadonBytes([215, 221, 147, 143, 94, 162, 174, 35, 120, 149, 245, 251, 115, 98, 76, 121, 186, 85, 159, 5, 18, 66, 54, 96, 59, 112, 108, 209, 162, 3, 228, 179])
Reveals:
* RadonTypes::RadonBytes([46, 103, 247, 196, 69, 212, 133, 224, 234, 170, 33, 24, 39, 252, 138, 59, 81, 122, 196, 85, 128, 29, 214, 211, 170, 126, 26, 146, 146, 24, 222, 7])
* RadonTypes::RadonBytes([223, 65, 54, 40, 144, 222, 207, 183, 8, 90, 133, 107, 180, 12, 217, 231, 177, 59, 155, 24, 152, 218, 212, 150, 133, 65, 16, 198, 74, 124, 63, 5])
```
New:
```
[Data Request] Created Tally for Data Request …
```
=> feat(rad): print RadonBytes using hex notation

src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
This PR implements a new CLI command: `searchRequests`. This can be used to find all the data requests that have the same bytecode. One common use case is to check the status of price feed contracts, or any periodic request.
Example: get all the requests from the CFX/USDT price feed starting from epoch 670000. The `--start` parameter is very important because the default behavior is to search all the blocks since the genesis, which may take a while.
```
$ witnet node searchRequests --start 670000 --hex-dr-bytes 0adf0308dce89889061254123a68747470733a2f2f6170692e62696e616e63652e636f6d2f6170692f76332f7469636b65722f70726963653f73796d626f6c3d434658555344541a168418778218646570726963658218571a000f4240185b1257123668747470733a2f2f7777772e6f6b65782e636f6d2f6170692f696e6465782f76332f4346582d5553442f6 …
```
=> feat(cli): searchRequests command

Cargo.lock
Partially fix, but not close, issue #2118
=> chore: update tokio from 1.12 to 1.14

Cargo.lock, rad/Cargo.toml, rad/src/lib.rs
Update version of surf, the http client used to resolve data requests.
Last time this was attempted some sources broke. See #1812
Fix #1820
=> chore: update surf version

Cargo.lock, crypto/Cargo.toml, crypto/src/signature.rs, data_structures/Cargo.toml, data_structures/src/chain.rs, data_structures/src/vrf.rs, node/Cargo.toml, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, validations/src/tests/mod.rs, wallet/src/repository/error.rs
And use re-exported version from witnet_crypto in other crates.
Also remove `SignatureError` which was not used anywhere, preferring `secp256k1::Error` instead.
=> chore: update secp256k1 dependency

rad/src/operators/string.rs
i16::unsigned_abs() instead of i16::wrapping_abs()
=> refactor(rad): remove TODO by using new std function

.github/workflows/push.yml, Justfile, data_structures/src/mainnet_validations.rs, data_structures/tests/inclusion_proofs.rs, node/src/actors/chain_manager/mod.rs, rad/src/reducers/mod.rs, rad/src/types/array.rs, validations/src/tests/mod.rs
That lint was temporarily ignored because of false positives (see #1803), but these false positives have been fixed since then.
(except in one case when using ChainManager, where I add an `#[allow(clippy::field_reassign_with_default)]`)
=> chore: remove allow for clippy lint field_reassign_with_default

Cargo.lock, bridges/centralized-ethereum/Cargo.toml, bridges/centralized-ethereum/src/actors/dr_database.rs, bridges/centralized-ethereum/src/actors/dr_reporter.rs, bridges/centralized-ethereum/src/actors/dr_sender.rs, bridges/centralized-ethereum/src/actors/eth_poller.rs, bridges/centralized-ethereum/src/actors/wit_poller.rs, bridges/centralized-ethereum/src/lib.rs, bridges/centralized-ethereum/wrb_abi.json, data_structures/Cargo.toml
Close #2163
Fix #2046
Fix #2131
=> Bridge batch report

node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/mod.rs
Currently the rewind command is broken because the genesis block is consolidated twice, resulting in error "UTXO did already exist". This pull request fixes it.
=> fix(node): do not consolidate genesis block twice during resync

node/src/actors/chain_manager/mod.rs
To fix the very high memory usage during resync
Fix #2194
=> fix(node): persist chain state during resync

data_structures/src/chain.rs, node/src/actors/json_rpc/json_rpc_methods.rs
As requested in drcpu-github/witnet-explorer-frontend#2, it would be a nice feature to show block weight in the block overview of the explorer. Adding this to the witnet-rust node allows for having one single source of truth.
=> feat(jsonrpc): add block weight as a value to getBlock

data_structures/src/chain.rs, data_structures/src/transaction.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mod.rs, node/src/utils.rs
Part of #2094
The worst that could happen is that a node misses some transactions, which does not sound very dangerous. However if a large portion of the network is affected by this bug, they could create empty blocks that reduce the throughput of the network.
The solution is the same as in #2092
```diff
-// A hashset of recently received transactions hashes
-// Used to avoid validating the same transaction more than once
-pending_transactions: HashSet<Hash>,
+/// Set that stores all the recently received transactions
+seen_transactions: HashSet<Transaction>,
```
=> Fix potential transaction malleability attack vectors

Cargo.lock, crypto/Cargo.toml, crypto/src/key.rs, crypto/src/signature.rs, data_structures/src/chain/mod.rs, node/src/actors/chain_manager/actor.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/signature_mngr.rs, src/cli/node/json_rpc_client.rs, validations/src/tests/mod.rs, validations/src/validations.rs, wallet/src/account.rs, wallet/src/actors/worker/methods.rs, wallet/src/actors/worker/mod.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/factories.rs
This avoids passing a `&Secp256k1` argument to every function that needs to validate signatures.
=> Use global secp256k1 context

util/src/timestamp.rs
The `local_time` function was used to convert from timestamp to local time, and then back to timestamp. I have verified that the result is the same when using the first timestamp directly.
=> refactor(util): remove unused local_time function

config/src/config.rs, config/src/defaults.rs, node/src/storage_mngr.rs, storage/src/backends/rocksdb.rs
The default value is "unlimited", which is the same as the previous behavior.
#2309
=> feat(node): allow to configure max_open_files rocksdb option

.github/workflows/push.yml, Justfile, wallet/src/repository/wallets/mod.rs
Ignoring [uninlined-format-args](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args) for now to avoid making this PR too big.
=> chore: fix clippy warnings for Rust 1.67

data_structures/src/chain/tapi.rs, net/src/client/http/mod.rs, rad/src/lib.rs
=> feat(net): follow http redirects

node/src/actors/rad_manager/handlers.rs
=> fix(node): commit http errors in data request retrieval

data_structures/src/chain/tapi.rs
The first commit removes the hardcoded WIP overwrites, this can definitely be merged.
The second one removes the voting structures for past accepted WIPs, but I'm not sure whether the accepted method is to remove them now or only when new WIPs are proposed.
The `test_initialize_wip_information` test fails due to the removal of accepted WIPs, but it will fail whenever anything is updated with respect to the `BitVotesCounter` since it is specific to one set of WIPs. Not quite sure if you want to keep that test or update it every time or ...?
=> Tapi cleanup

node/src/actors/chain_manager/actor.rs
Previously, own UTXOs were mistakenly being tagged as unusable by inserting their value as their timeout.
Part of #2367, but not quite fixing it.
=> Fix errors in snapshot importing functionality

Cargo.lock, data_structures/src/chain/tapi.rs, node/src/actors/inventory_manager/handlers.rs, node/src/actors/node.rs, partial_struct/tests/partial_struct_derive.rs, rad/Cargo.toml, rad/src/operators/string.rs, rad/src/types/mod.rs, wallet/src/actors/app/handlers/refresh_session.rs, wallet/src/repository/wallet/mod.rs
This should solve the stoppers for https://github.com/witnet/witnet-price-feeds/issues/210#issuecomment-1557134728.
This change may require activation through TAPI, provided that non-updated nodes will commit errors where updated nodes will report normally.
fix #2315 
fix #2338 
@Tommytrg Edit:
Also fix #2373
@aesedepece Edit:
Lol, it fixes itself?
=> feat(rad): decode JSON more efficiently

wallet/src/actors/app/handlers/create_data_req.rs, wallet/src/actors/app/handlers/create_vtt.rs, wallet/src/actors/app/routes.rs, wallet/src/actors/worker/methods.rs, wallet/src/repository/wallet/mod.rs, wallet/src/repository/wallet/tests/mod.rs, wallet/src/types.rs
This opens up the possibility of creating transactions in a wallet without persisting change addresses, which is needed in the case of fee estimations.
Fix #2384
=> fix(wallet): allow generating transactions without persisting change addresses

bridges/centralized-ethereum/src/actors/dr_database.rs, bridges/centralized-ethereum/src/actors/eth_poller.rs
=> fix(bridge): prevent ignoring data requests

data_structures/src/serialization_helpers.rs, net/src/client/http/mod.rs, node/tests/utils.rs, p2p/tests/peers.rs, rad/src/filters/deviation.rs, rad/src/script.rs, src/cli/mod.rs, src/cli/wallet/with_wallet.rs, validations/src/tests/mod.rs, wallet/tests/data_requests.rs
This prevents a potential DoS attack to where witnessing nodes could be forced into a temporal desynchronization state and slashing could be triggered on them on purpose.
=> fix(net): prevent panicking when finding an unknown HTTP status code

node/src/actors/json_rpc/api.rs
- [refactor(jsonrpc): ignore params in signaling_info function](https://github.com/witnet/witnet-rust/commit/0d42a2dd18b4d1eec052700f1a2400dac202790b)
- [docs(jsonrpc): replace signaling_info comment with an appropiate one](https://github.com/witnet/witnet-rust/commit/15c13c602c138b142b8716643fdd7871f7188012)
=> Update function signature in signaling_info function

node/src/actors/json_rpc/api.rs
The  initial suggestion was:
```rs
simple = params.get(1).unwrap_or(false);
```
But, we also have to call `parse` over the possible `String` so the one-liner would be:
```rs
simple = params.get(1).and_then(|v| v.as_str().map(|s| s.parse().unwrap_or(false))).unwrap_or(false);
```
As the previous line looks a bit hard to read, I have used an `if let` which seems more readable.
=> gitfix(jsonrpc): read simple positional argument in getBalance

data_structures/src/staking/aux.rs, data_structures/src/staking/errors.rs, data_structures/src/staking/stake.rs, data_structures/src/staking/stakes.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/json_rpc/api.rs, node/src/actors/messages.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
Implement JSON-RPC and CLI methods that allow querying the stakes of the specified address/addresses argument.
The argument can contain:
- A validator and a withdrawer
- A validator
- A withdrawer
- Empty argument, uses the node's address as validator.
close #2424
close #2423
=> Implement JSON-RPC method queryStakes

node/src/actors/chain_manager/mining.rs
Adds a single return statement in `mining.rs` to prevent the validator still proposing a block even when he's not eligible.
=> fix(mining): abort trying to mine a block when the node is not eligible

data_structures/src/error.rs, node/src/actors/chain_manager/mod.rs, validations/src/validations.rs
I think this is the only spot where we need to reset the collateral age of the validator which mined a block. I am not entirely happy with using `self.current_epoch.unwrap_or_default()`, but it should be safe since we would not get here if `current_epoch` was `None`.
=> feat(mining): reset collateral age of the validator which mined the latest block

src/cli/node/with_node.rs
The arguments to the `query_stakes` function in `with_node.rs` were in the incorrect order which resulted in querying the withdrawer when a validator was requested and vice versa.
=> (fix): switch query-stakes arguments

node/src/actors/chain_manager/mod.rs, node/src/actors/inventory_manager/handlers.rs, node/src/storage_mngr/node_migrations.rs
This PR contains two distinct patches that solve some synchronization issues.
```
-          let protocol_version = get_protocol_version(self.current_epoch);
+          let protocol_version = get_protocol_version(Some(block.block_header.beacon.checkpoint));
```
Pretty self-explanatory. Don't use the current epoch for validating block transactions when synchronizing blocks that may be older than the current protocol version.
```
-               let block_hash = block.hash();
let block_epoch = block.block_header.beacon.checkpoint;
+               let block_hash = block.versioned_hash(get_protocol_version(Some(block_epoch)));
```
Somewhat more involved. When I restart a node that is already in V1.8, I noticed it failed to synchronize. It received new blocks, but did not want to add them …
=> fix(chain_manager): fix some synchronization issues

data_structures/src/chain/mod.rs, data_structures/src/proto/versioning.rs, data_structures/src/staking/helpers.rs, data_structures/src/staking/mod.rs, data_structures/src/staking/stake.rs, data_structures/src/staking/stakes.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/chain_manager/mining.rs, node/src/actors/chain_manager/mod.rs, node/src/actors/session/handlers.rs, validations/src/eligibility/current.rs
=> feat(slashing): lazily slash reluctant block proposers

data_structures/src/staking/stake.rs, data_structures/src/staking/stakes.rs, node/src/actors/chain_manager/handlers.rs, node/src/actors/json_rpc/api.rs, node/src/actors/messages.rs, src/cli/node/json_rpc_client.rs, src/cli/node/with_node.rs
- Add an `all` argument to the `query_stakes` CLI method to query all stake entries.
- Return stake information split by key instead of thee total staked amount
close #2552 
close #2559
=> feat(jsonrpc): allow to query all stake entries

Cargo.lock, config/Cargo.toml, node/src/actors/inventory_manager/handlers.rs, storage/Cargo.toml, wallet/Cargo.toml
When passing a TX id to getBlock, a pseudomigration is run, such that it will crash the node because it can't read enough bytes.
This solution only runs the migration if there are enough bytes to operate on. In this particular case of passing a TX id, it will behave as before (produce a proper error)
=> fix(node): solve potential DoS when passing a TX id to getBlock
