- Cargo.toml
Adds basic configuration file to start working with Cargo.
> Cargo basic configuration

- .hooks/pre-commit
- rustfmt.toml
Also add configuration file for rustfmt at the root of the repository.
> Add linting (rustfmt) pre-commit git hook

- .travis.yml
- Cargo.toml
- Justfile
- config/Cargo.toml
- config/src/lib.rs
- core/src/lib.rs
- crypto/src/lib.rs
- crypto/tests/lib.rs
- data_structures/src/lib.rs
- data_structures/tests/lib.rs
- p2p/src/lib.rs
- src/cli/server.rs
- src/main.rs
- src/server.rs
- storage/src/lib.rs
- wit.toml
Read default values from the config file and update cli to read peer address.
> config: update cli, travis and read config file

- .travis.yml
- Cargo.toml
- config/Cargo.toml
- config/src/lib.rs
- core/Cargo.toml
- core/tests/lib.rs
- crypto/Cargo.toml
- crypto/tests/lib.rs
- data_structures/Cargo.toml
- data_structures/tests/lib.rs
- p2p/Cargo.toml
- p2p/tests/lib.rs
- src/cli.rs
- src/cli/mod.rs
- src/cli/server.rs
- src/main.rs
- storage/Cargo.toml
- storage/tests/lib.rs
- tests/witnet.rs
witnet-rust choose rust edition 2018 for dev.
cc https://rust-lang-nursery.github.io/edition-guide/introduction.html
r? @aesedepece
> upgrade rustc to 2018

- config/src/lib.rs
- core/src/lib.rs
- crypto/src/lib.rs
- data_structures/src/lib.rs
- p2p/src/lib.rs
- src/cli.rs
- src/main.rs
- src/server.rs
- storage/src/lib.rs
> deny 2018 unidiomatic code

- docs/development.md
- mkdocs.yml
Add a first draft for witnet development docs.
> docs: add draft for development guide

- core/Cargo.toml
> chore(dependencies): Add rocksdb-backend feature to witnet_storage

- Justfile
- core/src/actors/config_manager.rs
- core/src/actors/node.rs
- core/src/actors/storage_manager.rs
- docs/architecture/managers/storage-manager.md
- docs/development.md
- src/cli/node.rs
- src/main.rs
Remove unused arguments on cli/node.rs
Add "config" argument to read a config filename
Modify storage manager to read the data base path from config manager
> feat(cli): read config filename

- .travis.yml
- Justfile
Builds will fail if the code is not properly formatted.
> fix(travis): Add rustfmt to travis

- core/src/actors/session.rs
- docs/architecture/session.md
Create Session actor documentation with the currently functionality
> docs(architecture): create Session actor doc

- config/src/lib.rs
- core/src/actors/sessions_manager.rs
Add and doc a bootstrap period variable in config lib
Use this variable in session manager instead of the old constant
Close #88
> refactor(config): add bootstrap period variable

- core/src/actors/peers_manager.rs
- docs/architecture/managers/peers-manager.md
> feat(managers): make StorageManager query peers from storage

- core/src/actors/session.rs
This PR includes:
- Implement get peers handler to session actor(#92)
- Implement peer discovery protocol in session actor(#96)
Tests for #92 and #96 will be implemented in #134 and #135.
Close #92 
Close #96
> feat(core): add getPeers and peerDiscovery handlers to session actor

- docs/development.md
This PR add instructions to install rust and mkdocs, and clang requirement.
> docs(dev): improve doc for developers with mkdocs

- config/Cargo.toml
- core/src/actors/codec.rs
- core/src/actors/connections_manager.rs
- core/src/actors/session.rs
- core/tests/actors/codec.rs
- data_structures/src/builders.rs
This PR includes:
- Feature(actors): implement handshake protocol in `Session` actor
- Refactor(codec): use of BytesMut instead of `Request` and `Response`
- Refactor(managers): remove unused server_address in `SessionsManager`
Closes #52
> feat(actors): implement handshake protocol in Session actor

- core/src/actors/config_manager/mod.rs
- core/src/actors/connections_manager/mod.rs
- core/src/actors/epoch_manager/mod.rs
- core/src/actors/peers_manager/actor.rs
- core/src/actors/peers_manager/handlers.rs
- core/src/actors/peers_manager/mod.rs
- core/src/actors/session/actor.rs
- core/src/actors/session/handlers.rs
- core/src/actors/session/mod.rs
- core/src/actors/sessions_manager/handlers.rs
- core/src/actors/sessions_manager/mod.rs
- data_structures/src/types.rs
- p2p/src/sessions/mod.rs
- src/main.rs
Modify log messages according to:
- INFO: Anything we need to see in the last sprint.
- DEBUG: Stuff developers need to see.
- WARN: Expected errors.
- ERROR: Unexpected errors.
Added Display function to check Message's kind
> fix(core): Modify log messages

- core/src/actors/mempool_manager/actor.rs
- core/src/actors/mempool_manager/mod.rs
- core/src/actors/mod.rs
- core/src/actors/node.rs
- docs/architecture/managers/mempool-manager.md
- mkdocs.yml
- Epic for `MempoolManager` is #138
> feat(mempool manager): Add MempoolManager actor

- core/src/actors/mempool_manager/actor.rs
- core/src/actors/mempool_manager/mod.rs
- core/src/actors/mod.rs
- core/src/actors/node.rs
- core/src/actors/utxo_manager/actor.rs
- core/src/actors/utxo_manager/mod.rs
- docs/architecture/managers/mempool-manager.md
- docs/architecture/managers/utxo-manager.md
- mkdocs.yml
- Epic for `UtxoManager` is #139.
> feat(utxo manager): Add UTXO manager actor

- config/src/loaders/toml.rs
- core/src/actors/mempool_manager/actor.rs
- core/src/actors/mempool_manager/mod.rs
- core/src/actors/mod.rs
- core/src/actors/node.rs
- core/src/actors/utxo_manager/actor.rs
- core/src/actors/utxo_manager/mod.rs
- docs/architecture/managers/mempool-manager.md
- docs/architecture/managers/utxo-manager.md
- mkdocs.yml
- witnet.toml
Solution: Make global state used in tests thread-local
> fix(config tests): Fix race-condition in config tests

- core/src/actors/storage_manager/handlers.rs
- core/src/actors/storage_manager/messages.rs
Modified StorageManager generic messages to accept dynamic key values
> refactor(core): Modify static to dynamic key value in storage messages

- core/src/actors/blocks_manager/handlers.rs
- core/src/actors/blocks_manager/messages.rs
- core/src/actors/session/handlers.rs
- docs/architecture/managers/blocks-manager.md
- docs/architecture/managers/config-manager.md
- docs/architecture/managers/connections-manager.md
- docs/architecture/managers/epoch-manager.md
- docs/architecture/managers/managers.md
- docs/architecture/managers/peers-manager.md
- docs/architecture/managers/sessions-manager.md
- docs/architecture/managers/storage-manager.md
- docs/architecture/session.md
> feat(actors): start block download automatically upon consolidation

- core/src/actors/session/handlers.rs
This PR adds a basic handler for block messages at the Session.
It is to be merged after #201 .
> feat(core): add block handler for the session

- core/src/actors/session/handlers.rs
This PR adds a basic handler for inv messages at the `Session`.
It is to be merged after #184, #188 and #189.
When #189 is merged, a small change will need to be performed to really build `GetData` messages (for the time being, `Inv` messages are built instead).
> feat(core): add inv handler for the session

- core/src/actors/blocks_manager/handlers.rs
- core/src/actors/blocks_manager/messages.rs
- core/src/actors/session/handlers.rs
This is a fast-and-loose solution. It is intended mainly for demo purpose and we should discuss further the implementation that is missing.
> feat(core): Handle GetBlocks message in Session actor

- core/src/actors/inventory_manager/actor.rs
- core/src/actors/inventory_manager/mod.rs
- core/src/actors/mod.rs
- core/src/actors/node.rs
- docs/architecture/managers/inventory_manager.md
- mkdocs.yml
This PR includes:
- Add inventory manager actor.
- Format dependencies of the node.rs file.
Close #208.
> feat(inventory_manager): add inventory manager actor

- core/src/actors/chain_manager/mod.rs
- core/src/actors/json_rpc/json_rpc_methods.rs
- core/src/actors/session/handlers.rs
- data_structures/src/builders.rs
- data_structures/src/chain.rs
- data_structures/src/flatbuffers/protocol_generated.rs
- data_structures/src/serializers.rs
- data_structures/tests/builders.rs
- data_structures/tests/serializers.rs
- docs/interface/json-rpc.md
- docs/protocol/network/data-structures/block.md
- schemas/protocol.fbs
Update block and block header data structures removing the unnecessary block
header with proof from block header and adding it to block.
close #226
close #227
> refactor(data-structures): update block structure

- core/src/actors/chain_manager/handlers.rs
- core/src/actors/chain_manager/messages.rs
- core/src/actors/chain_manager/mod.rs
- core/src/actors/reputation_manager/messages.rs
- core/src/lib.rs
- core/src/validations.rs
- docs/architecture/managers/chain-manager.md
- docs/architecture/managers/reputation-manager.md
Added current epoch validation
Added Proof of Eligibility validation requesting to Reputation Manager
Created validation library in witnet_core to be implemented after Transaction struct has been defined
Updated docs of ReputationManager and ChainManager
Modified ValidatePoE message
> feat(core): Add epoch and PoE validations to the AddNewBlock Handler of ChainManager

- docs/protocol/network/data-structures/transaction.md
> docs(network): specify data structure for transactions

- core/src/validations.rs
- data_structures/src/chain.rs
Added create_merkle_tree function
Added validate_merkle_tree function
> feat(core): Add validation merkle tree function

- core/src/actors/chain_manager/handlers.rs
- core/src/actors/chain_manager/mod.rs
- data_structures/src/chain.rs
- docs/architecture/managers/chain-manager.md
Added block_candidate to the state of ChainManager
Updated chain_info beacon in EpochNotification handler
Added comparing bloc received  to block_candidate validation in AddNewBlock handler
Updated block_candidate in AddNewBlock handler
Added an empty method to send a valid block to InventoryManager (Another Issue)
> feat(core): Add block_candidate state and chain_info update

- core/src/actors/chain_manager/handlers.rs
- core/src/actors/chain_manager/mod.rs
- docs/architecture/managers/chain-manager.md
Created function to send `InventoryItem` to InventoryManager in ChainManager
Send `block_candidate` to InventoryManager
> feat(core): Send block_candidate to InventoryManager

- docs/protocol/network/data-structures/transaction.md
This supersedes #260, but it's still WIP as it's missing _coinbase_ documentation.
> Adapt transaction format to latest discussions

- core/src/actors/epoch_manager/mod.rs
- util/src/timestamp.rs
> refactor(util): improve precision in get timestamp

- core/src/actors/chain_manager/actor.rs
> feat(core): Set current_epoch in ChainManager started function

- config/src/config/mod.rs
- config/src/config/partial.rs
- config/src/defaults.rs
- config/src/loaders/toml.rs
- core/src/actors/mining_manager/actor.rs
- core/src/actors/mining_manager/handlers.rs
- core/src/actors/mining_manager/mod.rs
- core/src/actors/mod.rs
- core/src/actors/node.rs
- data_structures/src/chain.rs
- data_structures/src/serializers.rs
- docs/architecture/managers/mining_manager.md
- docs/configuration/environment.md
- docs/configuration/toml-file.md
> Mining manager

- data_structures/src/chain.rs
- data_structures/src/serializers.rs
> feat(data_structures): implement Hashable trait for Transaction

- core/src/actors/session/handlers.rs
- data_structures/src/chain.rs
- data_structures/src/serializers/decoders.rs
- data_structures/src/serializers/encoders.rs
- data_structures/src/serializers/mod.rs
- data_structures/tests/serializers.rs
> refactor(serializers): split serializers in different files

- core/Cargo.toml
- core/src/actors/chain_manager/actor.rs
- core/src/actors/chain_manager/handlers.rs
- core/src/actors/chain_manager/mod.rs
- core/src/actors/connections_manager/mod.rs
- core/src/actors/epoch_manager/handlers.rs
- core/src/actors/epoch_manager/mod.rs
- core/src/actors/mining_manager/handlers.rs
- core/src/actors/peers_manager/handlers.rs
- core/src/actors/peers_manager/mod.rs
- core/src/actors/session/actor.rs
- core/src/actors/session/handlers.rs
- core/src/actors/session/messages.rs
- core/src/actors/session/mod.rs
- core/src/actors/sessions_manager/handlers.rs
- core/src/actors/sessions_manager/messages.rs
- core/src/actors/sessions_manager/mod.rs
- p2p/src/peers/error.rs
- Improves consistency on what gets logged into different levels across all the modules of the app
- Improves visibility of the most important traces by using flashy colors
- Gets rid of unnecessary `.unwrap()`s
- Improves readability of some handlers
> General improvement to logging messages and levels 

- core/src/actors/chain_manager/handlers.rs
- core/src/actors/chain_manager/messages.rs
- core/src/actors/session/handlers.rs
- data_structures/src/serializers/encoders.rs
- data_structures/src/types.rs
- docs/architecture/managers/chain-manager.md
Created a handler for Transaction msg in Session
Added Transaction(Transaction) in types (FTB not implemented)
Created AddTransaction msg in ChainManager
Close #233
> feat(core): create handler for Transaction msgs in Session

- core/src/actors/chain_manager/handlers.rs
- core/src/actors/chain_manager/mod.rs
> feat(chain_manager): log epoch closing and consolidated block

- core/src/actors/chain_manager/data_request.rs
- core/src/actors/chain_manager/mod.rs
> feat(chain_manager): implement structures for data requests

- core/src/actors/session/handlers.rs
- data_structures/src/builders.rs
- data_structures/src/serializers/decoders.rs
- data_structures/src/serializers/encoders.rs
- data_structures/tests/builders.rs
Co-authored-by: Tommytrg <tomastrg22@gmail.com>
Implemented encode and decode functions to Transaction Command
Add build_transaction test
> feat(data-structures): Add encode and decode to transaction structure

- Cargo.toml
- core/Cargo.toml
- core/src/actors/mod.rs
- core/src/actors/rad_manager/actor.rs
- core/src/actors/rad_manager/handlers.rs
- core/src/actors/rad_manager/messages.rs
- core/src/actors/rad_manager/mod.rs
- docs/architecture/managers/rad-manager.md
- mkdocs.yml
- radon/Cargo.toml
- radon/src/lib.rs
- radon/src/main.rs
Add:
- `RadManager` actor
- `ResolveRA` and `RunConsensus` messages
- `witnet_radon` crate with empty functions: `run_retrieval`, `run_aggregate` and `run_consensus`
> feat(manager): RadManager

- core/src/actors/chain_manager/handlers.rs
- core/src/actors/chain_manager/mod.rs
- core/src/actors/json_rpc/json_rpc_methods.rs
- core/src/utils.rs
- docs/interface/json-rpc.md
Added Transactions to json_rpc inventory function
Added test
Fixed a panic error in `get_output_from_input` function
Updated json_rpc docs
Close #343
> feat(json_rpc): create method for adding transactions through JSON_RPC

- core/src/actors/chain_manager/messages.rs
- core/src/actors/chain_manager/mining.rs
- core/src/actors/chain_manager/mod.rs
- data_structures/src/chain.rs
> feat(chain_manager): add mint transactions into mined blocks + refactor

- core/src/actors/chain_manager/handlers.rs
- core/src/actors/chain_manager/mining.rs
- core/src/actors/chain_manager/mod.rs
- core/src/actors/session/handlers.rs
- core/src/actors/session/messages.rs
- docs/architecture/session.md
Modified `broadcast_block` function to broadcast also `Transactions`
Add validation and broadcasting to reveal transactions
Close #337
> feat(core): broadcast reveal transactions

- core/src/actors/chain_manager/data_request.rs
- core/src/actors/chain_manager/mining.rs
- core/src/actors/rad_manager/handlers.rs
- core/src/actors/rad_manager/messages.rs
execute consensus to all reveals and create tally transaction
Close #358
> feat(mining): create tally transactions

- core/src/actors/chain_manager/mining.rs
- core/src/actors/rad_manager/handlers.rs
- core/src/actors/rad_manager/messages.rs
- rad/src/lib.rs
implemented run_consensus
implemented run_aggregation
implemented RunConsensus Handler
implemented ResolveRA Handler
> feat(rad): implement run_consensus and run_aggregation

- core/src/actors/chain_manager/actor.rs
- core/src/actors/chain_manager/handlers.rs
- core/src/actors/chain_manager/messages.rs
- core/src/actors/chain_manager/mod.rs
- core/src/actors/session/handlers.rs
This PR improves the stability of the node by improving the block synchronization
> refactor(chain_manager): improve synchronization

- core/src/actors/chain_manager/handlers.rs
- data_structures/src/chain.rs
- docs/interface/cli.md
- docs/interface/json-rpc.md
- src/cli.rs
- src/json_rpc_client.rs
- src/main.rs
Returns the output of the transaction that matches the provided output pointer.
```sh
$ witnet cli getOutput <output pointer>
```
Closes #331 
Closes #333
This PR builds on top of #350
> feat(cli): implement get data request command

- core/src/actors/rad_manager/handlers.rs
- rad/src/lib.rs
Modified run_consensus to use `RadonTypes` as input
Add tests for run_aggregation and run_consensus
> test(rad): Add test for run_aggregation and run_consensus

- docs/protocol/serialization.md
- mkdocs.yml
Add a small section about serialization to the protocol documentation.
> docs(protocol): add serialization docs

- Cargo.toml
- wallet/Cargo.toml
- wallet/README.md
- wallet/src/lib.rs
- wallet/src/main.rs
Empty `witnet_wallet` crate that will contain everything related to the development of the wallet. To run the `main` procedure of this crate use:
```sh
$ cargo run -p witnet_wallet
```
> feat(wallet): Add empty wallet crate

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
> feat(core): Create State Machine in ChainManager

- docs/architecture/managers/sessions-manager.md
- node/src/actors/chain_manager/mod.rs
- node/src/actors/messages.rs
- node/src/actors/sessions_manager/handlers.rs
- node/src/actors/sessions_manager/mod.rs
- p2p/src/sessions/mod.rs
- p2p/tests/sessions.rs
> feat(p2p): add safu flag for anycast to peers with consensus

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
Created consolidate_block function
Created data request and tally show info functions
Close #449
> refactor(core): create consolidate_block function

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/messages.rs
- node/src/actors/session/actor.rs
- node/src/actors/session/handlers.rs
- node/src/actors/session/mod.rs
Removed `DiscardExistingInventoryEntries`
Added `EpochNotification` to Session
Changed AddNewBlock to AddCandidates and AddBlocks in Session
> feat(core): change AddNewBlock to AddCandidates and AddBlocks in Session

- Cargo.lock
- data_structures/Cargo.toml
- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- data_structures/src/lib.rs
- data_structures/src/validations.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
This PR it has to be merged after ChainManager refactor
Close #439
> refactor(node): move validations and data_requests from ChainManager to data_structures

- Cargo.lock
- node/Cargo.toml
- wallet/Cargo.toml
- wallet/src/key.rs
- wallet/src/lib.rs
- wallet/src/mnemonic.rs
- wallet/src/server.rs
- wallet/src/signature.rs
This PR contains commits from #432.
WIP: 
- ~~Replace secp256k1 lib with openssl~~
- Add test
> feat(wallet): add address derivation methods

- data_structures/src/validations.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
Modified Result<_, ()> to Result<_, failure::Error> in validations.rs
> feat(data-structures): use failure Error in validations

- data_structures/src/chain.rs
- data_structures/src/validations.rs
Added tags enum in chain.rs
Added transaction_tag function in validations.rs
Close #511
> feat(data_structures): add function to assign tags to transactions

- docs/architecture/managers/chain-manager.md
Updated ChainManager documentation
Close #456
> doc(node): update ChainManager documentation

- docs/interface/wallet.md
- mkdocs.yml
- wallet/src/server.rs
> docs(wallet): document all the wallet JSON-RPC methods

- data_structures/src/chain.rs
- data_structures/src/validations.rs
Added mint validation
Added commit validation
Added reveal validation
Added data request validation
Added tally validation
Close #513 
Close #515 
Close #516 
Close #517 
Close #518
> feat(validations): add specific transaction validations

- data_structures/src/chain.rs
- validations/src/validations.rs
> feat(validations): validate radon scripts

- crypto/src/hash.rs
- crypto/src/merkle.rs
- crypto/tests/lib.rs
- crypto/tests/merkle.rs
> feat(crypto): add progressive merkle tree

- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
Removed ActiveDataRequestPool
Removed data_request_pool state in ChainManager
Refactored all uses of ChainManager.data_request_pool to ChainManager.chain_state.data_request_pool
> refactor(data-structures): remove redundant ActiveDataRequestPool

- data_structures/src/chain.rs
- data_structures/src/tests.rs
- data_structures/tests/builders.rs
- data_structures/tests/serializers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/codec.rs
- rad/src/lib.rs
Created transaction_example and block_example methods
Added Default trait to some structs in chain.rs
Removed redundant code in tests
Modified codec log from debug to trace
Ignored test_run_retrieval_random_api() by connection problems
(Merge after #571)
> Remove redundant code in tests

- node/src/actors/sessions_manager/mod.rs
> Fix(sessions_manager): change "enoght" to "enough"

- docs/contributing.md
- explain commit message convention
- explain PGP-signing
> Improve contribution guide

- docs/contributing.md
- docs/development.md
- simplify cli commands documentations
- explain components better
- list all libraries in the project
- update development scripts
This PR is based on #607
> Improve development documentation

- node/src/actors/chain_manager/mining.rs
> fix(mining): keep mining a block after tally errors

- config/src/defaults.rs
- data_structures/src/chain.rs
- data_structures/src/vrf.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/signature_mngr.rs
- validations/src/validations.rs
> feat(validations): implement rand poe and rep poe validation

- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
- p2p/tests/sessions.rs
- reputation/src/ars.rs
- reputation/src/error.rs
- reputation/src/lib.rs
- reputation/src/trs.rs
Modified log level of synced state to info
Skipped clippy cognitive_complexity warnings
Updated commits every epoch and reveals every consolidated block
Handled ARS queue in epochs without blocks
Added tally change in tally mining
Close #674 
Close #675
> Handle bugs produced by empty epochs

- node/src/storage_mngr.rs
Refactor storage manager to run the actor (which is blocking) behind a `SyncArbiter`.
> refactor(node): run storage in sync-arbiter thread

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
Fixed a bug produced by updating active reputation system before than expected
> fix(node): fix bug in reputation synchronization

- data_structures/src/error.rs
- validations/src/validations.rs
- validations/tests/validations.rs
Created function to validate tally outputs: tally change, dishonest revealers and reveals not found.
Created a test to check this function
Close #687
> feat(validations): include validation for dishonest revealers and tests

- src/cli/mod.rs
Running: `RUST_LOG=witnet=info cargo run node server` will log with the given level defined in the environment variable. To override the environment value use one of the flats: `--debug` or `--trace`.
> refactor(cli): do not override log filter env value

- config/src/config.rs
- config/src/defaults.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
- node/src/utils.rs
- node/tests/utils.rs
Added consensus_c parameter in config
Modified mode_consensus method to use this parameter
Added test to check it
Close #730 
Close #731
> Add consensus parameter threshold in our consensus method

- data_structures/src/chain.rs
- docs/interface/json-rpc.md
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/messages.rs
- node/src/actors/sessions_manager/handlers.rs
Close #727 
* Beacon tip
* Synchronized?
* Number of peers
Sample call:
```
{"jsonrpc":"2.0","id":1,"method":"status"}
```
```
{"jsonrpc":"2.0","result":{"chainBeacon":{"checkpoint":576448,"hashPrevBlock":"eb1a106824538b226454423d7e988b0ec72ce74b9b28f5d0252de2381d41d405"},"numPeersInbound":1,"numPeersOutbound":1,"synchronized":true},"id":1}
```
> JSONRPC: status method for node

- config/src/config.rs
- config/src/defaults.rs
- node/src/actors/peers_manager/actor.rs
> feat(config): add bucketing update period to config

- bridges/ethereum/src/actors/tally_finder.rs
- data_structures/src/chain.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/messages.rs
Allow to use `dataRequestReport` with unfinished data requests. Previously it only worked with finished data requests, by reading the `DataRequestReport` struct from storage. Now it works by checking the in-memory list of data requests before checking the storage. The output format of the method changed slightly, commits and reveals are indexed by pkh.
Example:
```sh
echo '{"jsonrpc":"2.0","id":"1","method":"dataRequestReport","params":["13bdfde626237c392c0784c9f91d6a6faa557a72f82066bc7885b5a58445df0b"]}' | cargo run -- -c witnet.toml node raw
```
We can see how to output changes on every stage of the data request.
```json
{"jsonrpc":"2.0","result":{"block_hash_dr_tx":"e9241eb9a9a7213caaa48e22bcf9887503ca7e3812373e5f584fb37c4f85b1d6","block_hash_tally_tx":null,"commits":{},"reveals":{},"ta …
```
> feat(node): extend dataRequestReport to work with ongoing DRs

- p2p/tests/peers.rs
- rad/src/lib.rs
Remove tests that rely on randomness or HTTP requests.
> Remove non-deterministic tests

- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- data_structures/src/error.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/epoch_manager/handlers.rs
- node/src/actors/epoch_manager/mod.rs
- node/src/actors/messages.rs
- node/tests/actors/epoch_manager.rs
- validations/src/validations.rs
- validations/tests/validations.rs
> Implement time lock for data requests

- Cargo.lock
- config/src/config.rs
- config/src/defaults.rs
- node/src/actors/connections_manager/handlers.rs
- node/src/actors/connections_manager/mod.rs
- node/src/actors/messages.rs
- node/src/actors/peers_manager/actor.rs
- node/src/actors/peers_manager/mod.rs
- node/src/actors/session/actor.rs
- node/src/actors/session/handlers.rs
- node/src/actors/sessions_manager/handlers.rs
- node/src/actors/sessions_manager/mod.rs
- p2p/Cargo.toml
- p2p/src/error.rs
- p2p/src/peers/mod.rs
- p2p/src/sessions/mod.rs
- p2p/tests/peers.rs
> feat(p2p): implement feeler periodically function

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/transaction_factory.rs
- validations/src/tests.rs
- validations/src/validations.rs
> feat(validations): add vtt time_lock validation

- Cargo.lock
- rad/Cargo.toml
- rad/src/error.rs
- rad/src/operators/array.rs
- rad/src/operators/mod.rs
- rad/src/reducers/mod.rs
- rad/src/types/array.rs
- rad/src/types/integer.rs
- rad/src/types/string.rs
This PR adds sort functionality for array types (for integers and strings)
> feat(rad): add array sort operator

- crypto/src/key.rs
- data_structures/src/builders.rs
- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- data_structures/src/vrf.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/messages.rs
- p2p/src/sessions/bounded_sessions.rs
- p2p/src/sessions/mod.rs
- rad/src/operators/array.rs
- reputation/src/ars.rs
- validations/src/validations.rs
Rust 1.38 was released today, and clippy has some new lints which are fixed in this PR.
> Make clippy happy

- rad/src/operators/mod.rs
- rad/src/operators/string.rs
- rad/src/types/map.rs
- rad/src/types/string.rs
> feat(rad): add string match operator

- Cargo.lock
- Cargo.toml
- crypto/Cargo.toml
- crypto/src/key.rs
- crypto/src/lib.rs
- crypto/src/mnemonic.rs
- crypto/src/test_vectors.rs
- src/cli/wallet/with_wallet.rs
- wallet/src/actors/app/handlers/create_wallet.rs
- wallet/src/actors/app/methods.rs
- wallet/src/actors/worker/error.rs
- wallet/src/crypto.rs
- wallet/src/lib.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/mod.rs
- wallet/src/types.rs
Add the ability to create a wallet by importing its master key serialized in [slip32](https://github.com/satoshilabs/slips/blob/master/slip-0032.md).
```json
{
"params": {
"password": "11111111",
"seedSource": "xprv",
"seedData": "xprv1qxqqqqqpg0xyhjjecen2taujv52gzfvq9mfva3rd78zu4rn2qkx6k5j6w0csq0hs9lznqqr59zgleyz93w57mjpk8k837fn7xf43q7r3p37mxn095hysnx"
},
"method": "createWallet",
"id": "1",
"jsonrpc": "2.0"
}
```
```json
{
"id": "1",
"error": {
"data": [
[
"seedData",
"Imported key is not a master key according to its path: m/1'"
]
],
"message": "Validation Error",
"code": 400
},
"jsonrpc": "2.0"
}
```
```json
{
"params": {
"password": "11111111",
"seedSource": "xprv",
"seedData": "xprv1qpujxsyd4hfu0dtwa524vac84e09mjsgnh5h9crl8wrqg58z5wmsuqqcxlqmar3fjhkprndzkpnp2xlze76g4hu7g7c4r4r2m2e6y8 …
```
> Import keys serialized with slip32

- node/src/actors/inventory_manager/handlers.rs
- node/src/actors/inventory_manager/mod.rs
- node/src/actors/session/handlers.rs
[2019-10-28T16:30:31Z WARN  witnet_node::actors::session::handlers] Inventory request: Item not found: block 62adde3e36db3f22774cc255215b2833575f66bf2204011f80c03d34c7c9ea41
> refactor(node): improve error message when inventory item does not exist

- .github/workflows/push.yml
GitHub actions where previously run only upon push.
This PR modifies the GitHub actions configuration so the actions also run upon pull requesting.
> chore: run github actions upon pull requests

- node/src/actors/chain_manager/mod.rs
> feat(reputation): punish non revealer witnesses

- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/mod.rs
This fixes the getTransaction handler
And add tests
Fix #868
> fix(wallet): add missing keys when storing transactions

- .github/workflows/midnight.yml
- .github/workflows/push.yml
- .travis.yml
- Cargo.lock
- config/Cargo.toml
- storage/Cargo.toml
- wallet/Cargo.toml
It looks like it finally compiles in arm
Close #791
> chore: update rocksdb to 0.13

- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- data_structures/src/error.rs
- data_structures/src/radon_error.rs
- data_structures/src/radon_report.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- rad/src/filters/deviation.rs
- rad/src/filters/mod.rs
- rad/src/lib.rs
- rad/src/operators/array.rs
- rad/src/reducers/average.rs
- rad/src/reducers/mod.rs
- rad/src/reducers/mode.rs
- rad/src/types/array.rs
- validations/src/validations.rs
> Liars punishment

- bridges/ethereum/block_relay_abi.json
- bridges/ethereum/src/actors/eth_event_stream.rs
- bridges/ethereum/wbi_abi.json
Upgrade bridge to latest WBI changes.
Closes #909
> Update bridge to wbi

- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- data_structures/src/radon_error.rs
- rad/src/error.rs
- rad/src/lib.rs
- rad/src/types/mod.rs
- validations/src/validations.rs
> fix(data_structures): update reveal stage on zero reveals

- data_structures/src/radon_error.rs
- data_structures/src/radon_report.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/messages.rs
- node/src/actors/rad_manager/handlers.rs
- rad/src/error.rs
- rad/src/lib.rs
- rad/src/operators/string.rs
- rad/src/types/mod.rs
- validations/src/validations.rs
This is WIP.
Fix #938
Close #940
> Fit `RadonError` into `RadonTypes::RadonError`

- wallet/src/actors/app/handlers/create_vtt.rs
- wallet/src/actors/app/handlers/send_transaction.rs
- wallet/src/actors/app/methods.rs
- wallet/src/actors/worker/methods.rs
- wallet/src/db/error.rs
- wallet/src/db/mod.rs
- wallet/src/model.rs
- wallet/src/repository/error.rs
- wallet/src/repository/keys.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/mod.rs
- wallet/src/repository/wallets/mod.rs
- wallet/src/types.rs
This PR:
- re-implements the index transactions business logic
- adds key to DBKeyNotFound error
Closes #956
> fix(wallet): re-implement index transactions

- wallet/src/actors/app/handlers/create_vtt.rs
> feat(wallet): add fields to create VTT method

- data_structures/src/chain.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/peers_manager/actor.rs
- node/src/actors/peers_manager/mod.rs
- node/src/actors/sessions_manager/actor.rs
- node/src/actors/storage_keys.rs
> feat(storage): create dynamic storage keys

- crypto/src/key.rs
- crypto/src/signature.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/signature_mngr.rs
- validations/src/tests.rs
- validations/src/validations.rs
- wallet/src/account.rs
- wallet/src/actors/worker/methods.rs
- wallet/src/actors/worker/mod.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/factories.rs
- wallet/src/types.rs
This improves the node performance.
Tests pass but some functions have too many arguments
> feat: reuse crypto engine context

- Cargo.lock
- rad/Cargo.toml
- rad/src/lib.rs
- wallet/src/actors/app/handlers/run_rad_req.rs
- wallet/src/actors/app/methods.rs
- wallet/src/actors/worker/handlers/run_rad_request.rs
- wallet/src/actors/worker/methods.rs
- wallet/src/types.rs
This PR adds a new function to try data request given a `RadRequest` in order to be used in the wallet and possibly in the future in the CLI.
> Implement a try data request in the rad library

- rad/src/filters/deviation.rs
- rad/src/reducers/average.rs
- rad/src/reducers/deviation.rs
- rad/src/reducers/mod.rs
> fix(rad): ensure current reducers abide by `Fn(Array<T>) -> T`

- validations/src/validations.rs
- wallet/src/repository/wallet/mod.rs
> feat: 1 wit = 10^9 nanowits

- node/src/actors/chain_manager/mining.rs
- validations/src/validations.rs
log::debug!("Probability to mine a block: {:.6}%", probability);
log::debug!( "Probability to be eligible for this data request: {:.6}%", probability );
Close #1001
> feat(logs): show probability in dr and block mining

- node/src/actors/epoch_manager/handlers.rs
> fix: remove error log CheckpointZeroInTheFuture

- Cargo.lock
- data_structures/src/chain.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/messages.rs
- src/cli/node/json_rpc_client.rs
- validations/Cargo.toml
- validations/benches/reppoe.rs
- validations/src/tests.rs
- validations/src/validations.rs
Co-authored-by: Tomasz Polaczyk <tmpolaczyk@gmail.com>
> feat(reputation): implement a dynamic threshold for reppoe

- node/src/actors/chain_manager/handlers.rs
Close #1031 
Validate the candidates with lower VRF hash first
> feat(node): sort block candidates by VRF hash

- Cargo.toml
> chore: draft release 0.7.0

- Cargo.lock
- node/src/actors/chain_manager/mining.rs
- validations/src/validations.rs
> probability to mine a block

- config/src/config.rs
- config/src/defaults.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/mod.rs
- witnet.toml
> fix(genesis): remove mining_genesis flag to avoid genesis inconsistence

- wallet/src/actors/app/handlers/mod.rs
- wallet/src/actors/app/handlers/validate_mnemonics.rs
- wallet/src/actors/app/routes.rs
Add validate mnemonics method to the wallet
> feat: add wallet validate mnemonics method

- witnet.toml
The content of the genesis block referred within is:
https://github.com/witnet/genesis_block/commit/3c8dd4f6ce6ad239167e6baf207f544720dbe09d
> chore: update genesis block hash

- node/src/actors/session/handlers.rs
> log(session): move magic mismatching log error from ERROR to TRACE

- data_structures/src/data_request.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/messages.rs
- node/src/actors/rad_manager/handlers.rs
- validations/src/tests.rs
> fix(mining): fix bug in create_tally function and add tests

- wallet/src/actors/app/handlers/run_rad_req.rs
Rename run rad request method in snake_case
> fix: rename run rad request method in snake_case

- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- data_structures/src/error.rs
- data_structures/src/transaction.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/chain_manager/transaction_factory.rs
- schemas/witnet/witnet.proto
- validations/src/tests.rs
- validations/src/validations.rs
> Add collateral to CommitTransaction

- data_structures/src/data_request.rs
- data_structures/src/error.rs
- validations/src/tests.rs
- validations/src/validations.rs
> Refactor Tally validations

- bridges/ethereum/block_relay_abi.json
- bridges/ethereum/wrb_abi.json
Updated ABIs based on the latest changes in the smart contracts
Co-authored-by:  Mario Cao <mariocao@gmail.com>
> chore: updated ABIs

- config/src/config.rs
- data_structures/src/builders.rs
- data_structures/src/types.rs
- data_structures/tests/builders.rs
- node/src/actors/session/actor.rs
- node/src/actors/session/handlers.rs
- node/src/actors/session/mod.rs
- node/src/actors/sessions_manager/actor.rs
- node/src/actors/sessions_manager/handlers.rs
- p2p/src/sessions/mod.rs
- p2p/tests/sessions.rs
> fix(peering): add public address field to fix bucketing problems

- data_structures/src/data_request.rs
- node/src/actors/chain_manager/mining.rs
- validations/src/tests.rs
- validations/src/validations.rs
> feat(data-request): include collateral in tally

- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- node/src/actors/chain_manager/mining.rs
- src/cli/node/json_rpc_client.rs
- validations/src/tests.rs
- validations/src/validations.rs
> fix: use collateral minimum instead of zero

- docs/get-started/installation/from-source.md
- systemd/README.md
- systemd/runner.sh
- systemd/witnet.service
to make it lighter than using Docker and downloading at every start
it should make possible to run dozens of nodes natively on the host without requiring much
> manage node as service by systemd

- docs/get-started/installation/from-source.md
as explained at https://github.com/witnet/witnet-rust/issues/1043
> fix(apt): added pkg-config compilation dependency

- README.md
- systemd/README.md
Updating contributing and systemd documentation links
To be merged after https://github.com/witnet/documentation/pull/36/ is merged
> docs: update documentation links

- docker/witnet-rust/Dockerfile
- docker/witnet-rust/runner.sh
to solve what was assigned to me in the T8 linked issue.
I will backport https://github.com/witnet/witnet-rust/pull/1140/files when it will be merged.
> feat(docker): runner script just install latest node version

- docker/compose/bertux-operator-stable/docker-compose.yaml
to do as what has been done for the 5 nodes integration of Docker-Compose at https://github.com/witnet/witnet-rust/pull/1143
> fix(docker-compose): do not require customized config file

- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/json_rpc/server.rs
This fixes an error found in one of the bootstrap nodes, which stopped consolidating blocks when it got to 925 subscriptions.
> fix(jsonrpc): remove subscriptions on session close

- witnet.toml
> feat(toml): update consensus constants for Testnet8

- bridges/ethereum/block_relay_abi.json
> update block relay ABI

- data_structures/src/chain.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/messages.rs
- src/cli/node/json_rpc_client.rs
- src/cli/node/with_node.rs
Dont show all the utxo information (because it could be very noisy if you have so many utxos) if you don specific require with "--long" flag
> feat(cli): add long flag to getUtxoInfo

- config/src/config.rs
- config/src/defaults.rs
- data_structures/src/chain.rs
- node/src/actors/chain_manager/mining.rs
- node/tests/serialization.rs
- schemas/witnet/witnet.proto
> Create and mine superblock

- src/cli/mod.rs
Namely, autodetects the name and version of the crate at compile
time so that Sentry can report and pinpoint bugs to specific
releases.
> feat: do more advanced Sentry configuration

- bridges/ethereum/README.md
- bridges/ethereum/block_relay_abi.json
- bridges/ethereum/wrb_abi.json
Update ABIs an change hardcoded addresses for link
> Update to latest ABIs

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/messages.rs
> feat(chain_manager): improve / implement banners for synced / live states

- docker/witnet-rust/downloader.sh
- docker/witnet-rust/migrator.sh
- docker/witnet-rust/runner.sh
(More info in the comments inside the commit changes)
Close #1296
> feat(docker): make the node keep running even after crashing

- node/src/actors/sessions_manager/handlers.rs
> fix(node): remove unwrap that causes "transport endpoint is not connected"

- docker/witnet-rust/migrator.sh
> feat(docker): stop overwriting witnet.toml config file

- data_structures/src/chain.rs
- node/src/actors/chain_manager/handlers.rs
> Log number of pending transactions

- node/src/actors/json_rpc/json_rpc_methods.rs
Added transaction hashes as separate vectors to the JSON object returned by the getBlock RPC call. I use this in my blockchain explorer to parse and add all transactions to my database.
Witnet ID: WIT_IBQ0Z
> feat: add transaction hashes to getBlock RPC call

- node/src/actors/chain_manager/actor.rs
- node/src/actors/epoch_manager/handlers.rs
- node/src/actors/session/actor.rs
> chore: level down some spammy logging lines

- config/src/config.rs
- config/src/defaults.rs
- data_structures/src/chain.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/tests/serialization.rs
- schemas/witnet/witnet.proto
- validations/src/tests.rs
- validations/src/validations.rs
> feat(config): add initial difficulty as a consensus constant

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- validations/src/tests.rs
- validations/src/validations.rs
See PR #1360 
Close #1353 
Close #1354
> feat(validations): validate block candidates completely as they come

- docker/witnet-rust/runner.sh
- witnet.toml
I think it's about time that we go into INFO log level by default.
> feat: set default log level to INFO

- config/src/config.rs
- config/src/defaults.rs
- data_structures/src/chain.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/session/handlers.rs
- node/src/actors/sessions_manager/mod.rs
This environment allows to set consensus_constants in witnet.toml
> feat: add development environment

- rad/src/operators/string.rs
- rad/src/script.rs
> fix(rad): tell integers from floats when converting from JSON to CBOR

- data_structures/src/superblock.rs
- node/src/actors/chain_manager/mod.rs
> feat(superblock): track who voted what

- config/src/config.rs
- config/src/defaults.rs
- data_structures/src/chain.rs
- data_structures/src/superblock.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/tests/serialization.rs
- schemas/witnet/witnet.proto
- validations/src/tests.rs
This PR adds a bootstrapping committee in charge of signing the first superblocks until collateral_age plus activity_period epoch is reached.
> feat (config manager): add bootstrapping_committee

- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
Misc fixes related to superblocks for testnet 9.2
> Superblock fixes

- data_structures/src/superblock.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/messages.rs
- node/src/actors/session/handlers.rs
> feat(node): send superblock votes at the end of the synchronization

- data_structures/src/superblock.rs
- node/src/actors/chain_manager/mod.rs
Signed-off-by: Claudia Bartoli Duncan <claudia@stampery.co> 
This PR includes the consensus in a superblock when at least 2/3 of the members of the current_signing_committee agree on the same superblock, `insert_vote()` .It also implements different consensus states depending on the consensus, `has_consensus()`.
> Add 2/3 validation

- data_structures/src/chain.rs
- data_structures/src/superblock.rs
- node/src/actors/chain_manager/mod.rs
> Refactor superblock state

- config/src/defaults.rs
Change the activity period to 2000, decided after discussion #1416
> (Refactor): Change activity period to 2000

- data_structures/src/superblock.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
This PR adds recovery steps when a reduced committee has been reached
> Increment step by step reduced committee

- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
> refactor(superblock): move superblock creation out of mining

- data_structures/src/error.rs
- node/src/actors/chain_manager/transaction_factory.rs
- validations/src/tests.rs
- validations/src/validations.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/mod.rs
> Disallow data requests with more than one change output

- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/mod.rs
Co-authored-by: Mario Cao <mariocao@gmail.com>
> refactor(node): avoid mutation upon persisting previous chain state

- witnet.toml
> feat(config): disable sentry

- data_structures/src/chain.rs
This should almost never happen in the testnet, because this bug requires two transactions that try to spend the same UTXO, but one of them has at least one additional input.
Example: two transactions T1 and T2.
* T1 has input I1
* T2 has inputs I1 and I2
* T1 is included in a block, making T2 invalid. But the mapping (I2 => T2) is not removed, wasting memory
* However, if another transaction T3 with input I2 is included in a block, the memory is cleared
After PR #1503 this will trigger when removing any transaction from a full `TransactionsPool`, so it should be fixed before that.
> fix(data_structures): avoid potential memory leak in transactions pool

- data_structures/src/chain.rs
- validations/src/validations.rs
> feat(reputation): implement a tie breaker for sort based on hash

- node/src/actors/json_rpc/json_rpc_methods.rs
- src/cli/node/json_rpc_client.rs
Close #1374
Fix #1342 
Sample output:
{"jsonrpc":"2.0","id":"1","method":"getConsensusConstants"}
{"jsonrpc":"2.0","result":{"activity_period":1000,"bootstrap_hash":"00000000000000000001000000000000000000007769746e65742d302e372e30","checkpoint_zero_timestamp":1594018864,"checkpoints_period":30,"collateral_age":5,"collateral_minimum":1000000000,"epochs_with_initial_difficulty":1000,"extra_rounds":3,"genesis_hash":"a0b6496d8de53c5998b89a72bb233c600822e14a3b6709154553c74f90604f23","initial_difficulty":10,"max_dr_weight":8000,"max_vt_weight":2000,"mining_backup_factor":8,"mining_replication_factor":3,"reputation_expire_alpha_diff":20000,"reputation_issuance":1,"reputation_issuance_stop":1048576,"reputation_penalization_factor":0.5,"superblock_period":10},"id":"1"}
> getConsensusConstants JSON-RPC method

- bridges/ethereum/src/actors/witnet_block_stream.rs
- config/src/config.rs
- data_structures/src/superblock.rs
- docker/python-tester/example.py
- net/src/client/tcp/actors/jsonrpc.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/json_rpc/server.rs
- node/src/actors/messages.rs
- wallet/src/actors/app/handlers/node_notification.rs
- wallet/src/actors/app/methods.rs
- wallet/src/actors/app/mod.rs
- wallet/src/actors/app/params.rs
- wallet/src/actors/app/state.rs
- wallet/src/actors/worker/methods.rs
- wallet/src/lib.rs
- wallet/src/params.rs
Solve #1477
Solve #1478
Solve #1494
Solve #1501
> feat(node): signal block consolidation upon creating next superblock

- data_structures/src/superblock.rs
This PR changes the `add_vote` function that now will set as `InvalidIndex` a vote with  a superblockindex minor than the current superblock_index and as `MaybeValid` a vote with superblock_index equal  the current superblock_index +1.
Closes #1547
> MaybeValid if the vote index is x+1

- node/src/actors/chain_manager/mod.rs
This PR changes the function `current_committee_size_requirement` by replacing the default value to the `last_committee_size`.
It also adds a Test
> Change to last_committee_size in comm_size_requirement

- data_structures/src/builders.rs
- data_structures/src/chain.rs
- data_structures/src/superblock.rs
- data_structures/src/types.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/inventory_manager/handlers.rs
- node/src/actors/messages.rs
- node/src/actors/session/handlers.rs
- schemas/witnet/witnet.proto
> Real add superblock

- data_structures/src/superblock.rs
- node/src/actors/chain_manager/mod.rs
> fix(chain manager): compare superblock votes against current index

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
> feat(node): delay commit and reveal processing

- data_structures/src/superblock.rs
Before this PR, the function `get_current_superblock_votes` returned all the votes, including the invalid ones.
Now the function returns only the valid vote.
The PR adds a test to the function.
Closes #1563
> get_superblock_votes return valid votes

- config/src/config.rs
- data_structures/src/chain.rs
- src/cli/node/with_node.rs
Hello!
I implemented show-config command. I made the Config struct be able to be converted into PartialConfig, so that it can be serialized into toml format.
The related issue is #1075
> feat: implemented 'witnet node config' command

- Cargo.lock
- net/Cargo.toml
- node/Cargo.toml
- wallet/Cargo.toml
> chore: remove unused actix-http dependency

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/session/handlers.rs
> fix(node): remove extra block during synchronization

- config/src/config.rs
- config/src/defaults.rs
- data_structures/src/chain.rs
- node/tests/config_test.rs
- witnet.toml
It works with an empty genesis block and wit1mengano as bootstrap committee
> feat(node): enable mainnet environment

- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/state.rs
This PR udpates the wallet DR transacions with the metadata returned by tally.
> feat(update tally balance movements)

- config/src/config.rs
- config/src/defaults.rs
- wallet/src/actors/worker/error.rs
- wallet/src/actors/worker/methods.rs
- wallet/src/lib.rs
- wallet/src/params.rs
- wallet/src/repository/error.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/state.rs
- wallet/src/repository/wallet/tests/mod.rs
> feat(wallet): add sync transient addresses for support wallet imports

- wallet/src/model.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/mod.rs
Mark output type as EXTERNAL, INTERNAL or OTHER
> Add output type

- node/src/actors/session/handlers.rs
- node/src/actors/session/mod.rs
Hello! I Implemented the feature described in https://github.com/witnet/witnet-rust/issues/739.
> feat: implemented penality to unsolicited peers meesages

- node/src/actors/chain_manager/mod.rs
Co-authored-by: Luis Rubio <l.rubiorod@gmail.com>
Co-authored-by: Gorka Irazoqui <gorka.irazoki@gmail.com>
Co-authored-by: Adán SDPC <adan.sdpc@gmail.com>
> fix(chain_manager): avoid broadcast if received block if too old

- node/src/actors/chain_manager/handlers.rs
This PR fix a bug produced when a node is forks and later lose the outbounds. In that case, the node goes to WaitingConsensus state and try to synchronize again. Due to have an invalid block it is impossible to synchronize but it never reverts due to do not check Superblocks during WaitingConsensus state
> fix(node): check forked case during synchronization

- wallet/src/actors/app/handlers/get_addresses.rs
- wallet/src/actors/app/methods.rs
- wallet/src/actors/worker/handlers/get_addresses.rs
- wallet/src/actors/worker/methods.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/mod.rs
> feat(wallet): add getInternal addresses in jsonrpc

- data_structures/src/chain.rs
- data_structures/src/transaction.rs
Close #1668
When running a node in debug mode, the superblock creation step used to take more than 60 seconds. With this PR, it takes less than 1 second. In release mode the difference may not be as noticeable because the node is already fast enough (unless someone is running a node on slow hardware), but with this PR we can support bigger ARS with more identities.
The size of an uncompressed key is 128 bytes, so this PR will increase the memory usage by 128 bytes times the size of the ARS. For an ARS with 2000 identities, this is about 250 KiB.
> Cache uncompressed bn keys

- Cargo.lock
- Cargo.toml
- config/Cargo.toml
- config/src/dirs.rs
> chore: updated directories 2.0.2 to directories-next 1.0.2

- wallet/src/repository/wallet/mod.rs
This PR fixes the update of address payments.
Previously, if Tally or Data Request transactions were returning some change or refunds to the originating address, the `received payments` field of an address was updated wrongly with that "re-funded" amount.
> fix(wallet): update address info only if mint or vtt

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
> feat(node): persist chain state during synchronization

- wallet/src/actors/app/error.rs
- wallet/src/actors/app/methods.rs
This PR improves how errors are passed through to Sheikah instead of mapping most of them to `Internal` errors.
Co-authored-by: Luis Rubio <l.rubiorod@gmail.com>
Closes #1654
> refactor(wallet): move validation errors logic

- wallet/src/actors/app/methods.rs
- wallet/src/actors/app/state.rs
- wallet/src/actors/worker/methods.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/state.rs
> feat(wallet): stop syncing when logging in with another session

- data_structures/src/error.rs
- data_structures/src/transaction.rs
- data_structures/src/transaction_factory.rs
- data_structures/src/utxo_pool.rs
- node/src/actors/chain_manager/handlers.rs
- validations/src/tests.rs
- validations/src/validations.rs
- wallet/src/actors/app/handlers/create_data_req.rs
- wallet/src/actors/app/handlers/create_vtt.rs
- wallet/src/lib.rs
- wallet/src/params.rs
- wallet/src/repository/error.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/factories.rs
- wallet/src/repository/wallet/tests/mod.rs
- wallet/src/types.rs
This PR supersides @girazoki 's PR #1692 
Close #1692 
Close #1635
> Weighted fee

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/inventory_manager/handlers.rs
> refactor(node): remove calls to self.handle

- node/src/actors/peers_manager/actor.rs
> revert: fix(peers_manager): avoid temporarily import peers

- wallet/src/actors/app/methods.rs
- wallet/src/actors/worker/handlers/check_wallet_seed.rs
- wallet/src/actors/worker/handlers/create_data_req.rs
- wallet/src/actors/worker/handlers/create_vtt.rs
- wallet/src/actors/worker/handlers/create_wallet.rs
- wallet/src/actors/worker/handlers/export_master_key.rs
- wallet/src/actors/worker/handlers/gen_address.rs
- wallet/src/actors/worker/handlers/gen_mnemonic.rs
- wallet/src/actors/worker/handlers/get.rs
- wallet/src/actors/worker/handlers/get_addresses.rs
- wallet/src/actors/worker/handlers/get_balance.rs
- wallet/src/actors/worker/handlers/get_transaction.rs
- wallet/src/actors/worker/handlers/get_transactions.rs
- wallet/src/actors/worker/handlers/run_rad_request.rs
- wallet/src/actors/worker/handlers/set.rs
- wallet/src/actors/worker/handlers/sign_data.rs
- wallet/src/actors/worker/handlers/unlock_wallet.rs
- wallet/src/actors/worker/handlers/update_wallet_info.rs
Change structs in wallet in order to avoid unnamed tuples 
closes #1744
> ref(wallet): remove unnamed tuples in wallet

- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/inventory_manager/handlers.rs
- node/src/actors/inventory_manager/mod.rs
- node/src/utils.rs
> Add tests to inventory manager

- .github/workflows/push.yml
Co-authored-by : Tomasz Polaczyk <tmpolaczyk@gmail.com>
> feat(github): modifiy file .github to replace travis

- config/src/config.rs
- config/src/defaults.rs
- data_structures/src/chain.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/messages.rs
- node/src/actors/session/handlers.rs
> Reinsert tx mempool

- data_structures/src/chain.rs
- data_structures/src/lib.rs
- data_structures/src/proto/schema.rs
- data_structures/src/radon_error.rs
- data_structures/src/radon_report.rs
- data_structures/src/transaction.rs
- data_structures/src/types.rs
- data_structures/src/utxo_pool.rs
- data_structures/src/vrf.rs
Add some missing lints to `data_structures/src/lib.rs`. This includes documenting every public field, which may take a while.
> Document data structures

- data_structures/src/mainnet_validations.rs
- validations/src/tests.rs
- validations/src/validations.rs
> feat(validation): add dr open weight to block validation

- data_structures/src/data_request.rs
- validations/src/tests.rs
- validations/src/validations.rs
> feat: disable dr timelock validation

- data_structures/src/chain.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- src/cli/node/json_rpc_client.rs
- wallet/src/actors/app/methods.rs
> refactor(node): remove unnecessary synchronization bool in sycstatus method

- p2p/src/peers/mod.rs
- p2p/tests/buckets.rs
Close #1646
This reverts commits dd03818b024f54bdb612b792081226079d82f560 and 676a46b1ee5a004d6b8a6c40c5af2ad771fcc7a2
> Remove p2p ice hack

- wallet/src/model.rs
This PR adds a small fix in a test that was being ignored in the wallet file model.rs
> fix(wallet): small bug in a test

- wallet/src/model.rs
- wallet/src/repository/keys.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/mod.rs
> fix(wallet): fix AddressInfo received_amount and received_payments 

- wallet/src/actors/app/routes.rs
> fix(wallet): fix error serialization

- Cargo.lock
- wallet/Cargo.toml
- wallet/src/signal.rs
> fix(wallet): fix ctrl-c handler in windows

- Cargo.lock
- wallet/Cargo.toml
- wallet/src/signal.rs
> feat(wallet): update tokio_signal ctrl-c handler

- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/session/handlers.rs
- rad/src/operators/string.rs
> Fix possible overflow when calculating absolute value

- wallet/src/repository/wallet/mod.rs
Co-authored-by: Mario Cao <mariocao@gmail.com>
Close #1836
> fix(wallet): update confirmed balance after resynchronization

- rad/src/operators/array.rs
- rad/src/operators/map.rs
- rad/src/operators/string.rs
- rad/src/script.rs
- rad/src/types/array.rs
- rad/src/types/map.rs
- wallet/tests/data_requests.rs
Fix #1847 
Alternative to PR #1848 that ensures that the RadonMap implementation is deterministic.
> Use RadonMap ordered by key

- config/src/config.rs
- config/src/defaults.rs
- node/src/actors/sessions_manager/actor.rs
- node/src/actors/sessions_manager/handlers.rs
- p2p/src/peers/mod.rs
- p2p/src/sessions/mod.rs
- p2p/tests/sessions.rs
- witnet.toml
This PR changes the sybil rejection from 16 bits to a parameter from the config file
> feat(node): change sybil rejection to /14

- data_structures/src/error.rs
- validations/src/tests.rs
- validations/src/validations.rs
> Non zero timelocks

- Cargo.lock
- data_structures/Cargo.toml
- data_structures/src/chain.rs
- data_structures/src/superblock.rs
* Change algorithm to calculate first (close #1891)
* Remove collision check from `magic_partition_2`, use modulo instead
> Implement latest changes to superblock consensus algorithm

- Cargo.lock
> chore: update generic-array

- bridges/centralized-ethereum/src/actors/dr_reporter.rs
This PR queries the gas price of a data request so that the same value is used when reporting the result
> feat(bridge): use dr_gas_price for reporting result

- Cargo.lock
- bridges/centralized-ethereum/Cargo.toml
- bridges/centralized-ethereum/src/actors/dr_database.rs
- bridges/centralized-ethereum/src/config.rs
- bridges/centralized-ethereum/src/main.rs
- node/src/storage_mngr.rs
- witnet_centralized_ethereum_bridge.toml
> Use StorageManager to persist and load the bridge database

- bridges/centralized-ethereum/src/actors/dr_reporter.rs
- bridges/centralized-ethereum/src/config.rs
- witnet_centralized_ethereum_bridge.toml
Co-authored-by: Tomasz Polaczyk <tmpolaczyk@gmail.com>
> feat(bridge): add maximum data request's result size

- validations/src/tests.rs
Implements the tests described in #1920
> Tapi block validation tests

- config/src/config.rs
- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- data_structures/src/mainnet_validations.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/inventory_manager/handlers.rs
- node/src/actors/messages.rs
- node/src/actors/rad_manager/handlers.rs
- validations/src/tests.rs
- validations/src/validations.rs
> feat(node): implement TAPI signaling

- wallet/src/actors/app/handlers/create_wallet.rs
- wallet/src/actors/app/handlers/unlock_wallet.rs
- wallet/src/actors/app/methods.rs
- wallet/src/actors/app/tests/mod.rs
- wallet/src/actors/worker/error.rs
- wallet/src/actors/worker/handlers/create_wallet.rs
- wallet/src/actors/worker/methods.rs
- wallet/src/lib.rs
- wallet/src/params.rs
- wallet/src/repository/keys.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/state.rs
- wallet/src/repository/wallet/tests/factories.rs
- wallet/src/repository/wallets/mod.rs
- wallet/src/types.rs
Synchronize wallet from birth_date param instead of genesis
Closes #1919
> Birthdate sync

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/messages.rs
- node/src/actors/session/actor.rs
- node/src/actors/session/handlers.rs
- node/src/actors/session/mod.rs
- node/src/actors/sessions_manager/handlers.rs
- node/src/actors/sessions_manager/mod.rs
- p2p/src/peers/mod.rs
Close #1969 
Close #1971 
Close #1970
Close #1972
> Improve peering process using SuperBlock consensus information

- config/src/config.rs
- data_structures/src/chain.rs
- data_structures/src/data_request.rs
- data_structures/src/mainnet_validations.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/inventory_manager/handlers.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- node/src/actors/messages.rs
- node/src/actors/rad_manager/handlers.rs
- node/src/storage_mngr.rs
- node/src/storage_mngr/node_migrations.rs
- validations/benches/reppoe.rs
- validations/src/tests.rs
- validations/src/validations.rs
This implements the logic described in [WIP0014](https://github.com/witnet/WIPs/blob/master/wip-0014.md), but it does not activate it yet. The activation date (start of the voting period) will be decided in another PR.
Note that this includes some changes to the storage format, so any nodes that upgrade to this version will not be able to downgrade.
Close #1921
Close #1923
Close #1924
Close #1925
Close #1926
> Merge TAPI branch into master

- data_structures/src/mainnet_validations.rs
Before this PR, if we can include a wip with the same name but different fields (like init, end...), it wasn't modified. So you should clear the storage to apply it. With this change, a wip with different fields is considered new so it will included
> fix(tapi): insert wips that have modifications

- Cargo.lock
- bridges/centralized-ethereum/Cargo.toml
- bridges/centralized-ethereum/src/actors/dr_reporter.rs
- bridges/centralized-ethereum/src/actors/dr_sender.rs
- bridges/centralized-ethereum/src/actors/eth_poller.rs
- bridges/centralized-ethereum/src/actors/wit_poller.rs
- bridges/centralized-ethereum/src/lib.rs
- bridges/centralized-ethereum/src/main.rs
> fix(bridge): retry on timeout

- node/src/actors/chain_manager/mod.rs
If the init date of a voting WIP is slightly old (for example, if a node updates to the new version a few days after the init epoch), the update TAPI process can take a few minutes to run. For reference, my node can process about 1500 blocks per second. This PR adds a simple progress indicator.
> feat(node): add logs to tapi update from blocks

- src/cli/node/json_rpc_client.rs
- src/cli/node/with_node.rs
> feat(cli): add CLI method for TAPI information

- node/src/actors/chain_manager/mod.rs
- node/src/actors/connections_manager/mod.rs
- node/src/actors/epoch_manager/mod.rs
- node/src/actors/inventory_manager/mod.rs
- node/src/actors/json_rpc/connection.rs
- node/src/actors/json_rpc/server.rs
- node/src/actors/node.rs
- node/src/actors/peers_manager/actor.rs
- node/src/actors/peers_manager/mod.rs
- node/src/actors/rad_manager/handlers.rs
- node/src/actors/rad_manager/mod.rs
- node/src/actors/session/mod.rs
- node/src/actors/sessions_manager/mod.rs
- node/src/config_mngr.rs
- node/src/signature_mngr.rs
- node/src/storage_mngr.rs
- node/src/utils.rs
- src/cli/node/with_node.rs
Fix #1934
How to test: add a panic somewhere in the node and check that the node stops after showing the panic message.
> feat(node): stop actor system if any essential actor panics

- bridges/centralized-ethereum/src/actors/dr_reporter.rs
- bridges/centralized-ethereum/src/actors/eth_poller.rs
- bridges/centralized-ethereum/src/config.rs
- witnet_centralized_ethereum_bridge.toml
> feat(bridge): add timeout to call_with_confirmations

- wallet/src/repository/wallet/tests/mod.rs
> test(wallet): test use_unconfirmed_utxos

- bridges/centralized-ethereum/src/actors/dr_reporter.rs
- bridges/centralized-ethereum/src/lib.rs
To ensure that when a transaction reverts it does not set the data request as finished
As I reported in #2015:
> But I found another bug, as you see in the logs it says Data request 4 inserted with state Finished two times. Sending two transactions is expected because the first one may have a small fee or something, but only one of the transactions will succeed so only one of them should be written in the database. But we currently don't check the status code of a transaction and we write both to the database, each of them overwriting the old transaction hash.
Actually, the ethereum transaction hash is not stored, only the witnet transaction hash, so that is not a problem. But it may result in some data requests wrongly marked as finished.
~~TODO: if the transaction fails it may be …
> fix(bridge): handle receipt of reportResult

- bridges/centralized-ethereum/src/actors/dr_reporter.rs
- bridges/centralized-ethereum/src/actors/eth_poller.rs
- bridges/centralized-ethereum/src/lib.rs
> fix(bridge): handle deleted requests

- node/src/actors/chain_manager/mod.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- src/cli/node/json_rpc_client.rs
- src/cli/node/with_node.rs
> feat(cli): add dry-run to sendRequest CLI method

- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mod.rs
> fix(superblock): process temporal sb votes when AlmostSynced instead of Synced 2

- node/src/actors/rad_manager/handlers.rs
- rad/src/error.rs
- rad/src/operators/array.rs
- rad/src/types/mod.rs
- validations/src/tests/mod.rs
- validations/src/validations.rs
Implement [WIP-0018](https://github.com/witnet/WIPs/blob/master/wip-0018.md)
TODO: the signaling bit is not assigned yet, but we may consider to merge wips 0017-0019.
> Unhandled intercept v2 (implement WIP-0018)

- node/src/actors/rad_manager/handlers.rs
> feat(rad): add a maximum for retrieval timeout

- src/cli/node/json_rpc_client.rs
- src/cli/node/with_node.rs
Close #2072
Adds a `--run-tally` flag to `dataRequestReport` CLI method.
Example:
```
$ witnet node dataRequestReport 63c1ff0bacd24676bd71fa2bb984e8faee22cd8c73b14b83c57149a792dc315c --run-tally
[...]
Tally: RadonTypes::RadonError(UnhandledIntercept { inner: None, message: Some("inner: ModeTie { values: RadonArray { value: [String(RadonString { value: \"149.28.82.190\" }), String(RadonString { value: \"138.201.132.240\" }), String(RadonString { value: \"199.192.30.223\" }), String(RadonString { value: \"159.89.7.193\" }), String(RadonString { value: \"138.201.65.62\" }), String(RadonString { value: \"195.201.61.247\" }), String(RadonString { value: \"149.28.82.190\" }), String(RadonString { value: \"138.201.132.40\" }), String(RadonString { value: \"136.243.93.244\" }), String(RadonString …
```
> feat(cli): allow running tally locally in dataRequestReport CLI method

- node/src/actors/rad_manager/handlers.rs
> Timeout per source

- rad/src/lib.rs
> fix(rad): add timing information to rng requests

- bridges/centralized-ethereum/src/lib.rs
And show warnings if the ethereum node is syncing
Fix #2141
> fix(bridge): ignore rust-web3 error when eth_syncing returns true

- node/src/actors/json_rpc/json_rpc_methods.rs
Currently, fetching a data request completed before activation of WIP0019 results in that data request being displayed with an `Unknown` RADRetrieve kind due to the changes made to retrieval types. Obviously, this is not correct, these data requests were correct at the time and them being shown as invalid could result in incorrect on-chain analysis and can also be considered a problem for tools suchs as the explorer or external wallets. 
Before this patch, an RPC call to below data requests results in the RADRetrieve kind to be shown as `Unknown`.
`./witnet node transaction a065dbeb6d8efa142555e82dab51fe0e5c31a985e43ea55949a01f261a143fcc`
`{"jsonrpc":"2.0","result":{"blockHash":"392b6dbda4e0ac7cb73a17c40e4a01ad30e96e1302d370dcc653c037b701aabf","confirmed":true,"transaction":{"DataRequest": …
> fix(jsonrpc): replace RADType::Unknown with RADType::HttpGet for data requests older than the WIP0019 activation epoch

- README.md
> fix: fix contributing link in README

- node/src/actors/json_rpc/json_rpc_methods.rs
> feat(node): add blockEpoch to response of get_transaction

- data_structures/src/mainnet_validations.rs
> feat: include WIP0020-0021 in list of enabled WIPs

- Cargo.toml
- config/Cargo.toml
- crypto/Cargo.toml
- data_structures/Cargo.toml
- futures_utils/Cargo.toml
- net/Cargo.toml
- node/Cargo.toml
- node/src/actors/inventory_manager/handlers.rs
- node/src/actors/rad_manager/handlers.rs
- p2p/Cargo.toml
- partial_struct/Cargo.toml
- protected/Cargo.toml
- rad/Cargo.toml
- reputation/Cargo.toml
- rustfmt.toml
- storage/Cargo.toml
- toolkit/Cargo.toml
- util/Cargo.toml
- validations/Cargo.toml
- wallet/Cargo.toml
> chore: update code to 2021 edition

- rad/src/lib.rs
- rad/src/types/string.rs
> Remove unneeded wip checks

- bridges/centralized-ethereum/src/actors/dr_database.rs
- bridges/centralized-ethereum/src/actors/dr_reporter.rs
- bridges/centralized-ethereum/src/actors/eth_poller.rs
- bridges/centralized-ethereum/src/config.rs
- witnet_centralized_ethereum_bridge.toml
> Bridge report result fixes

- data_structures/src/transaction.rs
> feat: implement script transaction weight calculation

- .github/actions/build-helper/action.yml
- .github/actions/build-linux/action.yml
- .github/actions/download-releases/action.yml
- .github/workflows/master.yml
- RELEASE.md
- docker/witnet-rust/Dockerfile
- docker/witnet-rust/downloader.sh
Visualization:
Entire workflow is triggered by pushing a new tag
> ci: ✨  CD for witnet-rust

- bridges/centralized-ethereum/src/actors/dr_sender.rs
- bridges/centralized-ethereum/src/actors/dr_sender/tests.rs
- data_structures/src/chain.rs
- node/src/actors/json_rpc/json_rpc_methods.rs
- rad/src/types/integer.rs
- validations/src/validations.rs
> Fix bridge collateral

- Cargo.lock
- bridges/centralized-ethereum/Cargo.toml
- net/Cargo.toml
- net/src/client/tcp/actors/jsonrpc.rs
- node/Cargo.toml
- node/src/actors/epoch_manager/mod.rs
- wallet/Cargo.toml
[Changelog](https://github.com/actix/actix/blob/master/actix/CHANGES.md)
> chore: update actix to 0.13

- config/src/config.rs
- config/src/defaults.rs
- wallet/src/lib.rs
- wallet/src/params.rs
- wallet/src/repository/wallet/mod.rs
- wallet/src/repository/wallet/tests/factories.rs
> feat(wallet): add pending_tx_timeout_seconds config variable

- .github/actions/versions-match/action.yml
- .github/workflows/push.yml
- Cargo.lock
- node/Cargo.toml
> feat(ci): ensure version of some subcrates matches that of main crate

- data_structures/src/chain/mod.rs
- data_structures/src/serialization_helpers.rs
- data_structures/src/transaction_factory.rs
- data_structures/src/utxo_pool.rs
- data_structures/src/utxo_pool/utxo_db.rs
- data_structures/tests/utxo_pool.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/inventory_manager/handlers.rs
- src/cli/node/json_rpc_client.rs
- validations/src/tests/mod.rs
- validations/src/validations.rs
- wallet/src/actors/worker/methods.rs
> refactor: get rid of some explicit cloning

- Cargo.lock
- util/src/timestamp.rs
> chore: update chrono to 0.4.23

- bridges/centralized-ethereum/src/actors/eth_poller.rs
- bridges/centralized-ethereum/src/config.rs
> feat(bridge): add skip_first config param to allow skipping requests

- Cargo.lock
- Cargo.toml
- crypto/Cargo.toml
- src/cli/node/json_rpc_client.rs
Supersede #2322 #2334 #2336 #2339 #2343
Fix #1643
> Dependabot prs

- data_structures/src/chain/tapi.rs
- data_structures/src/radon_error.rs
- net/src/client/http/mod.rs
- node/src/actors/chain_manager/mining.rs
- rad/src/error.rs
- rad/src/lib.rs
- rad/src/types/mod.rs
- validations/src/tests/mod.rs
- validations/src/validations.rs
> feat: introduce new EncodeReveal error

- data_structures/src/chain/tapi.rs
- data_structures/src/radon_report.rs
- rad/src/error.rs
- rad/src/lib.rs
- rad/src/operators/array.rs
- rad/src/operators/map.rs
- rad/src/operators/mod.rs
- rad/src/operators/string.rs
- rad/src/script.rs
- rad/src/types/array.rs
- rad/src/types/float.rs
- rad/src/types/integer.rs
- rad/src/types/map.rs
- rad/src/types/mod.rs
- rad/src/types/string.rs
Follow-up to #1784
Fix #1133
Fix #2225
> Rad replace separators

- Cargo.lock
- Cargo.toml
- bridges/centralized-ethereum/Cargo.toml
- bridges/centralized-ethereum/src/actors/dr_reporter.rs
- bridges/centralized-ethereum/src/config.rs
- bridges/centralized-ethereum/src/lib.rs
- bridges/centralized-ethereum/src/main.rs
- data_structures/src/builders.rs
- node/Cargo.toml
- toolkit/Cargo.toml
- witnet_centralized_ethereum_bridge.toml
> Witnet 1.5.6

- bridges/centralized-ethereum/src/actors/dr_sender.rs
- bridges/centralized-ethereum/src/actors/dr_sender/tests.rs
- config/src/config.rs
- config/src/defaults.rs
- data_structures/src/chain/tapi.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/tests/data_request_examples.rs
- rad/src/operators/mod.rs
- src/cli/node/json_rpc_client.rs
- validations/src/tests/mod.rs
- validations/src/validations.rs
- wallet/src/actors/app/handlers/create_data_req.rs
- witnet.toml
This is be a follow-up to #2348. I'm closing the former.
Close #2344
> TAPI bits for 1.6 improvement proposals

- bridges/centralized-ethereum/src/actors/dr_sender.rs
- bridges/centralized-ethereum/src/actors/dr_sender/tests.rs
- config/src/config.rs
- config/src/defaults.rs
- data_structures/src/chain/tapi.rs
- data_structures/src/data_request.rs
- node/src/actors/chain_manager/actor.rs
- node/src/actors/chain_manager/handlers.rs
- node/src/actors/chain_manager/mining.rs
- node/src/actors/chain_manager/mod.rs
- node/src/actors/inventory_manager/handlers.rs
- node/tests/data_request_examples.rs
- rad/src/operators/mod.rs
- src/cli/node/json_rpc_client.rs
- validations/src/tests/mod.rs
- validations/src/validations.rs
- wallet/src/actors/app/handlers/create_data_req.rs
- witnet.toml
This integrates #2277 on top of #2352.
> Integrate WIP-0023 into 1.6 branch

- Cargo.lock
- Cargo.toml
- bridges/centralized-ethereum/Cargo.toml
- data_structures/Cargo.toml
- node/Cargo.toml
- toolkit/Cargo.toml
- wallet/Cargo.toml
> chore(cargo): update crate versions to 1.6.2

- bridges/centralized-ethereum/src/actors/dr_reporter.rs
This avoids a division by zero panic that was going under our radar after the introduction of `report_result_max_network_gas_price_ratio`.
> fix(bridge): prevent reporting if report gas price can't be fetched from WRB

- schemas/witnet/witnet.proto
> fix(schemas): remove optional label from ValueTransferOutput in StakeTransactionBody

- Cargo.lock
- Cargo.toml
- bridges/centralized-ethereum/Cargo.toml
- data_structures/Cargo.toml
- node/Cargo.toml
- toolkit/Cargo.toml
- wallet/Cargo.toml
Just for the CI to show if everything is ready for tagging.
> chore(cargo): this is 2.0.0-rc.2

- bridges/centralized-ethereum/src/actors/watch_dog.rs
Update the log message to include the name of the method that is failing
Close #2566
> chore(watch_dog): log method name on error

- node/src/actors/json_rpc/api.rs
- node/src/actors/messages.rs
> feat(json_rpc): allow filtering get_utxo_info by min_value or from_signer
